//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSNumber, NSString, PinField, PinKeypad, UIButton, UILabel, UITextInputPasswordRules, UIViewController;
@protocol PinViewDelegate;

@interface PinView : UIView
{
    UILabel *_titleLabel;	// 8 = 0x8
    PinField *_pinField;	// 16 = 0x10
    UIView *_dividerLine;	// 24 = 0x18
    double _scale;	// 32 = 0x20
    _Bool _autoKeyboard;	// 40 = 0x28
    _Bool _keypadActive;	// 41 = 0x29
    _Bool _pinEntered;	// 42 = 0x2a
    PinKeypad *_keypad;	// 48 = 0x30
    struct CGRect _keyboardDefaultFrame;	// 56 = 0x38
    NSNumber *_pinMinLength;	// 88 = 0x58
    NSNumber *_pinCharset;	// 96 = 0x60
    UIViewController *_viewController;	// 104 = 0x68
    id <PinViewDelegate> _delegate;	// 112 = 0x70
    UIButton *_cancelButton;	// 120 = 0x78
    NSString *_title;	// 128 = 0x80
}

- (void).cxx_destruct;	// IMP=0x002000000000f348
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak id <PinViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)setViewController:(id)arg1;	// IMP=0x001000000000f2e8
- (id)viewController;	// IMP=0x001000000000f2d7
- (void)deleteBackward;	// IMP=0x001000000000f2ba
- (void)insertText:(id)arg1;	// IMP=0x001000000000f29d
@property(readonly, nonatomic) _Bool hasText;
@property(nonatomic, getter=isSecureTextEntry) _Bool secureTextEntry;
@property(nonatomic) long long autocapitalizationType;
@property(nonatomic) long long returnKeyType;
@property(nonatomic) long long keyboardAppearance;
@property(nonatomic) long long keyboardType;
@property(nonatomic) long long autocorrectionType;
@property(nonatomic) long long spellCheckingType;
- (void)pinEntered:(id)arg1;	// IMP=0x001000000000f09c
- (void)_setKeyboardUserInteractionEnabled:(_Bool)arg1;	// IMP=0x001000000000f015
- (void)_dismissKeypad;	// IMP=0x001000000000efc6
- (void)_deactivateKeypadView;	// IMP=0x001000000000ef8c
- (void)_activateKeypadView;	// IMP=0x001000000000edff
- (_Bool)resignFirstResponder;	// IMP=0x001000000000ed60
- (_Bool)becomeFirstResponder;	// IMP=0x001000000000ece1
- (_Bool)canBecomeFirstResponder;	// IMP=0x001000000000ecbe
- (struct CGRect)_roundRectToPixel:(struct CGRect)arg1;	// IMP=0x001000000000ec22
- (double)_roundToPixel:(double)arg1;	// IMP=0x001000000000ebf5
- (void)_layoutSubviewsWithKeyboard:(struct CGRect)arg1;	// IMP=0x001000000000e7ba
- (void)layoutSubviews;	// IMP=0x001000000000e4ba
- (void)keyboardDidShow:(id)arg1;	// IMP=0x001000000000e367
- (void)dealloc;	// IMP=0x001000000000e2c6
- (id)initWithPinLength:(id)arg1 minLength:(id)arg2 maxLength:(id)arg3 charset:(id)arg4;	// IMP=0x001000000000deac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool enablesReturnKeyAutomatically;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) UITextInputPasswordRules *passwordRules;
@property(nonatomic) long long smartDashesType;
@property(nonatomic) long long smartInsertDeleteType;
@property(nonatomic) long long smartQuotesType;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *textContentType;

@end

