//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableOrderedSet, NSNumber, NSOperationQueue, NSString, NSURL, NSXPCConnection, SDAirDropActivity, SDPeopleBrowser, SDScreenTimeMonitor, SDShareSheetProxyLoaderManager, SDSuggestionBrowser, SDXPCHelperConnection, SFAirDropNode, UIImpactFeedbackGenerator, UINotificationFeedbackGenerator, UISUIActivityViewControllerConfiguration, UISelectionFeedbackGenerator, _UIActivityHelper, _UIUserDefaultsActivity;
@protocol SDShareSheetSessionDelegate;

__attribute__((visibility("hidden")))
@interface SDShareSheetSession : NSObject
{
    _Bool _activateCalled;	// 8 = 0x8
    _Bool _airDropAllowed;	// 9 = 0x9
    _Bool _engagedWithSheet;	// 10 = 0xa
    _Bool _sentInitialConfiguration;	// 11 = 0xb
    _Bool _sharingExpanded;	// 12 = 0xc
    _Bool _shouldSuggestFamilyMembers;	// 13 = 0xd
    _Bool _isSharePlayAvailable;	// 14 = 0xe
    _Bool _partialSlotsRendering;	// 15 = 0xf
    _Bool _itemsRequested;	// 16 = 0x10
    _Bool _itemsReady;	// 17 = 0x11
    _Bool _firedImpactHaptic;	// 18 = 0x12
    _Bool _transferActive;	// 19 = 0x13
    _Bool _invalidateCalled;	// 20 = 0x14
    int _sharedItemsCount;	// 24 = 0x18
    id <SDShareSheetSessionDelegate> _delegate;	// 32 = 0x20
    NSString *_sessionID;	// 40 = 0x28
    long long _sharedItemsRequestID;	// 48 = 0x30
    long long _attachmentCount;	// 56 = 0x38
    NSMutableOrderedSet *_cachedSharedItems;	// 64 = 0x40
    NSOperationQueue *_operationQueue;	// 72 = 0x48
    long long _generatedPreviews;	// 80 = 0x50
    NSMutableDictionary *_sharedItemsMap;	// 88 = 0x58
    NSMutableDictionary *_sharedItemsRequestIDToPreviewPhoto;	// 96 = 0x60
    long long _lastTransferEvent;	// 104 = 0x68
    UINotificationFeedbackGenerator *_notificationHaptic;	// 112 = 0x70
    UISelectionFeedbackGenerator *_selectionHaptic;	// 120 = 0x78
    UIImpactFeedbackGenerator *_impactHaptic;	// 128 = 0x80
    SDAirDropActivity *_activeAirDropActivity;	// 136 = 0x88
    _UIUserDefaultsActivity *_shareUserDefaultsActivity;	// 144 = 0x90
    SDScreenTimeMonitor *_screenTimeMonitor;	// 152 = 0x98
    SFAirDropNode *_selectedNode;	// 160 = 0xa0
    NSMutableDictionary *_transferNodes;	// 168 = 0xa8
    SFAirDropNode *_selectedRecipient;	// 176 = 0xb0
    SDPeopleBrowser *_peopleBrowser;	// 184 = 0xb8
    SDSuggestionBrowser *_suggestionBrowser;	// 192 = 0xc0
    SDXPCHelperConnection *_xpcHelperCnx;	// 200 = 0xc8
    _UIActivityHelper *_activityHelper;	// 208 = 0xd0
    NSXPCConnection *_connection;	// 216 = 0xd8
    UISUIActivityViewControllerConfiguration *_hostConfiguration;	// 224 = 0xe0
    NSArray *_orderedPresentableActivities;	// 232 = 0xe8
    NSDictionary *_bundleIDToActivities;	// 240 = 0xf0
    NSArray *_airDropPeople;	// 248 = 0xf8
    NSArray *_suggestedPeople;	// 256 = 0x100
    NSArray *_shareActivities;	// 264 = 0x108
    NSDictionary *_shareActivitiesByUUID;	// 272 = 0x110
    NSArray *_shareActivitiesInUserOrder;	// 280 = 0x118
    NSArray *_visibleShareActivities;	// 288 = 0x120
    NSArray *_actionActivities;	// 296 = 0x128
    NSDictionary *_actionActivitiesByUUID;	// 304 = 0x130
    NSArray *_actionActivitiesInUserOrder;	// 312 = 0x138
    NSArray *_visibleActionActivities;	// 320 = 0x140
    NSArray *_favoriteApps;	// 328 = 0x148
    NSArray *_favoriteActions;	// 336 = 0x150
    NSArray *_airDropNodes;	// 344 = 0x158
    NSArray *_peopleNodes;	// 352 = 0x160
    NSArray *_hostShareActivityProxies;	// 360 = 0x168
    NSArray *_hostActionActivityProxies;	// 368 = 0x170
    NSMutableDictionary *_realNameToNodeID;	// 376 = 0x178
    NSMutableDictionary *_shareActivityToID;	// 384 = 0x180
    NSMutableDictionary *_actionActivityToID;	// 392 = 0x188
    NSNumber *_nearbyCountSlotID;	// 400 = 0x190
    long long _nearbyCountBadge;	// 408 = 0x198
    NSURL *_urlBeingShared;	// 416 = 0x1a0
    NSMutableArray *_activeSecurityContexts;	// 424 = 0x1a8
    SDShareSheetProxyLoaderManager *_proxyLoaderManager;	// 432 = 0x1b0
    CDUnknownBlockType _disabledNodesUpdatedHandler;	// 440 = 0x1b8
}

- (void).cxx_destruct;	// IMP=0x002000000014a743
@property(nonatomic) _Bool invalidateCalled; // @synthesize invalidateCalled=_invalidateCalled;
@property(copy, nonatomic) CDUnknownBlockType disabledNodesUpdatedHandler; // @synthesize disabledNodesUpdatedHandler=_disabledNodesUpdatedHandler;
@property(retain, nonatomic) SDShareSheetProxyLoaderManager *proxyLoaderManager; // @synthesize proxyLoaderManager=_proxyLoaderManager;
@property(retain, nonatomic) NSMutableArray *activeSecurityContexts; // @synthesize activeSecurityContexts=_activeSecurityContexts;
@property(retain, nonatomic) NSURL *urlBeingShared; // @synthesize urlBeingShared=_urlBeingShared;
@property(nonatomic) long long nearbyCountBadge; // @synthesize nearbyCountBadge=_nearbyCountBadge;
@property(retain, nonatomic) NSNumber *nearbyCountSlotID; // @synthesize nearbyCountSlotID=_nearbyCountSlotID;
@property(retain, nonatomic) NSMutableDictionary *actionActivityToID; // @synthesize actionActivityToID=_actionActivityToID;
@property(retain, nonatomic) NSMutableDictionary *shareActivityToID; // @synthesize shareActivityToID=_shareActivityToID;
@property(retain, nonatomic) NSMutableDictionary *realNameToNodeID; // @synthesize realNameToNodeID=_realNameToNodeID;
@property(retain, nonatomic) NSArray *hostActionActivityProxies; // @synthesize hostActionActivityProxies=_hostActionActivityProxies;
@property(retain, nonatomic) NSArray *hostShareActivityProxies; // @synthesize hostShareActivityProxies=_hostShareActivityProxies;
@property(retain, nonatomic) NSArray *peopleNodes; // @synthesize peopleNodes=_peopleNodes;
@property(retain, nonatomic) NSArray *airDropNodes; // @synthesize airDropNodes=_airDropNodes;
@property(retain, nonatomic) NSArray *favoriteActions; // @synthesize favoriteActions=_favoriteActions;
@property(retain, nonatomic) NSArray *favoriteApps; // @synthesize favoriteApps=_favoriteApps;
@property(retain, nonatomic) NSArray *visibleActionActivities; // @synthesize visibleActionActivities=_visibleActionActivities;
@property(retain, nonatomic) NSArray *actionActivitiesInUserOrder; // @synthesize actionActivitiesInUserOrder=_actionActivitiesInUserOrder;
@property(retain, nonatomic) NSDictionary *actionActivitiesByUUID; // @synthesize actionActivitiesByUUID=_actionActivitiesByUUID;
@property(retain, nonatomic) NSArray *actionActivities; // @synthesize actionActivities=_actionActivities;
@property(retain, nonatomic) NSArray *visibleShareActivities; // @synthesize visibleShareActivities=_visibleShareActivities;
@property(retain, nonatomic) NSArray *shareActivitiesInUserOrder; // @synthesize shareActivitiesInUserOrder=_shareActivitiesInUserOrder;
@property(retain, nonatomic) NSDictionary *shareActivitiesByUUID; // @synthesize shareActivitiesByUUID=_shareActivitiesByUUID;
@property(retain, nonatomic) NSArray *shareActivities; // @synthesize shareActivities=_shareActivities;
@property(retain, nonatomic) NSArray *suggestedPeople; // @synthesize suggestedPeople=_suggestedPeople;
@property(retain, nonatomic) NSArray *airDropPeople; // @synthesize airDropPeople=_airDropPeople;
@property(retain, nonatomic) NSDictionary *bundleIDToActivities; // @synthesize bundleIDToActivities=_bundleIDToActivities;
@property(retain, nonatomic) NSArray *orderedPresentableActivities; // @synthesize orderedPresentableActivities=_orderedPresentableActivities;
- (void)setHostConfiguration:(id)arg1;	// IMP=0x001000000014a412
- (id)hostConfiguration;	// IMP=0x001000000014a405
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) _UIActivityHelper *activityHelper; // @synthesize activityHelper=_activityHelper;
@property(retain, nonatomic) SDXPCHelperConnection *xpcHelperCnx; // @synthesize xpcHelperCnx=_xpcHelperCnx;
@property(retain, nonatomic) SDSuggestionBrowser *suggestionBrowser; // @synthesize suggestionBrowser=_suggestionBrowser;
@property(retain, nonatomic) SDPeopleBrowser *peopleBrowser; // @synthesize peopleBrowser=_peopleBrowser;
@property(retain, nonatomic) SFAirDropNode *selectedRecipient; // @synthesize selectedRecipient=_selectedRecipient;
@property(retain, nonatomic) NSMutableDictionary *transferNodes; // @synthesize transferNodes=_transferNodes;
@property(retain, nonatomic) SFAirDropNode *selectedNode; // @synthesize selectedNode=_selectedNode;
@property(retain, nonatomic) SDScreenTimeMonitor *screenTimeMonitor; // @synthesize screenTimeMonitor=_screenTimeMonitor;
@property(retain, nonatomic) _UIUserDefaultsActivity *shareUserDefaultsActivity; // @synthesize shareUserDefaultsActivity=_shareUserDefaultsActivity;
@property(retain, nonatomic) SDAirDropActivity *activeAirDropActivity; // @synthesize activeAirDropActivity=_activeAirDropActivity;
@property(retain, nonatomic) UIImpactFeedbackGenerator *impactHaptic; // @synthesize impactHaptic=_impactHaptic;
@property(retain, nonatomic) UISelectionFeedbackGenerator *selectionHaptic; // @synthesize selectionHaptic=_selectionHaptic;
@property(retain, nonatomic) UINotificationFeedbackGenerator *notificationHaptic; // @synthesize notificationHaptic=_notificationHaptic;
@property(nonatomic) long long lastTransferEvent; // @synthesize lastTransferEvent=_lastTransferEvent;
@property(retain, nonatomic) NSMutableDictionary *sharedItemsRequestIDToPreviewPhoto; // @synthesize sharedItemsRequestIDToPreviewPhoto=_sharedItemsRequestIDToPreviewPhoto;
@property(retain, nonatomic) NSMutableDictionary *sharedItemsMap; // @synthesize sharedItemsMap=_sharedItemsMap;
@property(nonatomic) int sharedItemsCount; // @synthesize sharedItemsCount=_sharedItemsCount;
@property(nonatomic) long long generatedPreviews; // @synthesize generatedPreviews=_generatedPreviews;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(nonatomic) _Bool transferActive; // @synthesize transferActive=_transferActive;
@property(nonatomic) _Bool firedImpactHaptic; // @synthesize firedImpactHaptic=_firedImpactHaptic;
@property(nonatomic) _Bool itemsReady; // @synthesize itemsReady=_itemsReady;
@property(nonatomic) _Bool itemsRequested; // @synthesize itemsRequested=_itemsRequested;
@property(retain, nonatomic) NSMutableOrderedSet *cachedSharedItems; // @synthesize cachedSharedItems=_cachedSharedItems;
@property(nonatomic) long long attachmentCount; // @synthesize attachmentCount=_attachmentCount;
@property(nonatomic) long long sharedItemsRequestID; // @synthesize sharedItemsRequestID=_sharedItemsRequestID;
@property(retain, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) _Bool partialSlotsRendering; // @synthesize partialSlotsRendering=_partialSlotsRendering;
@property(nonatomic) _Bool isSharePlayAvailable; // @synthesize isSharePlayAvailable=_isSharePlayAvailable;
@property(nonatomic) _Bool shouldSuggestFamilyMembers; // @synthesize shouldSuggestFamilyMembers=_shouldSuggestFamilyMembers;
@property(nonatomic) _Bool sharingExpanded; // @synthesize sharingExpanded=_sharingExpanded;
@property(nonatomic) _Bool sentInitialConfiguration; // @synthesize sentInitialConfiguration=_sentInitialConfiguration;
@property(nonatomic) _Bool engagedWithSheet; // @synthesize engagedWithSheet=_engagedWithSheet;
@property(nonatomic) _Bool airDropAllowed; // @synthesize airDropAllowed=_airDropAllowed;
@property(nonatomic) __weak id <SDShareSheetSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)proxyLoaderManagerDidFinishLoadingProxySection:(id)arg1 cancelled:(_Bool)arg2;	// IMP=0x0010000000149f96
- (void)proxyLoaderManager:(id)arg1 didLoadProxiesWithChangeDetails:(id)arg2;	// IMP=0x0010000000149f3a
- (void)_updateProxiesWithChangeDetails:(id)arg1;	// IMP=0x0010000000149d52
- (void)_removeFailedIndexes:(id)arg1 forProxySection:(id)arg2;	// IMP=0x0010000000149afd
- (void)reportCurrentInvocationForDuration:(long long)arg1;	// IMP=0x001000000014973b
- (void)_loadProxySectionWithType:(long long)arg1;	// IMP=0x0010000000149670
- (id)_proxySectionForType:(long long)arg1;	// IMP=0x0010000000149534
- (id)minimumVisibleShareActivities;	// IMP=0x0010000000148f64
- (id)secondaryLabelColor;	// IMP=0x0010000000148dd8
- (id)labelColor;	// IMP=0x0010000000148c82
- (void)generateSpecialPreviewPhotoForRequestID:(long long)arg1;	// IMP=0x00100000001486e2
- (_Bool)addAttributedString:(id)arg1 withAttachmentName:(id)arg2 description:(id)arg3 previewImage:(id)arg4 itemIndex:(int)arg5;	// IMP=0x00100000001483cd
- (_Bool)addString:(id)arg1 withAttachmentName:(id)arg2 description:(id)arg3 previewImage:(id)arg4 itemIndex:(int)arg5;	// IMP=0x001000000014815d
- (_Bool)createURLPayloadForData:(id)arg1 ofType:(id)arg2 withAttachmentName:(id)arg3 description:(id)arg4 previewImage:(id)arg5 itemIndex:(int)arg6 completion:(CDUnknownBlockType)arg7;	// IMP=0x0010000000147b5c
- (_Bool)addData:(id)arg1 ofType:(id)arg2 withAttachmentName:(id)arg3 description:(id)arg4 previewImage:(id)arg5 itemIndex:(int)arg6;	// IMP=0x0010000000147888
- (_Bool)addImage:(id)arg1 withAttachmentName:(id)arg2 description:(id)arg3 previewImage:(id)arg4 itemIndex:(int)arg5;	// IMP=0x001000000014738f
- (_Bool)addURL:(id)arg1 withAttachmentName:(id)arg2 description:(id)arg3 previewImage:(id)arg4 itemIndex:(int)arg5;	// IMP=0x0010000000146dc6
- (_Bool)isValidPayload:(id)arg1 toPerson:(id)arg2 invalidMessage:(id *)arg3;	// IMP=0x00100000001461ae
- (void)resetAfterAirDropTransfer;	// IMP=0x00100000001460ce
- (void)startSendForNode:(id)arg1 WithItems:(id)arg2 itemData:(id)arg3;	// IMP=0x0010000000145464
@property(readonly, nonatomic) NSString *hostAppProcessName;
@property(readonly, nonatomic) NSString *hostAppBundleID;
- (id)_orderedActivitiesIncludingUserDisabledExtensionsForAuditToken:(CDStruct_4c969caf)arg1;	// IMP=0x0010000000145394
- (void)_loadPresentableActivitiesForAuditToken:(CDStruct_4c969caf)arg1;	// IMP=0x001000000014528a
- (id)_orderedAvailableActivitiesForAuditToken:(CDStruct_4c969caf)arg1 WithMatchingContextCustomizationBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000144fcb
- (void)checkPolicyForAirDropPeople;	// IMP=0x0010000000144b52
- (void)checkPolicyForSuggestedPeople;	// IMP=0x00100000001443c8
- (void)updateRestrictedActivityTypes:(id)arg1;	// IMP=0x0010000000143ccb
- (void)nodesPotentiallyUpdated;	// IMP=0x0010000000143c19
- (void)systemRestrictionsChanged:(id)arg1;	// IMP=0x0010000000143483
- (void)removeStatusMonitorObservers;	// IMP=0x0010000000143430
- (void)addStatusMonitorObservers;	// IMP=0x001000000014339f
- (id)airdropNodeForIdentifier:(id)arg1;	// IMP=0x0010000000143139
- (void)_deactivateSecurityContext:(id)arg1;	// IMP=0x0010000000143075
- (void)_activateSecurityContext:(id)arg1;	// IMP=0x0010000000142fb1
@property(readonly, copy) NSString *description;
- (void)invalidate;	// IMP=0x0010000000142cf4
- (void)activate;	// IMP=0x0010000000142b39
- (id)initWithSessionID:(id)arg1 xpcConnection:(id)arg2;	// IMP=0x00100000001424c6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

