//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData, NSString;

@interface SDUnlockSetupCreateRecord : PBCodable
{
    unsigned int _errorCode;	// 8 = 0x8
    NSString *_pairedDeviceID;	// 16 = 0x10
    unsigned int _sessionID;	// 24 = 0x18
    NSData *_token;	// 32 = 0x20
    unsigned int _version;	// 40 = 0x28
    CDStruct_e173124d _has;	// 44 = 0x2c
}

- (void).cxx_destruct;	// IMP=0x00200000000dc191
@property(retain, nonatomic) NSString *pairedDeviceID; // @synthesize pairedDeviceID=_pairedDeviceID;
@property(retain, nonatomic) NSData *token; // @synthesize token=_token;
@property(nonatomic) unsigned int errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) unsigned int sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000dc05c
- (unsigned long long)hash;	// IMP=0x00100000000dbfa5
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000dbe5f
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000dbd66
- (void)copyTo:(id)arg1;	// IMP=0x00100000000dbcab
- (void)writeTo:(id)arg1;	// IMP=0x00100000000dbbe1
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000dbbd4
- (id)dictionaryRepresentation;	// IMP=0x00100000000db6da
- (id)description;	// IMP=0x00100000000db62b
@property(readonly, nonatomic) _Bool hasPairedDeviceID;
@property(readonly, nonatomic) _Bool hasToken;
@property(nonatomic) _Bool hasErrorCode;
@property(nonatomic) _Bool hasSessionID;
@property(nonatomic) _Bool hasVersion;

@end

