//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, SDUnlockIDSController, SDUnlockSecurityManager, SFPairedUnlockEvent;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SDUnlockSessionManager : NSObject
{
    long long _setupAuthSession;	// 8 = 0x8
    long long _unlockAuthSession;	// 16 = 0x10
    long long _stashBagSession;	// 24 = 0x18
    SDUnlockIDSController *_idsController;	// 32 = 0x20
    SDUnlockSecurityManager *_securityManager;	// 40 = 0x28
    SFPairedUnlockEvent *_metrics;	// 48 = 0x30
    NSObject<OS_dispatch_source> *_unlockTimer;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000001f0fbe
@property(retain) NSObject<OS_dispatch_source> *unlockTimer; // @synthesize unlockTimer=_unlockTimer;
@property(retain) SFPairedUnlockEvent *metrics; // @synthesize metrics=_metrics;
@property(retain) SDUnlockSecurityManager *securityManager; // @synthesize securityManager=_securityManager;
@property __weak SDUnlockIDSController *idsController; // @synthesize idsController=_idsController;
@property long long stashBagSession; // @synthesize stashBagSession=_stashBagSession;
@property long long unlockAuthSession; // @synthesize unlockAuthSession=_unlockAuthSession;
@property long long setupAuthSession; // @synthesize setupAuthSession=_setupAuthSession;
- (void)logMetrics;	// IMP=0x00100000001f0e12
- (void)logProtoBufReceived:(id)arg1;	// IMP=0x00100000001f0ced
- (void)logProtoBufSend:(id)arg1;	// IMP=0x00100000001f0bc8
- (unsigned int)generateSessionID;	// IMP=0x00100000001f0bb9
- (_Bool)activeDevicesMatch;	// IMP=0x00100000001f0bb1
- (id)activeDeviceDescription;	// IMP=0x00100000001f0ba9
- (id)activeDeviceName;	// IMP=0x00100000001f0ba1
- (id)pairingStorePath;	// IMP=0x00100000001f0b99
- (id)pairingID;	// IMP=0x00100000001f0b91
- (_Bool)deviceIsPaired;	// IMP=0x00100000001f0b89
- (unsigned short)pairingCompatibilityState;	// IMP=0x00100000001f0b7e
- (_Bool)inConfigureState;	// IMP=0x00100000001f0b76
- (_Bool)shouldAbort;	// IMP=0x00100000001f0b6e
- (void)abortDevicePairingWithReason:(id)arg1;	// IMP=0x00100000001f0b68
- (void)sendDisableMessage;	// IMP=0x00100000001f0a66
- (void)sendResetMessage:(unsigned int)arg1 reason:(unsigned short)arg2;	// IMP=0x00100000001f092b
- (void)invalidateUnlockTimer;	// IMP=0x00100000001f08a5
- (void)restartUnlockTimer:(unsigned long long)arg1;	// IMP=0x00100000001f06d4
- (void)resetStashState;	// IMP=0x00100000001f0665
- (void)resetState;	// IMP=0x00100000001f05e9
- (void)resetAndClearState;	// IMP=0x00100000001f05d7
- (void)resetSetupState;	// IMP=0x00100000001f0568
- (void)resetAll;	// IMP=0x00100000001f052d
- (void)disableUnlockWithDevice:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000001f0443
- (_Bool)unlockEnabled;	// IMP=0x00100000001f03ff
- (void)disableUnlockPairingForSecManager:(id)arg1;	// IMP=0x00100000001f0336
- (void)disableUnlockPairing;	// IMP=0x00100000001f02b0
- (void)enableUnlockPairing;	// IMP=0x00100000001f0233
- (void)deviceDidEnterConfigState:(id)arg1;	// IMP=0x00100000001f0182
- (void)pairingDidBegin:(id)arg1;	// IMP=0x00100000001f00d1
- (void)pairingStatusChanged:(id)arg1;	// IMP=0x00100000001f00cb
- (void)updateExitPrevention;	// IMP=0x00100000001f00c5
- (void)handleDevicesDidFailToPair;	// IMP=0x00100000001f004f
- (void)devicesDidFailToPair:(id)arg1;	// IMP=0x00100000001f003d
- (id)generateDebugInfo;	// IMP=0x00100000001efb4a
- (void)removeObservers;	// IMP=0x00100000001efaf7
- (void)addObservers;	// IMP=0x00100000001efa38
- (void)debugInfoRequested:(id)arg1;	// IMP=0x00100000001efa32
- (void)preventExitForLocaleIfNeeded;	// IMP=0x00100000001efa2c
- (void)updateSecurityManager;	// IMP=0x00100000001ef7f4
- (void)updateSecurityManagerIfNeeded;	// IMP=0x00100000001ef7ab
- (void)dealloc;	// IMP=0x00100000001ef76d
- (id)init;	// IMP=0x00100000001ef680

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

