//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSSet, NSString;

__attribute__((visibility("hidden")))
@interface SDWorkgroupBrowser : NSObject
{
    int _clientCount;	// 8 = 0x8
    MISSING_TYPE *_browser;	// 16 = 0x10
}

+ (id)sharedBrowser;	// IMP=0x00200000000de321
- (void).cxx_destruct;	// IMP=0x00200000000de742
- (void)stop;	// IMP=0x00100000000de6f3
- (void)start;	// IMP=0x00100000000de600
- (void)bonjourNodesDidChange:(id)arg1;	// IMP=0x00100000000de5b0
@property(readonly, copy) NSSet *workgroups;
@property(readonly, copy) NSArray *nodes;
- (id)init;	// IMP=0x00100000000de376

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

