//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TIUserModelDataStore;
@protocol CHPKPersistentAnalyticsSessionDelegate, OS_dispatch_queue;

@interface CHPKPersistentAnalyticsController : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    TIUserModelDataStore *_dataStore;	// 16 = 0x10
    id <CHPKPersistentAnalyticsSessionDelegate> _sessionDelegate;	// 24 = 0x18
}

+ (void)registerScheduledEventsActivity;	// IMP=0x00200000000030b0
+ (id)userModelDataStorePath;	// IMP=0x0010000000002ef0
+ (id)sharedInstance;	// IMP=0x0010000000002d30
- (void).cxx_destruct;	// IMP=0x00200000000057d0
@property(nonatomic) __weak id <CHPKPersistentAnalyticsSessionDelegate> sessionDelegate; // @synthesize sessionDelegate=_sessionDelegate;
- (oneway void)test_dispatchDailyEvent;	// IMP=0x0010000000005770
- (oneway void)didEndPKCanvasSession:(id)arg1 withInputMode:(id)arg2;	// IMP=0x00100000000054d0
- (oneway void)didEndInputSessionUsingScribbleWithInputMode:(id)arg1;	// IMP=0x0010000000005390
- (oneway void)didEndInputSessionWithInputMode:(id)arg1;	// IMP=0x0010000000005270
- (oneway void)didBeginInputSession;	// IMP=0x0010000000005230
- (_Bool)inputModeIdentifierIsValid:(id)arg1;	// IMP=0x00100000000051d0
- (void)dispatchLifecycleEventForFeature:(id)arg1 denominatorKey:(id)arg2 inputModeIdentifier:(id)arg3 values:(id)arg4 sinceDate:(id)arg5;	// IMP=0x0010000000004dd0
- (void)dispatchLifecycleEvents;	// IMP=0x0010000000004850
- (void)dispatchDailyUsageEvents;	// IMP=0x0010000000004140
- (void)dispatchSettingsEvents;	// IMP=0x00100000000040a0
- (void)dispatchScheduledEventsWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000003f60
- (id)newContextForAnalyticsWithUserModel:(id)arg1 language:(id)arg2;	// IMP=0x0010000000003e40
- (_Bool)cachedSettingsBoolForKey:(id)arg1 userModel:(id)arg2;	// IMP=0x0010000000003d80
- (id)durableCounterKeys;	// IMP=0x0010000000003d70
- (id)settingsDictionary;	// IMP=0x0010000000003800
- (id)init;	// IMP=0x0010000000002e00

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

