//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CHCachedRecognizerManager, CHInputContextLexiconManager, CHRecognizerInferenceCache, NSString, NSXPCListener;
@protocol OS_dispatch_queue, OS_dispatch_workloop;

@interface CHRemoteRecognitionServer : NSObject
{
    CHCachedRecognizerManager *_recognizerManager;	// 8 = 0x8
    CHInputContextLexiconManager *_lexiconManager;	// 16 = 0x10
    NSXPCListener *_listener;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_serverQueue;	// 32 = 0x20
    _Bool _isListening;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_highPriorityRecognitionProcessingQueue;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_lowPriorityRecognitionProcessingQueue;	// 56 = 0x38
    NSObject<OS_dispatch_workloop> *_recognitionProcessingWorkloop;	// 64 = 0x40
    CHRecognizerInferenceCache *_recognizerInferenceCache;	// 72 = 0x48
    long long _openRequestCount;	// 80 = 0x50
}

+ (id)_unableToProcessRequestErrorWithBundleIdentifier:(id)arg1;	// IMP=0x002000000000a4b0
+ (id)_maxStrokeLimitErrorWithInputDrawingStrokeCount:(long long)arg1;	// IMP=0x001000000000a1d0
+ (id)_invalidInputErrorWithDescription:(id)arg1 failureReason:(id)arg2 recoverySuggestion:(id)arg3 errorCode:(long long)arg4;	// IMP=0x001000000000a070
+ (_Bool)_hasEntitlement:(id)arg1 connection:(id)arg2;	// IMP=0x00100000000078c0
+ (id)sharedRemoteRecognitionServer;	// IMP=0x0010000000006cd0
- (void).cxx_destruct;	// IMP=0x002000000000a770
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0010000000009f10
- (void)resumeConnectionIfIdle;	// IMP=0x0010000000009ed0
- (void)transcriptionPathsForTokenizedResult:(id)arg1 recognitionRequest:(id)arg2 withReply:(CDUnknownBlockType)arg3;	// IMP=0x00100000000094f0
- (void)handleRecognitionRequest:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000007c20
- (_Bool)_shouldFulfillRecognitionRequestForConnection:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000079f0
- (id)_queueForRequest:(id)arg1;	// IMP=0x0010000000007810
- (_Bool)_isValidRemoteRecognitionRequest:(id)arg1 connection:(id)arg2 error:(id *)arg3;	// IMP=0x00100000000071b0
- (id)_bundleIdentifierForConnection:(id)arg1;	// IMP=0x0010000000007090
- (void)dealloc;	// IMP=0x0010000000006f80
- (id)init;	// IMP=0x0010000000006da0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

