//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ClassKit/CLSActivity.h>

@class NSObject, NSString;
@protocol PDDatabaseValue;

@interface CLSActivity (PDSyncableItem)
+ (id)recordType;	// IMP=0x002000000006b62b
+ (long long)migrationOrder;	// IMP=0x00100000000a6094
+ (_Bool)migrateFromVersion:(unsigned long long)arg1 finalVersion:(out unsigned long long *)arg2 inDatabase:(id)arg3;	// IMP=0x00100000000a5ee1
+ (id)entityName;	// IMP=0x00100000000a5cb5
+ (int)entityType;	// IMP=0x001000000017c8e1
+ (int)syncType;	// IMP=0x001000000017c8d6
@property(readonly, nonatomic) NSString *parentReferenceName;
@property(readonly, nonatomic) long long syncableItemType;
- (long long)syncOrder;	// IMP=0x001000000006b7fb
- (void)populate:(id)arg1;	// IMP=0x001000000006b717
- (id)initWithCKRecord:(id)arg1;	// IMP=0x001000000006b638
- (void)bindTo:(id)arg1;	// IMP=0x00100000000a5dd8
- (id)initWithDatabaseRow:(id)arg1;	// IMP=0x00100000000a5cc2
- (id)generateReportFromDataInDatabase:(id)arg1 processedObjectCallback:(CDUnknownBlockType)arg2;	// IMP=0x0010000000121a08

// Remaining properties
@property(readonly, nonatomic) unsigned long long changeHash;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic, getter=isDeleteTracked) _Bool deleteTracked;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<PDDatabaseValue> *identityValue;
@property(readonly) Class superclass;
@end

