//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSComparisonPredicate.h>

@interface NSComparisonPredicate (PDSQLWhereClause)
- (_Bool)getRightKeyPath:(id *)arg1 orRightContstantValue:(id *)arg2 error:(id *)arg3;	// IMP=0x001000000009526d
- (id)leftKeyPath:(id *)arg1;	// IMP=0x00100000000951c9
- (_Bool)pd_containsKeyPath:(id)arg1;	// IMP=0x0010000000098e46
- (id)pd_filterSubpredicatesForKeyPath:(id)arg1;	// IMP=0x0010000000098c18
- (void)_populateKeypathValueMap:(id)arg1;	// IMP=0x0010000000098b1d
@end

