//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class PDDPEndpointConfig;

@interface PDDEndpointInfo : NSObject
{
    double _lastSuccessTime;	// 8 = 0x8
    double _lastFailureTime;	// 16 = 0x10
    long long _failureCounter;	// 24 = 0x18
    PDDPEndpointConfig *_config;	// 32 = 0x20
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000007b9fb
- (void).cxx_destruct;	// IMP=0x002000000007ba5e
@property(retain, nonatomic) PDDPEndpointConfig *config; // @synthesize config=_config;
@property(nonatomic) long long failureCounter; // @synthesize failureCounter=_failureCounter;
@property(nonatomic) double lastFailureTime; // @synthesize lastFailureTime=_lastFailureTime;
@property(nonatomic) double lastSuccessTime; // @synthesize lastSuccessTime=_lastSuccessTime;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000007b954
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000007b87c
- (_Bool)requiresMescal;	// IMP=0x001000000007b74c
- (_Bool)needsCooldown;	// IMP=0x001000000007b5a4
- (_Bool)isExpired;	// IMP=0x001000000007b474
- (id)dictionaryRepresentation;	// IMP=0x001000000007b071
- (id)identifier;	// IMP=0x001000000007b021
- (id)initWithDictionary:(id)arg1;	// IMP=0x001000000007aac8
- (id)initWithEndpointConfig:(id)arg1;	// IMP=0x001000000007aa4e

@end

