//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBRequest.h>

@class NSMutableArray;

@interface PDDPEESyncRequest : PBRequest
{
    NSMutableArray *_requestZones;	// 8 = 0x8
}

+ (Class)requestZonesType;	// IMP=0x00200000000d3e18
- (void).cxx_destruct;	// IMP=0x00200000000d48bf
@property(retain, nonatomic) NSMutableArray *requestZones; // @synthesize requestZones=_requestZones;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000d4765
- (unsigned long long)hash;	// IMP=0x00100000000d4748
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000d46ae
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000d44eb
- (void)copyTo:(id)arg1;	// IMP=0x00100000000d4424
- (Class)responseClass;	// IMP=0x00100000000d4413
- (unsigned int)requestTypeCode;	// IMP=0x00100000000d4408
- (void)writeTo:(id)arg1;	// IMP=0x00100000000d42d8
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000d410b
- (id)dictionaryRepresentation;	// IMP=0x00100000000d3ed8
- (id)description;	// IMP=0x00100000000d3e29
- (id)requestZonesAtIndex:(unsigned long long)arg1;	// IMP=0x00100000000d3dfb
- (unsigned long long)requestZonesCount;	// IMP=0x00100000000d3dde
- (void)addRequestZones:(id)arg1;	// IMP=0x00100000000d3d74
- (void)clearRequestZones;	// IMP=0x00100000000d3d57

@end

