//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface PDDPStateChangesIOS134MACOS10154PersonalDomainState : PBCodable
{
    unsigned long long _flags;	// 8 = 0x8
    int _domain;	// 16 = 0x10
    int _state;	// 20 = 0x14
    CDStruct_214543d2 _has;	// 24 = 0x18
}

@property(nonatomic) unsigned long long flags; // @synthesize flags=_flags;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000018a1ab
- (unsigned long long)hash;	// IMP=0x001000000018a14b
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000018a078
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000189fe0
- (void)copyTo:(id)arg1;	// IMP=0x0010000000189f6b
- (void)writeTo:(id)arg1;	// IMP=0x0010000000189eda
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000189ecd
- (id)dictionaryRepresentation;	// IMP=0x00100000001899d2
- (id)description;	// IMP=0x0010000000189923
@property(nonatomic) _Bool hasFlags;
- (int)StringAsState:(id)arg1;	// IMP=0x001000000018984b
- (id)stateAsString:(int)arg1;	// IMP=0x00100000001897e5
@property(nonatomic) _Bool hasState;
@property(nonatomic) int state; // @synthesize state=_state;
- (int)StringAsDomain:(id)arg1;	// IMP=0x001000000018968c
- (id)domainAsString:(int)arg1;	// IMP=0x00100000001895f4
@property(nonatomic) _Bool hasDomain;
@property(nonatomic) int domain; // @synthesize domain=_domain;

@end

