//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol OS_xpc_object;

@interface CSActivationXPCClient : NSObject
{
    NSObject<OS_xpc_object> *_xpcConnection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000007126
@property(retain, nonatomic) NSObject<OS_xpc_object> *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
- (id)_decodeError:(id)arg1;	// IMP=0x0010000000007041
- (void)_sendMessage:(id)arg1 connection:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006e3e
- (void)notifyActivationEvent:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000006c7d
- (void)_handleListenerError:(id)arg1;	// IMP=0x0010000000006b68
- (void)_handleListenerEvent:(id)arg1;	// IMP=0x0010000000006ad1
- (void)dealloc;	// IMP=0x0010000000006a0b
- (void)connect;	// IMP=0x0010000000006902
- (id)init;	// IMP=0x00100000000068a3

@end

