//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AVVoiceTriggerClient, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface CSBuiltinSpeakerStateMonitor
{
    _Bool _isSpeakerMuted;	// 8 = 0x8
    AVVoiceTriggerClient *_alwaysOnProcessorController;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    unsigned long long _builtInSpeakerState;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x00200000000ca61a
- (void).cxx_destruct;	// IMP=0x00200000000cb8b8
@property(nonatomic) _Bool isSpeakerMuted; // @synthesize isSpeakerMuted=_isSpeakerMuted;
@property(nonatomic) unsigned long long builtInSpeakerState; // @synthesize builtInSpeakerState=_builtInSpeakerState;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) AVVoiceTriggerClient *alwaysOnProcessorController; // @synthesize alwaysOnProcessorController=_alwaysOnProcessorController;
- (void)CSAudioServerCrashMonitorDidReceiveServerRestart:(id)arg1;	// IMP=0x00100000000cb7c6
- (void)_notifyObserver:(id)arg1 isSpeakerMuted:(_Bool)arg2;	// IMP=0x00100000000cb7b4
- (void)_didReceiveSpeakerMuteStateChangeNotification:(_Bool)arg1;	// IMP=0x00100000000cb738
- (void)_notifyObserver:(id)arg1 withBuiltinSpeakerState:(unsigned long long)arg2;	// IMP=0x00100000000cb6cf
- (void)_didReceiveBuiltinSpeakerStateChangeNotification:(unsigned long long)arg1;	// IMP=0x00100000000cb651
- (void)_stopMonitoring;	// IMP=0x00100000000cb4c1
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x00100000000cae8e
- (_Bool)isBuiltinSpeakerMuted;	// IMP=0x00100000000cadda
- (unsigned long long)currentBuiltinSpeakerState;	// IMP=0x00100000000cad22
- (void)_fetchSpeakerStateActiveInfo;	// IMP=0x00100000000caa36
- (void)_fetchSpeakerStateMutedInfo;	// IMP=0x00100000000ca744
- (id)init;	// IMP=0x00100000000ca66f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
// Error: Property attributes should begin with the type ('T') attribute, property name: superclass
// Property attributes: (null)


@end

