//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CSCoreSpeechServices : NSObject
{
}

+ (long long)getFirstPassRunningMode;	// IMP=0x0040000000024698
+ (void)requestUpdatedSATAudio;	// IMP=0x00100000000243f4
+ (void)voiceTriggerJarvisLanguageList:(id)arg1 jarvisSelectedLanguage:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002415a
+ (void)voiceTriggerRTModelForVersion:(unsigned long long)arg1 minorVersion:(unsigned long long)arg2 downloadedModels:(id)arg3 preinstalledModels:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000023c37
+ (void)voiceTriggerRTModelForVersion:(unsigned long long)arg1 minorVersion:(unsigned long long)arg2 accessoryRTModelType:(long long)arg3 endpointId:(id)arg4 downloadedModels:(id)arg5 preinstalledModels:(id)arg6 completion:(CDUnknownBlockType)arg7;	// IMP=0x0010000000023675
+ (void)voiceTriggerRTModelForVersion:(unsigned long long)arg1 minorVersion:(unsigned long long)arg2 accessoryRTModelType:(long long)arg3 downloadedModels:(id)arg4 preinstalledModels:(id)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x001000000002364a
+ (void)getCurrentVoiceTriggerLocaleWithEndpointId:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000023319
+ (void)fetchRemoteVoiceTriggerAssetForLanguageCode:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002312b
+ (void)installedVoiceTriggerAssetForLanguageCode:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000022f3d
+ (id)getCoreSpeechXPCConnection;	// IMP=0x0010000000022ece
+ (id)getCoreSpeechServiceConnection;	// IMP=0x0010000000022e5d

@end

