//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CSDefaultAudioRouteChangeMonitorMac
{
}

+ (id)sharedInstance;	// IMP=0x000000000004ecd4
- (unsigned int)defaultOutputAudioDeviceID;	// IMP=0x004000000004ecec
- (_Bool)isDefaultOutputBultInSpeaker;	// IMP=0x001000000004ece4
- (_Bool)isDefaultInputBuiltInMic;	// IMP=0x001000000004ecdc

@end

