//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDSDaemonCapabilities : NSObject
{
    int _supportedServicesToken;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x002000000033f6d0
@property(nonatomic) int supportedServicesToken; // @synthesize supportedServicesToken=_supportedServicesToken;
- (void)_deferredUpdateCapabilities;	// IMP=0x001000000033ff90
- (void)carrierBundleInformationDidChange;	// IMP=0x001000000033fed0
- (void)_setupTokens;	// IMP=0x001000000033fe90
- (void)_listenForMGChanges;	// IMP=0x001000000033fe80
- (void)_updateCapabilities;	// IMP=0x001000000033f890
- (void)dealloc;	// IMP=0x001000000033f850
- (id)init;	// IMP=0x001000000033f790

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

