//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSDAccountController, IDSDServiceController, IDSRegistrationController, IDSRestrictions, MISSING_TYPE, NSDate;

@interface IDSSIMResponder : NSObject
{
    IDSDAccountController *_accountController;	// 8 = 0x8
    IDSDServiceController *_serviceController;	// 16 = 0x10
    IDSRegistrationController *_registrationController;	// 24 = 0x18
    IDSRestrictions *_restrictions;	// 32 = 0x20
    NSDate *_registrationStateChangedDate;	// 40 = 0x28
    long long _registrationStateChangedCounter;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000012080
@property(nonatomic) long long registrationStateChangedCounter; // @synthesize registrationStateChangedCounter=_registrationStateChangedCounter;
@property(retain, nonatomic) NSDate *registrationStateChangedDate; // @synthesize registrationStateChangedDate=_registrationStateChangedDate;
@property(retain, nonatomic) IDSRestrictions *restrictions; // @synthesize restrictions=_restrictions;
@property(retain, nonatomic) IDSRegistrationController *registrationController; // @synthesize registrationController=_registrationController;
@property(retain, nonatomic) IDSDServiceController *serviceController; // @synthesize serviceController=_serviceController;
@property(retain, nonatomic) IDSDAccountController *accountController; // @synthesize accountController=_accountController;
- (void)handleSIMRemoved;	// IMP=0x00100000000117f0
- (void)handleRegistrationStateChanged:(_Bool)arg1;	// IMP=0x00100000000109c0
- (MISSING_TYPE *)handleSIMInserted;	// IMP=0x001000000000ffd0
- (void)_checkTechChange;	// IMP=0x001000000000f530
- (void)_enumeratePrimaryAccountsOfType:(int)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x001000000000f250
- (id)initWithAccountController:(id)arg1 serviceController:(id)arg2 restrictions:(id)arg3 registrationController:(id)arg4;	// IMP=0x001000000000f0f0

@end

