//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AccountAdditionalPushTopics
{
}

+ (id)_propertySettersForAccountAdditionalPushTopics;	// IMP=0x00400000000b96ad
+ (id)_predicateForAccountPID:(long long)arg1;	// IMP=0x00100000000b963a
+ (void)updateAccountAdditionalPushTopics:(id)arg1 forAccountPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000000b92c0
+ (void)deleteAccountAdditionalPushTopicsForAccountPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000000b9227
+ (id)insertAccountAdditionalPushTopics:(id)arg1 forAccountPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000000b91ac
+ (id)accountAdditionalPushTopicsForAccountPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000000b8e01
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x00100000000b8dd2
+ (id)databaseTable;	// IMP=0x00100000000b8dc5
- (id)accountAdditionalPushTopics;	// IMP=0x00400000000b98c4
- (void)updateWithAccountAdditionalPushTopics:(id)arg1;	// IMP=0x00100000000b93b0
- (id)initWithAccountAdditionalPushTopics:(id)arg1 forAccountPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000000b8eab

@end

