//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface PDObjectSettingsManager : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    NSMutableDictionary *_objectSettings;	// 16 = 0x10
    _Bool _archiveScheduled;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000033ef10
- (id)init;	// IMP=0x001000000033e753

@end

