//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class PKCurrencyAmount;

@interface PDPeerPaymentTransactionReceivedUserNotification
{
    PKCurrencyAmount *_updatedBalance;	// 104 = 0x68
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000001ce322
- (void).cxx_destruct;	// IMP=0x00200000001ce5f4
@property(readonly, nonatomic) PKCurrencyAmount *updatedBalance; // @synthesize updatedBalance=_updatedBalance;
- (id)notificationContentWithDataSource:(id)arg1;	// IMP=0x00100000001ce4d2
- (unsigned long long)notificationType;	// IMP=0x00100000001ce4c7
- (_Bool)isValid;	// IMP=0x00100000001ce442
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000001ce3c5
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000001ce32a
- (id)initWithPassUniqueIdentifier:(id)arg1 accountBalance:(id)arg2;	// IMP=0x00100000001ce253

@end

