//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface PDVehicleConnectionSession : NSObject
{
    NSObject<OS_dispatch_queue> *_vehicleConnectionSessionQueue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_replyQueue;	// 16 = 0x10
    NSString *_sessionIdentifier;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000360b61
@property(readonly, copy, nonatomic) NSString *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
- (void)_sessionDidFailToConnect;	// IMP=0x0010000000360b51
- (void)endSession;	// IMP=0x0010000000360b4b
- (void)startSessionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000360b35
- (_Bool)sendData:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000360b2d
- (void)dealloc;	// IMP=0x0010000000360afe
- (id)initForSecureElementPass:(id)arg1 delegate:(id)arg2;	// IMP=0x0010000000360acf

@end

