//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PeerPaymentPreferences
{
}

+ (id)_propertySettersForPeerPaymentPreferences;	// IMP=0x004000000027f1e4
+ (id)_predicateForPeerPaymentAccountPID:(long long)arg1;	// IMP=0x001000000027ed91
+ (id)anyInDatabase:(id)arg1 forPeerPaymentAccount:(id)arg2;	// IMP=0x001000000027ecf8
+ (id)insertPeerPaymentPeferences:(id)arg1 forPeerPaymentAccount:(id)arg2 inDatabase:(id)arg3;	// IMP=0x001000000027e8db
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x001000000027e8ac
+ (id);	// IMP=0x001000000027e89f
- (id)_dictionaryForPeerPaymentPreferences:(id)arg1 forPeerPaymentAccountPID:(long long)arg2;	// IMP=0x004000000027f107
- (id)peerPaymentPreferences;	// IMP=0x001000000027eede
- (_Bool)deleteFromDatabase;	// IMP=0x001000000027ee04
- (void)updatePeerPaymentPreferences:(id)arg1 forPeerPaymentAccount:(id)arg2;	// IMP=0x001000000027ead6
- (id)initWithPeerPaymentPreferences:(id)arg1 forPeerPaymentAccount:(id)arg2 inDatabase:(id)arg3;	// IMP=0x001000000027e969

@end

