//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class CalendarModel, NSString, UITableView;

@interface IdentitySwitcherViewController : UIViewController
{
    CalendarModel *_model;	// 8 = 0x8
    UITableView *_tableView;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000d721c
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00100000000d6fcf
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00100000000d6b88
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00100000000d6ab6
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00100000000d6a65
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00100000000d6a5a
- (struct CGSize)preferredContentSize;	// IMP=0x00100000000d69f2
- (void)loadView;	// IMP=0x00100000000d68a3
- (id)initWithModel:(id)arg1;	// IMP=0x00100000000d6835

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

