//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class EKCalendarEventInvitationNotification, EKEvent, EKEventOccurrenceInfo, NSDictionary;

@interface InboxRepliedSectionItem : NSObject
{
    EKEventOccurrenceInfo *_occurrenceInfo;	// 8 = 0x8
    EKEvent *_event;	// 16 = 0x10
    EKCalendarEventInvitationNotification *_notification;	// 24 = 0x18
    NSDictionary *_cellFrameDictionary;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000002ddf5
@property(retain, nonatomic) NSDictionary *cellFrameDictionary; // @synthesize cellFrameDictionary=_cellFrameDictionary;
@property(retain, nonatomic) EKCalendarEventInvitationNotification *notification; // @synthesize notification=_notification;
@property(retain, nonatomic) EKEvent *event; // @synthesize event=_event;
@property(retain, nonatomic) EKEventOccurrenceInfo *occurrenceInfo; // @synthesize occurrenceInfo=_occurrenceInfo;
- (id)description;	// IMP=0x001000000002dc5e
- (id)initWithOccurrenceInfo:(id)arg1;	// IMP=0x001000000002dbf3

@end

