//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APSEnvironment, MISSING_TYPE, NSMutableArray, NSNumber, NSTimer;
@protocol APSOutgoingMessageQueueDelegate;

@interface APSOutgoingMessageQueue : NSObject
{
    id <APSOutgoingMessageQueueDelegate> _delegate;	// 8 = 0x8
    APSEnvironment *_environment;	// 16 = 0x10
    NSMutableArray *_queue;	// 24 = 0x18
    NSTimer *_timer;	// 32 = 0x20
    double _criticalMessageTimeout;	// 40 = 0x28
    NSTimer *_criticalMessageKeepAliveTimer;	// 48 = 0x30
    double _criticalMessageKeepAliveTimerDuration;	// 56 = 0x38
    unsigned long long _criticalMessageFlushCount;	// 64 = 0x40
    unsigned long long _numberOfCriticalMessageFlushesBeforeDisconnecting;	// 72 = 0x48
    unsigned long long _criticalMessageFlushSize;	// 80 = 0x50
    double _forcedShortTimeoutDuration;	// 88 = 0x58
    double _lastReceivedAckOrReconnect;	// 96 = 0x60
    void *_powerAssertion;	// 104 = 0x68
    NSNumber *_lastReversePushRTTMilliseconds[2];	// 112 = 0x70
    _Bool _shouldReportLastReversePushRTT[2];	// 128 = 0x80
    _Bool _powerOptimizationsForExpensiveNetworkingDisabled;	// 130 = 0x82
}

- (void).cxx_destruct;	// IMP=0x0020000000060d07
@property(nonatomic) _Bool powerOptimizationsForExpensiveNetworkingDisabled; // @synthesize powerOptimizationsForExpensiveNetworkingDisabled=_powerOptimizationsForExpensiveNetworkingDisabled;
- (unsigned long long)count;	// IMP=0x0010000000060cd9
- (void)setForcedShortTimeoutInterval:(id)arg1;	// IMP=0x0010000000060bc5
- (void)setCriticalMessageTimeout:(id)arg1;	// IMP=0x0010000000060ab1
- (void)setCriticalMessageKeepAliveTimerDuration:(id)arg1;	// IMP=0x001000000006099d
- (void)setNumberOfCriticalMessageFlushesBeforeDisconnecting:(id)arg1;	// IMP=0x00100000000608af
@property(readonly, nonatomic) _Bool hasEagerMessages;
@property(readonly, nonatomic) _Bool hasPendingMessages;
- (void)_criticalMessageKeepAliveTimerFired;	// IMP=0x00100000000605c2
- (void)_clearCriticalMessageKeepAliveTimer;	// IMP=0x00100000000604ff
- (void)_clearCriticalMessageKeepAliveTimerIfAppropriate;	// IMP=0x00100000000603a4
- (void)_startCriticalMessageFlushTimerSendingFlush;	// IMP=0x001000000006026f
- (_Bool)_outgoingMessageIsLateCriticalMessage:(id)arg1;	// IMP=0x0010000000060045
- (void)_timerFired:(id)arg1;	// IMP=0x001000000005f7d7
- (void)_recalculateDisableFastDormancy;	// IMP=0x001000000005f697
- (void)_recalculatePowerAssertion;	// IMP=0x001000000005f479
- (void)_recalculateTimer;	// IMP=0x001000000005ecd6
- (void)_queueChanged;	// IMP=0x001000000005ec63
- (void)_deliverResult:(id)arg1 forMessage:(id)arg2;	// IMP=0x001000000005eb37
- (void)handleConnectionClosedOnInterface:(long long)arg1;	// IMP=0x001000000005e7b9
- (void)handleConnectionClosed;	// IMP=0x001000000005e7a2
- (void)handleConnectionOpenedOnInterface:(long long)arg1;	// IMP=0x001000000005e3af
- (void)handleAcknowledgmentForOutgoingMessageWithResult:(id)arg1 ackTimestamp:(unsigned long long)arg2 relevantInterfaceMonitor:(id)arg3 dualChannelState:(unsigned int)arg4 onInterface:(long long)arg5;	// IMP=0x001000000005d86f
- (void)handleAcknowledgmentForOutgoingMessageWithResult:(id)arg1 ackTimestamp:(unsigned long long)arg2;	// IMP=0x001000000005d846
- (MISSING_TYPE *)lastReversePushRTTMillisecondsOnInterface: /* Error: Ran out of types for this method. */;	// IMP=0x001000000005d6c8
- (void)setShouldReportLastReversePushRTT:(_Bool)arg1 onInterface:(long long)arg2;	// IMP=0x001000000005d51e
- (_Bool)shouldReportLastReversePushRTTOnInterface:(long long)arg1;	// IMP=0x001000000005d45a
- (void)handleErrorSendingOutgoingMessage:(id)arg1 error:(id)arg2;	// IMP=0x001000000005d27a
- (void)handleSentOutgoingMessage:(id)arg1 onInterface:(long long)arg2;	// IMP=0x001000000005d0ad
- (void)handleSentOutgoingMessage:(id)arg1;	// IMP=0x001000000005d096
- (void)transferOwnershipOfPendingMessagesToHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000005ced7
- (void)cancelOutgoingMessageWithID:(unsigned long long)arg1;	// IMP=0x001000000005cbda
- (id)outgoingMessagesToSendForTokenState:(id)arg1;	// IMP=0x001000000005c96a
- (void)enqueueOutgoingMessage:(id)arg1 forOriginator:(id)arg2;	// IMP=0x001000000005c858
- (void)dealloc;	// IMP=0x001000000005c7b8
- (id)initWithDelegate:(id)arg1 environment:(id)arg2;	// IMP=0x001000000005c6ec

@end

