//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SATimerResume.h>

@interface SATimerResume (ADTimerTransformer)
- (id)_ad_timerResponseForResponse:(id)arg1;	// IMP=0x0010000000080883
- (id)_ad_timerRequestRepresentation;	// IMP=0x0010000000080817
@end

