//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewCell.h>

@class MISSING_TYPE;

@interface _TtC9Reminders29TTRIListDetailColorsTableCell : UITableViewCell
{
    MISSING_TYPE *gridView;	// 8 = 0x8
    MISSING_TYPE *delegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x004000000001d8f0
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;	// IMP=0x001000000001d8a0
- (id)initWithReuseIdentifier:(id)arg1;	// IMP=0x001000000001d830
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000001d7c0
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x001000000001d770

@end

