//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9Reminders31TTRRemindersListViewModelSource : _TtCs12_SwiftObject
{
    MISSING_TYPE *sortingCapability;	// 16 = 0x10
    MISSING_TYPE *delegate;	// 24 = 0x18
    MISSING_TYPE *tree;	// 40 = 0x28
    MISSING_TYPE *listMessaging;	// 48 = 0x30
    MISSING_TYPE *dataModelSource;	// 56 = 0x38
    MISSING_TYPE *interactor;	// 72 = 0x48
    MISSING_TYPE *remReminderByObjectID;	// 88 = 0x58
    MISSING_TYPE *cachedListInfo;	// 96 = 0x60
    MISSING_TYPE *cachedEmptyListMessaging;	// 259 = 0x103
    MISSING_TYPE *recurrentRemindersViewModelOverrides;	// 264 = 0x108
    MISSING_TYPE *recurrentReminderReplacements;	// 272 = 0x110
    MISSING_TYPE *nextDataModelUpdateOptions;	// 280 = 0x118
}

@end

