//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC9Reminders23TTRIShowFlaggedAssembly : NSObject
{
}

- (id)init;	// IMP=0x00400000001797c0

@end

