//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Intents/INObjectResolutionResult.h>

@interface ConfigurationListResolutionResult : INObjectResolutionResult
{
}

+ (id)confirmationRequiredWithObjectToConfirm:(id)arg1;	// IMP=0x00200000003e3bf0
+ (id)disambiguationWithObjectsToDisambiguate:(id)arg1;	// IMP=0x00100000003e3b70
+ (id)successWithResolvedObject:(id)arg1;	// IMP=0x00100000003e3af0
+ (id)confirmationRequiredWithConfigurationListToConfirm:(id)arg1;	// IMP=0x00100000003e3a60
+ (id)disambiguationWithConfigurationListsToDisambiguate:(id)arg1;	// IMP=0x00100000003e39a0
+ (id)successWithResolvedConfigurationList:(id)arg1;	// IMP=0x00100000003e3830
- (id)initWithJSONDictionary:(id)arg1 forIntent:(id)arg2;	// IMP=0x00400000003e3d60

@end

