//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APCacheStore, APCacheableBaseObject, NSString;

@interface APCacheStoreOperationSet : NSObject
{
    APCacheStore *_cacheStore;	// 8 = 0x8
    NSString *_key;	// 16 = 0x10
    APCacheableBaseObject *_object;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000d16aa
@property(readonly, nonatomic) APCacheableBaseObject *object; // @synthesize object=_object;
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, nonatomic) __weak APCacheStore *cacheStore; // @synthesize cacheStore=_cacheStore;
- (_Bool)_setObject:(id)arg1 objectSerializedData:(id)arg2 forKey:(id)arg3;	// IMP=0x00100000000d13d0
- (void)rollBack;	// IMP=0x00100000000d13ca
- (void)commit;	// IMP=0x00100000000d13c4
- (_Bool)execute;	// IMP=0x00100000000d12e9
- (id)initWithCacheStore:(id)arg1 key:(id)arg2 object:(id)arg3;	// IMP=0x00100000000d1242

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

