//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class MISSING_TYPE, NSMutableArray, NSString;

@interface APPBPolicyData : PBCodable
{
    NSString *_identifier;	// 8 = 0x8
    MISSING_TYPE *_policyValues;	// 16 = 0x10
}

+ (Class)policyValuesType;	// IMP=0x0020000000030e4d
- (void).cxx_destruct;	// IMP=0x0020000000031a4f
@property(retain, nonatomic) NSMutableArray *policyValues; // @synthesize policyValues=_policyValues;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000003188d
- (unsigned long long)hash;	// IMP=0x0010000000031840
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000031778
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000003159f
- (void)copyTo:(id)arg1;	// IMP=0x00100000000314b5
- (void)writeTo:(id)arg1;	// IMP=0x0010000000031369
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000003135c
- (id)dictionaryRepresentation;	// IMP=0x0010000000030f0d
- (id)description;	// IMP=0x0010000000030e5e
- (id)policyValuesAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000030e30
- (unsigned long long)policyValuesCount;	// IMP=0x0010000000030e13
- (void)addPolicyValues:(id)arg1;	// IMP=0x0010000000030da9
- (void)clearPolicyValues;	// IMP=0x0010000000030d8c
@property(readonly, nonatomic) _Bool hasIdentifier;

@end

