//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface APPBLogAggregateMetricsResponse : PBCodable
{
}

+ (id)options;	// IMP=0x0020000000037eaf
- (void)mergeFrom:(id)arg1;	// IMP=0x004000000003816b
- (unsigned long long)hash;	// IMP=0x0010000000038163
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000003811e
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000380e5
- (void)copyTo:(id)arg1;	// IMP=0x00100000000380df
- (void)writeTo:(id)arg1;	// IMP=0x00100000000380d9
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000380cc
- (id);	// IMP=0x0010000000037fae
- (id)description;	// IMP=0x0010000000037eff

@end

