//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol APSettingsStorableProtocol;

@interface APSettings : NSObject
{
    id <APSettingsStorableProtocol> _storage;	// 8 = 0x8
}

+ (id)settings;	// IMP=0x00200000000f6c93
+ (id)mapTable;	// IMP=0x00100000000f6c27
+ (id)storageWithDefaultValues:(id)arg1;	// IMP=0x00100000000f6bda
+ (id)defaultValues;	// IMP=0x00100000000f6bd2
- (void).cxx_destruct;	// IMP=0x00200000000f75ac
@property(readonly, nonatomic) id <APSettingsStorableProtocol> storage; // @synthesize storage=_storage;
- (id)methodSignatureForSelector:(SEL)arg1;	// IMP=0x00100000000f743d
- (void)forwardInvocation:(id)arg1;	// IMP=0x00100000000f72fa
- (id)_propertyNameFromSetSelectorString:(id)arg1;	// IMP=0x00100000000f71f5
- (id)_gatherSubclassProperties;	// IMP=0x00100000000f711b
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;	// IMP=0x00100000000f7030
- (id)valueForUndefinedKey:(id)arg1;	// IMP=0x00100000000f6f54
- (id)_namespacedKey:(id)arg1;	// IMP=0x00100000000f6ec4
- (id)init;	// IMP=0x00100000000f6e21
- (void)synchronize;	// IMP=0x00100000000f6de4

@end

