//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class CSDMessagingAVConferenceInviteData, NSString;

@interface CSDMessagingCallMessage : PBCodable
{
    CSDMessagingAVConferenceInviteData *_inviteData;	// 8 = 0x8
    unsigned int _protoProtocolVersion;	// 16 = 0x10
    NSString *_protoUpgradeSessionUUID;	// 24 = 0x18
    int _type;	// 32 = 0x20
    _Bool _oBSOLETEProtoMomentsAvailable;	// 36 = 0x24
    _Bool _protoMomentsV2Available;	// 37 = 0x25
    _Bool _protoSenderMuteUplink;	// 38 = 0x26
    _Bool _protoShouldSuppressInCallUI;	// 39 = 0x27
    _Bool _protoWantsVideo;	// 40 = 0x28
    struct {
        unsigned int protoProtocolVersion:1;
        unsigned int type:1;
        unsigned int oBSOLETEProtoMomentsAvailable:1;
        unsigned int protoMomentsV2Available:1;
        unsigned int protoSenderMuteUplink:1;
        unsigned int protoShouldSuppressInCallUI:1;
        unsigned int protoWantsVideo:1;
    } _has;	// 44 = 0x2c
}

- (void).cxx_destruct;	// IMP=0x00100000001150ef
@property(retain, nonatomic) NSString *protoUpgradeSessionUUID; // @synthesize protoUpgradeSessionUUID=_protoUpgradeSessionUUID;
@property(nonatomic) _Bool protoMomentsV2Available; // @synthesize protoMomentsV2Available=_protoMomentsV2Available;
@property(nonatomic) _Bool protoShouldSuppressInCallUI; // @synthesize protoShouldSuppressInCallUI=_protoShouldSuppressInCallUI;
@property(nonatomic) _Bool protoSenderMuteUplink; // @synthesize protoSenderMuteUplink=_protoSenderMuteUplink;
@property(nonatomic) _Bool oBSOLETEProtoMomentsAvailable; // @synthesize oBSOLETEProtoMomentsAvailable=_oBSOLETEProtoMomentsAvailable;
@property(retain, nonatomic) CSDMessagingAVConferenceInviteData *inviteData; // @synthesize inviteData=_inviteData;
@property(nonatomic) _Bool protoWantsVideo; // @synthesize protoWantsVideo=_protoWantsVideo;
@property(nonatomic) unsigned int protoProtocolVersion; // @synthesize protoProtocolVersion=_protoProtocolVersion;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000114efe
- (unsigned long long)hash;	// IMP=0x0010000000114dca
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000114b9a
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000114a34
- (void)copyTo:(id)arg1;	// IMP=0x0010000000114904
- (void)writeTo:(id)arg1;	// IMP=0x00100000001147b9
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000001147ac
- (id)dictionaryRepresentation;	// IMP=0x0010000000113e35
- (id)description;	// IMP=0x0010000000113d86
@property(readonly, nonatomic) _Bool hasProtoUpgradeSessionUUID;
@property(nonatomic) _Bool hasProtoMomentsV2Available;
@property(nonatomic) _Bool hasProtoShouldSuppressInCallUI;
@property(nonatomic) _Bool hasProtoSenderMuteUplink;
@property(nonatomic) _Bool hasOBSOLETEProtoMomentsAvailable;
@property(readonly, nonatomic) _Bool hasInviteData;
@property(nonatomic) _Bool hasProtoWantsVideo;
@property(nonatomic) _Bool hasProtoProtocolVersion;
- (int)StringAsType:(id)arg1;	// IMP=0x0010000000113b0e
- (id)typeAsString:(int)arg1;	// IMP=0x0010000000113aa8
@property(nonatomic) _Bool hasType;
@property(nonatomic) int type; // @synthesize type=_type;
- (void)addProtocolVersion;	// IMP=0x001000000001382f
@property(nonatomic) _Bool shouldSuppressInCallUI;
@property(nonatomic, getter=isMomentsAvailable) _Bool momentsAvailable;
@property(nonatomic) _Bool senderMuteUplink;
- (void)setWantsVideo:(_Bool)arg1;	// IMP=0x00100000000136f9
- (_Bool)wantsVideo;	// IMP=0x00100000000136e7
@property(nonatomic) int protocolVersion;

@end

