//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class CSDMessagingHandle, NSString, TUConversationMember;

@interface CSDMessagingConversationMember : PBCodable
{
    unsigned long long _lightweightPrimaryParticipantID;	// 8 = 0x8
    CSDMessagingHandle *_handle;	// 16 = 0x10
    CSDMessagingHandle *_lightweightPrimary;	// 24 = 0x18
    NSString *_nickname;	// 32 = 0x20
    int _validationSource;	// 40 = 0x28
    unsigned int _version;	// 44 = 0x2c
    struct {
        unsigned int lightweightPrimaryParticipantID:1;
        unsigned int validationSource:1;
        unsigned int version:1;
    } _has;	// 48 = 0x30
}

+ (id)memberWithTUConversationMember:(id)arg1;	// IMP=0x0010000000063766
- (void).cxx_destruct;	// IMP=0x00100000000d2c4f
@property(nonatomic) unsigned long long lightweightPrimaryParticipantID; // @synthesize lightweightPrimaryParticipantID=_lightweightPrimaryParticipantID;
@property(retain, nonatomic) CSDMessagingHandle *lightweightPrimary; // @synthesize lightweightPrimary=_lightweightPrimary;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) CSDMessagingHandle *handle; // @synthesize handle=_handle;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000d2aad
- (unsigned long long)hash;	// IMP=0x00100000000d29c7
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000d284b
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000d2728
- (void)copyTo:(id)arg1;	// IMP=0x00100000000d2644
- (void)writeTo:(id)arg1;	// IMP=0x00100000000d255d
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000d2550
- (id)dictionaryRepresentation;	// IMP=0x00100000000d1f3a
- (id)description;	// IMP=0x00100000000d1e8b
- (int)StringAsValidationSource:(id)arg1;	// IMP=0x00100000000d1e29
- (id)validationSourceAsString:(int)arg1;	// IMP=0x00100000000d1dd4
@property(nonatomic) _Bool hasValidationSource;
@property(nonatomic) int validationSource; // @synthesize validationSource=_validationSource;
@property(nonatomic) _Bool hasLightweightPrimaryParticipantID;
@property(readonly, nonatomic) _Bool hasLightweightPrimary;
@property(readonly, nonatomic) _Bool hasNickname;
@property(readonly, nonatomic) _Bool hasHandle;
@property(nonatomic) _Bool hasVersion;
@property(readonly, nonatomic) TUConversationMember *tuConversationMember;

@end

