//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface ASCTextOfferMetadata
{
    NSString *_title;	// 8 = 0x8
    NSString *_subtitle;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x004000000000e13e
- (void).cxx_destruct;	// IMP=0x002000000000e694
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (_Bool)isText;	// IMP=0x001000000000e66a
- (id)description;	// IMP=0x001000000000e58e
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000e3fb
- (unsigned long long)hash;	// IMP=0x001000000000e349
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000000e275
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000000e146
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2;	// IMP=0x001000000000e077

@end

