//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MapKit/_MKQuickRouteManager.h>

@class CarQuickRouteRefreshOperation;

@interface _MKQuickRouteManager (CarQuickRouteRefreshOperation)
- (void)_Car_cancelUpdateETA;	// IMP=0x002000000015dff3
- (void)_Car_queueUpdateETA;	// IMP=0x001000000015dedc
@property(readonly) _Bool _Car_shouldDelayOperation;
@property(readonly) double _Car_etaAge;
@property(readonly) _Bool _Car_isPrimaryRefreshQueue;
@property(retain, nonatomic) CarQuickRouteRefreshOperation *_Car_refreshOperation;
@property(nonatomic) _Bool _Car_isVisible;
@end

