//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UILabel.h>

__attribute__((visibility("hidden")))
@interface _RAPAnnotationTitleLabel : UILabel
{
}

- (void)drawTextInRect:(struct CGRect)arg1;	// IMP=0x0040000000749114

@end

