//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE, NSLayoutConstraint, NSMutableArray, NSString, UIButton, UIImage, UIImageView, UILabel, UIScrollView, UISwitch, UIView;

__attribute__((visibility("hidden")))
@interface _RAPPrivacyInformationController : UIViewController
{
    long long _appearance;	// 8 = 0x8
    long long _shortcutType;	// 16 = 0x10
    UILabel *_titleLabel;	// 24 = 0x18
    UILabel *_subtitleLabel;	// 32 = 0x20
    UISwitch *_followUpSwitch;	// 40 = 0x28
    UIScrollView *_scrollView;	// 48 = 0x30
    UIView *_containerView;	// 56 = 0x38
    UIView *_bottomView;	// 64 = 0x40
    UIButton *_skipButton;	// 72 = 0x48
    UIImageView *_iconView;	// 80 = 0x50
    UIImage *_portraitIcon;	// 88 = 0x58
    UIImage *_landscapeIcon;	// 96 = 0x60
    _Bool _shouldShowPrivacy;	// 104 = 0x68
    _Bool _hasValidEmail;	// 105 = 0x69
    _Bool _isUserEnteredEmailAddress;	// 106 = 0x6a
    NSString *_emailAddress;	// 112 = 0x70
    _Bool _accessibilityEnabled;	// 120 = 0x78
    NSMutableArray *_portraitSpecificConstraints;	// 128 = 0x80
    NSMutableArray *_landscapeSpecificConstraints;	// 136 = 0x88
    NSLayoutConstraint *_portraitAccessibilityConstraint;	// 144 = 0x90
    CDUnknownBlockType _completion;	// 152 = 0x98
}

- (void).cxx_destruct;	// IMP=0x0020000000a5e895
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void)_skipButtonTapped;	// IMP=0x0010000000a5e809
- (void)_sendButtonTapped;	// IMP=0x0010000000a5e759
- (void)acceptPrivacyAgreement;	// IMP=0x0010000000a5e610
- (id)_getEvent;	// IMP=0x0010000000a5e5ac
- (void)cancelPrivacyAgreement;	// IMP=0x0010000000a5e3f6
- (id)_createSkipButton;	// IMP=0x0010000000a5e1c5
- (id)_createSendButton;	// IMP=0x0010000000a5df48
- (id)_setupBottomViewInView:(id)arg1 commonConstraints:(id)arg2 portraitSpecificConstraints:(id)arg3 landscapeSpecificConstraints:(id)arg4;	// IMP=0x0010000000a5d779
- (id)_createDetailsViewInView:(id)arg1 constraints:(id)arg2;	// IMP=0x0010000000a5d1e4
- (id)_createSwitchViewInView:(id)arg1 constraints:(id)arg2;	// IMP=0x0010000000a5cb4a
- (id)setupContactViewsInContainer:(id)arg1 constraints:(id)arg2 portraitSpecificConstraints:(id)arg3 landscapeSpecificConstraints:(id)arg4;	// IMP=0x0010000000a5c7f0
- (id)setupTitleViewsInContainer:(id)arg1 constraints:(id)arg2 portraitSpecificConstraints:(id)arg3 landscapeSpecificConstraints:(id)arg4;	// IMP=0x0010000000a5c0d4
- (id)_setupContainerViewInView:(id)arg1 constraints:(id)arg2 portraitSpecificConstraints:(id)arg3 landscapeSpecificConstraints:(id)arg4;	// IMP=0x0010000000a5b4a2
- (void)setupViews;	// IMP=0x0010000000a5b33a
- (MISSING_TYPE *)updateCenterYConstraintIfNeeded;	// IMP=0x0010000000a5b2c1
- (void)setSkipButtonFont;	// IMP=0x0010000000a5b226
- (id)sendButtonFont;	// IMP=0x0010000000a5b205
- (id)followUpDetailFont;	// IMP=0x0010000000a5b1e4
- (id)followUpLabelFont;	// IMP=0x0010000000a5b1c3
- (void)setSubtitleFont;	// IMP=0x0010000000a5b14c
- (id)titleFont;	// IMP=0x0010000000a5b12b
- (void)contentSizeDidChange:(id)arg1;	// IMP=0x0010000000a5b0b1
- (void)viewDidLayoutSubviews;	// IMP=0x0010000000a5af05
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0010000000a5addc
- (id)defaultPOIStyleAttributes;	// IMP=0x0010000000a5ad8a
- (void)viewDidLoad;	// IMP=0x0010000000a5a80b
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000a5a7f7
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000a5a7e3
- (id)initWithShortcutType:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000a5a7a4
- (id)initWithCompletion:(CDUnknownBlockType)arg1 emailAddress:(id)arg2 isUserEnteredEmailAddress:(_Bool)arg3;	// IMP=0x0010000000a5a72b
- (id)initWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000a5a67b

@end

