//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC4Maps20PlaceSummaryMetadata : NSObject
{
    MISSING_TYPE *useCase;	// 8 = 0x8
    MISSING_TYPE *templatePairs;	// 16 = 0x10
    MISSING_TYPE *serverOverrides;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00400000000b1d20
- (id)init;	// IMP=0x00100000000b1cc0

@end

