//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MapsSync/_TtC8MapsSync18MapsSyncCollection.h>

@interface _TtC8MapsSync18MapsSyncCollection (CollectionHandler)
- (void)setPlaces:(id)arg1;	// IMP=0x0010000000684e26
- (void)setImage:(id)arg1;	// IMP=0x0010000000684d7c
- (void)setTitle:(id)arg1;	// IMP=0x0010000000684cd2
- (void)setImageURL:(id)arg1;	// IMP=0x0010000000684c28
- (id)imageURL;	// IMP=0x0010000000684c16
- (_Bool)isFavoritesCollection;	// IMP=0x0010000000684b94
@end

