//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface AnimationSlideParameters : NSObject
{
    double _deltaHeight;	// 8 = 0x8
    CDStruct_62478167 _parametersIn;	// 16 = 0x10
    CDStruct_62478167 _parametersOut;	// 48 = 0x30
}

+ (id)presentSmallerParameters;	// IMP=0x00400000007096f7
+ (id)defaultParameters;	// IMP=0x001000000070965e
@property(nonatomic) double deltaHeight; // @synthesize deltaHeight=_deltaHeight;
@property(nonatomic) CDStruct_d2b197d1 parametersOut; // @synthesize parametersOut=_parametersOut;
@property(nonatomic) CDStruct_d2b197d1 parametersIn; // @synthesize parametersIn=_parametersIn;

@end

