//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, NSString;

__attribute__((visibility("hidden")))
@interface BatteryMonitorController : NSObject
{
    NSHashTable *_tokens;	// 8 = 0x8
    _Bool _isMonitoring;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00200000008f13b9
- (void).cxx_destruct;	// IMP=0x00200000008f1656
@property(nonatomic) _Bool isMonitoring; // @synthesize isMonitoring=_isMonitoring;
- (void)batteryMonitorConcreteTokenWillInvalidate:(id)arg1;	// IMP=0x00100000008f161b
- (void)_updateBatteryMonitoring;	// IMP=0x00100000008f14a2
- (id)beginMonitoringBattery;	// IMP=0x00100000008f140e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

