//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSObject, NSTimer, PersonalizedItemSource;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface CalendarItemSource
{
    NSArray *_allItems;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_updateQueue;	// 16 = 0x10
    NSTimer *_updateTimer;	// 24 = 0x18
    PersonalizedItemSource *_exclusionSource;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_lockQueue;	// 40 = 0x28
}

+ (id)subtitleFromEventName:(id)arg1 eventDate:(id)arg2;	// IMP=0x00200000008222cd
+ (void)initialize;	// IMP=0x00100000008208bb
+ (id)sharedDateFormatter;	// IMP=0x0010000000820816
- (void).cxx_destruct;	// IMP=0x0020000000822506
- (void)personalizedItemSourceDidChangeItems:(id)arg1;	// IMP=0x00100000008224f4
- (_Bool)shouldIncludeEvent:(id)arg1;	// IMP=0x00100000008221f0
- (void)_updateCalendarItems;	// IMP=0x0010000000821386
- (void)loadCalendarItems;	// IMP=0x001000000082131e
- (id)predicateForIncompleteReminders;	// IMP=0x00100000008212c0
- (id)predicateForRemindersDueAfter:(id)arg1;	// IMP=0x00100000008211b9
- (id)predicateForDateRangeSince:(id)arg1;	// IMP=0x00100000008210b2
- (id)allItems;	// IMP=0x0010000000820f8c
- (id)_nextUpdateDate;	// IMP=0x0010000000820f02
- (void)_scheduleUpdateTimer;	// IMP=0x0010000000820e30
- (void)_clearUpdateTimer;	// IMP=0x0010000000820df8
- (void)dateHasChanged:(id)arg1;	// IMP=0x0010000000820dbd
- (void)excludeItemsFromSource:(id)arg1;	// IMP=0x0010000000820d72
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x0010000000820d60
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x0010000000820d32
- (void)eventStoreDidChange:(id)arg1;	// IMP=0x0010000000820d20
- (void)userDefaultsDidChange:(id)arg1;	// IMP=0x0010000000820bf9
- (id)init;	// IMP=0x0010000000820954

@end

