//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOAdvisoryCard, GEORouteIncident, NSString;

__attribute__((visibility("hidden")))
@interface CarAdvisoryListItem : NSObject
{
    GEORouteIncident *_incident;	// 8 = 0x8
    GEOAdvisoryCard *_advisoryCard;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00100000008d07ac
- (id)subtitle;	// IMP=0x00100000008d06cf
- (id)title;	// IMP=0x00100000008d05f2
- (id)initWithGEOAdvisoryCard:(id)arg1;	// IMP=0x00100000008d0587
- (id)initWithGEORouteIncident:(id)arg1;	// IMP=0x00100000008d051c
- (void)updateModel:(id)arg1;	// IMP=0x0010000000360215

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

