//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class GuidanceETA, MISSING_TYPE, NSArray, NSString;

@protocol CarPlaceCardCardViewControllerDataSource <NSObject>
- (NSArray *)automaticSharingContacts;
- (GuidanceETA *)etaForCurrentRoute;

@optional
- (MISSING_TYPE *)currentRoute;
- (NSString *)routeMainDescriptionText;
@end

