//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOObserverHashTable, MISSING_TYPE, NSArray, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface CollectionsDataProvider : NSObject
{
    MISSING_TYPE *_observers;	// 8 = 0x8
    NSDictionary *_collectionsByIdentifier;	// 16 = 0x10
    NSDictionary *_contentsByIdentifier;	// 24 = 0x18
    NSDictionary *_observedCollectionsByIdentifier;	// 32 = 0x20
    _Bool _active;	// 40 = 0x28
    _Bool _hasInitialData;	// 41 = 0x29
    _Bool _observeInfo;	// 42 = 0x2a
    _Bool _observeContents;	// 43 = 0x2b
    long long _context;	// 48 = 0x30
    NSArray *_collections;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000007555f8
@property(readonly, nonatomic) NSArray *collections; // @synthesize collections=_collections;
@property(readonly, nonatomic) _Bool observeContents; // @synthesize observeContents=_observeContents;
@property(readonly, nonatomic) _Bool observeInfo; // @synthesize observeInfo=_observeInfo;
@property(readonly, nonatomic) long long context; // @synthesize context=_context;
@property(readonly, nonatomic) _Bool hasInitialData; // @synthesize hasInitialData=_hasInitialData;
@property(nonatomic) _Bool active; // @synthesize active=_active;
- (void)_stopObservingCollection:(id)arg1;	// IMP=0x0010000000755491
- (void)_startObservingCollection:(id)arg1;	// IMP=0x0010000000755362
- (void)_updateObservedCollectionsWithCollections:(id)arg1;	// IMP=0x0010000000754f15
- (void)collectionHandlerContentUpdated:(id)arg1;	// IMP=0x0010000000754de6
- (void)collectionHandlerInfoUpdated:(id)arg1;	// IMP=0x0010000000754cb7
- (void)collectionManager:(id)arg1 contentDidChange:(id)arg2;	// IMP=0x0010000000754b8d
@property(readonly, nonatomic) GEOObserverHashTable *observers;
- (void)_updateContentsOfCollection:(id)arg1 notifyObservers:(_Bool)arg2;	// IMP=0x00100000007547fb
- (void)_updateInfoOfCollection:(id)arg1 notifyObservers:(_Bool)arg2;	// IMP=0x0010000000754683
- (void)_updateCollectionsAndNotifyObservers:(_Bool)arg1;	// IMP=0x0010000000753e17
- (id)initWithContext:(long long)arg1 observeInfo:(_Bool)arg2 observeContents:(_Bool)arg3;	// IMP=0x0010000000753cd7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

