//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSString, NSURL, UIImage;

__attribute__((visibility("hidden")))
@interface CuratedCollectionMediaIntegrationViewModel : NSObject
{
    NSString *_identifier;	// 8 = 0x8
    NSString *_title;	// 16 = 0x10
    NSString *_subtitle;	// 24 = 0x18
    NSString *_actionText;	// 32 = 0x20
    NSURL *_url;	// 40 = 0x28
    NSURL *_artworkURL;	// 48 = 0x30
    UIImage *_systemFirstPartyIcon;	// 56 = 0x38
    NSString *_localizedSystemFirstPartyName;	// 64 = 0x40
    UIImage *_realmIcon;	// 72 = 0x48
    NSArray *_childViewModels;	// 80 = 0x50
    NSString *_targetAppIdentifier;	// 88 = 0x58
    long long _mediaType;	// 96 = 0x60
    double _logoToTitlePadding;	// 104 = 0x68
}

+ (double)logoToTitlePaddingWithMediaType:(long long)arg1;	// IMP=0x0020000000215078
+ (MISSING_TYPE *)bundleIdentifierForResult: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000214fc8
+ (id)localizedSystemFirstPartyNameForResult:(id)arg1;	// IMP=0x0010000000214dba
+ (id)systemFirstPartyIconForResult:(id)arg1;	// IMP=0x0010000000214d20
+ (id)realmIconForResult:(id)arg1;	// IMP=0x0010000000214c50
+ (id)actionTextForResult:(id)arg1 hasChildLinks:(_Bool)arg2;	// IMP=0x00100000002149a0
+ (id)subtitleForResult:(id)arg1;	// IMP=0x0010000000214537
+ (id)formatterForDurationString;	// IMP=0x001000000021447d
- (void).cxx_destruct;	// IMP=0x0020000000215119
@property(readonly, nonatomic) double logoToTitlePadding; // @synthesize logoToTitlePadding=_logoToTitlePadding;
@property(readonly, nonatomic) long long mediaType; // @synthesize mediaType=_mediaType;
@property(readonly, nonatomic) NSString *targetAppIdentifier; // @synthesize targetAppIdentifier=_targetAppIdentifier;
@property(readonly, nonatomic) NSArray *childViewModels; // @synthesize childViewModels=_childViewModels;
@property(readonly, nonatomic) UIImage *realmIcon; // @synthesize realmIcon=_realmIcon;
@property(readonly, nonatomic) NSString *localizedSystemFirstPartyName; // @synthesize localizedSystemFirstPartyName=_localizedSystemFirstPartyName;
@property(readonly, nonatomic) UIImage *systemFirstPartyIcon; // @synthesize systemFirstPartyIcon=_systemFirstPartyIcon;
@property(readonly, nonatomic) NSURL *artworkURL; // @synthesize artworkURL=_artworkURL;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSString *actionText; // @synthesize actionText=_actionText;
@property(readonly, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)cancelImageDownload;	// IMP=0x0010000000214429
- (void)loadImageForSize:(struct CGSize)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000214350
- (id)initWithAdamID:(id)arg1 title:(id)arg2 subtitle:(id)arg3 actionText:(id)arg4 url:(id)arg5 artworkURL:(id)arg6 systemFirstPartyIcon:(id)arg7 localizedSystemFirstPartyName:(id)arg8 realmIcon:(id)arg9 childViewModels:(id)arg10 targetAppIdentifier:(id)arg11 mediaType:(long long)arg12 logoToTitlePadding:(double)arg13;	// IMP=0x001000000021412d
- (id)initWithResolvedThirdPartyLink:(id)arg1 mediaType:(long long)arg2;	// IMP=0x0010000000213fda
- (id)initWithAppleMediaServicesResult:(id)arg1 thirdPartyLinks:(id)arg2;	// IMP=0x0010000000213be0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

