//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MKMultiPartLabel, NSLayoutConstraint, NSString, RouteStepLabelListView, SimpleSignView, UILayoutGuide, UIView;

__attribute__((visibility("hidden")))
@interface DirectionsStepView
{
    SimpleSignView *_signView;	// 8 = 0x8
    RouteStepLabelListView *_labelListView;	// 16 = 0x10
    _Bool _alignLeftIfNoManeuverSign;	// 24 = 0x18
    _Bool _isDimmedStep;	// 25 = 0x19
    NSLayoutConstraint *_trailingGuideWidth;	// 32 = 0x20
    NSLayoutConstraint *_trailingGuideToContentViewConstraint;	// 40 = 0x28
    UILayoutGuide *_trailingViewGuide;	// 48 = 0x30
    MKMultiPartLabel *_roadDescriptionLabel;	// 56 = 0x38
    _Bool _isSelectedRow;	// 64 = 0x40
    UIView *_trailingView;	// 72 = 0x48
}

+ (id)backgroundColorForIndex:(long long)arg1;	// IMP=0x0020000000196e1d
+ (unsigned long long)signViewIconSize;	// IMP=0x0010000000196e12
+ (CDStruct_092aca68)arrowMetrics;	// IMP=0x0010000000196de7
+ (id)_multiPartAttributedStringForRoadDescriptionsInStep:(id)arg1;	// IMP=0x0010000000196035
+ (id)_roadDescriptionsLabelForStep:(id)arg1 width:(double)arg2;	// IMP=0x0010000000195ebe
+ (double)heightForWidth:(double)arg1 route:(id)arg2 step:(id)arg3 idiom:(long long)arg4;	// IMP=0x00100000001943ae
+ (Class)_labelListViewClassForRoute:(id)arg1 step:(id)arg2;	// IMP=0x001000000019439d
+ (double)_textWidthForWidth:(double)arg1 withManeuver:(_Bool)arg2 metrics:(CDStruct_afa449f9)arg3;	// IMP=0x001000000019437f
+ (double)_heightForRoadDescriptionViewWithStep:(id)arg1 forWidth:(double)arg2;	// IMP=0x001000000019427b
+ (CDStruct_afa449f9)cellMetricsForIdiom:(long long)arg1;	// IMP=0x00100000001941fe
- (void).cxx_destruct;	// IMP=0x0020000000196e46
@property(retain, nonatomic) UIView *trailingView; // @synthesize trailingView=_trailingView;
@property(nonatomic) _Bool isSelectedRow; // @synthesize isSelectedRow=_isSelectedRow;
- (id)_minorLabelColor;	// IMP=0x0010000000196d63
- (id)_majorLabelColor;	// IMP=0x0010000000196cdf
- (void)_updateStyleValuesFromTheme;	// IMP=0x0010000000196b85
- (double)_dimAlpha;	// IMP=0x0010000000196b20
- (void)setIsDimmedStep:(_Bool)arg1;	// IMP=0x0010000000196afd
- (id)signView;	// IMP=0x001000000019695f
- (void)_updateSignViewForStep:(id)arg1 shieldImage:(id)arg2 route:(id)arg3;	// IMP=0x0010000000196547
- (id)_shieldImageFromStep:(id)arg1 route:(id)arg2 shieldSize:(long long)arg3;	// IMP=0x0010000000195b1a
- (void)_updateTrailingGuideToContentViewConstraintWithConstant:(double)arg1;	// IMP=0x00100000001957d3
- (void)setRoute:(id)arg1 step:(id)arg2 stepIndex:(unsigned long long)arg3 alignToLeftEdgeIfNoManeuverSign:(_Bool)arg4 size:(long long)arg5;	// IMP=0x0010000000194f49
- (void)layoutSubviews;	// IMP=0x001000000019455b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

