//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AddressBookAddress, NSString, SearchResult;

__attribute__((visibility("hidden")))
@interface DirectionsHomeHistoryItem : NSObject
{
    SearchResult *_currentLocation;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000002e5b60
@property(retain, nonatomic) SearchResult *currentLocation; // @synthesize currentLocation=_currentLocation;
@property(readonly, nonatomic) double timestamp;
@property(readonly, nonatomic) AddressBookAddress *homeAddress;
- (id)init;	// IMP=0x00100000002e5a65
- (void)updateModel:(id)arg1;	// IMP=0x001000000035f39f
- (id)entryWithTicket:(id)arg1;	// IMP=0x0010000000791fc8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

