//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, UILabel, UIScrollView, UIStackView;
@protocol ErrorResultsViewDelegate;

__attribute__((visibility("hidden")))
@interface ErrorResultsView : UIView
{
    UIScrollView *_scrollView;	// 8 = 0x8
    UIStackView *_stackView;	// 16 = 0x10
    UILabel *_titleLabel;	// 24 = 0x18
    NSMutableArray *_suggestionsButtons;	// 32 = 0x20
    NSArray *_suggestions;	// 40 = 0x28
    id <ErrorResultsViewDelegate> _delegate;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000364ad1
@property(nonatomic) __weak id <ErrorResultsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)setupConstraints;	// IMP=0x0010000000364389
- (id)init;	// IMP=0x001000000036409a
- (void)setTitle:(id)arg1 andSuggestions:(id)arg2;	// IMP=0x0010000000363a9f
- (void)updateTheme;	// IMP=0x00100000003638d0
- (void)buttonAction:(id)arg1;	// IMP=0x001000000036381c

@end

