//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, UIImageView;

__attribute__((visibility("hidden")))
@interface FullscreenImageViewControllerZoomAnimationController : NSObject
{
    UIImageView *_originalImageView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000003fa1a8
- (void)animateTransition:(id)arg1;	// IMP=0x00100000003f981d
- (double)transitionDuration:(id)arg1;	// IMP=0x00100000003f980f
- (id)initWithOriginalImageView:(id)arg1;	// IMP=0x00100000003f9791

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

