//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GeoServices/GEOComposedAdvisoryItem.h>

@class NSString;

@interface GEOComposedAdvisoryItem (CarSearchCellDataSource)
- (void)updateModel:(id)arg1;	// IMP=0x00200000003602b5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

