//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface LoadingToken : NSObject
{
    CDUnknownBlockType _invalidate;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000083b5fa
- (void)end;	// IMP=0x001000000083b5cd
- (void)dealloc;	// IMP=0x001000000083b58f
- (id)initWithInvalidationBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000083b51c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

