//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class BNBannerSource, BannerItem, GuidanceManeuverView, NSLayoutConstraint, NSString, NavSignLaneGuidanceView, NavSignShieldInfo, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface ManeuverBannerView : UIView
{
    UIView *_maneuverImageContainer;	// 8 = 0x8
    GuidanceManeuverView *_maneuverImageView;	// 16 = 0x10
    NavSignLaneGuidanceView *_laneGuidanceView;	// 24 = 0x18
    UILabel *_distanceLabel;	// 32 = 0x20
    UILabel *_descriptionLabel;	// 40 = 0x28
    UIImageView *_exitShield;	// 48 = 0x30
    NSLayoutConstraint *_maneuverImageLeadingConstraint;	// 56 = 0x38
    NSLayoutConstraint *_laneGuidanceTopConstraint;	// 64 = 0x40
    NSLayoutConstraint *_distanceLabelToTopConstraint;	// 72 = 0x48
    NSLayoutConstraint *_distanceLabelToLaneGuidanceConstraint;	// 80 = 0x50
    NSLayoutConstraint *_distanceLabelToExitShieldConstraint;	// 88 = 0x58
    NSLayoutConstraint *_distanceLabelToTrailingConstraint;	// 96 = 0x60
    NSLayoutConstraint *_descriptionToDistanceConstraint;	// 104 = 0x68
    double _calculatedWidth;	// 112 = 0x70
    double _cachedHeight;	// 120 = 0x78
    _Bool _showingLaneGuidance;	// 128 = 0x80
    _Bool _showingManeuverImage;	// 129 = 0x81
    _Bool _showingDescription;	// 130 = 0x82
    _Bool _showingExitShield;	// 131 = 0x83
    NavSignShieldInfo *_cachedShieldInfo;	// 136 = 0x88
    BNBannerSource *_target;	// 144 = 0x90
    BannerItem *_item;	// 152 = 0x98
}

- (void).cxx_destruct;	// IMP=0x00200000001eef11
@property(readonly, nonatomic) BannerItem *item; // @synthesize item=_item;
@property(readonly, nonatomic) __weak BNBannerSource *target; // @synthesize target=_target;
@property(readonly, nonatomic) unsigned long long bannerType;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00100000001eed53
- (double)heightForSignWithWidth:(double)arg1;	// IMP=0x00100000001eeba8
- (void)updateFromBannerItem;	// IMP=0x00100000001ee4fa
- (id)minorText;	// IMP=0x00100000001ee3fe
- (id)majorText;	// IMP=0x00100000001ee318
- (void)updateLayout;	// IMP=0x00100000001edfa4
- (id)maneuverItem;	// IMP=0x00100000001edf92
- (id)initWithTarget:(id)arg1 item:(id)arg2;	// IMP=0x00100000001ece9c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

