//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MapsSupport/MSPHistoryContainer.h>

@class MSPHistoryRAPStorage;

@interface MSPHistoryContainer (MapsAdditions)
+ (id)defaultContainer;	// IMP=0x0020000000aa0a04
- (void)garbageCollectRAPStorageIfNeeded;	// IMP=0x0020000000aa171d
- (void)updateExistingEntryFromEntry:(id)arg1 completionQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000aa14b8
- (void)fetchEntryForIdentifier:(id)arg1 completionQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000aa10a6
- (id)userVisibleContentsQuerySourceDedupingSupersededItems:(_Bool)arg1;	// IMP=0x0010000000aa0c2f
@property(readonly, nonatomic) MSPHistoryRAPStorage *searchRecordingStorage;
@property(readonly, nonatomic) MSPHistoryRAPStorage *directionsRecordingStorage;
@end

