//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, NSMutableArray, ParkedCar;
@protocol GEOMapServiceTicket;

__attribute__((visibility("hidden")))
@interface ParkedCarManager : NSObject
{
    NSHashTable *_observers;	// 8 = 0x8
    id <GEOMapServiceTicket> _ticket;	// 16 = 0x10
    NSMutableArray *_fetchHandlers;	// 24 = 0x18
    _Bool _isUpdating;	// 32 = 0x20
    ParkedCar *_parkedCar;	// 40 = 0x28
}

+ (id)sharedManager;	// IMP=0x0040000000a452fa
- (void).cxx_destruct;	// IMP=0x0020000000a48470
@property(readonly, nonatomic) ParkedCar *parkedCar; // @synthesize parkedCar=_parkedCar;
- (void)_debug_showParkedCarReplacementNotificationAfterDelay:(double)arg1;	// IMP=0x0010000000a483bb
- (void)_debug_showParkedCarNotificationAfterDelay:(double)arg1;	// IMP=0x0010000000a48332
- (void)_debug_reloadParkedCar;	// IMP=0x0010000000a48320
- (void)_debug_addParkedCarAtLocation:(id)arg1;	// IMP=0x0010000000a47fce
- (void)informCoreRoutineOfEngagementWithParkedCar:(id)arg1;	// IMP=0x0010000000a47fc8
- (void)setCoordinate:(struct CLLocationCoordinate2D)arg1 referenceFrame:(int)arg2 forParkedCar:(id)arg3;	// IMP=0x0010000000a47c94
- (void)setNotes:(id)arg1 forParkedCar:(id)arg2;	// IMP=0x0010000000a47a35
- (void)setImage:(id)arg1 forParkedCar:(id)arg2;	// IMP=0x0010000000a4747a
- (void)removeImageForParkedCar:(id)arg1;	// IMP=0x0010000000a4723d
- (void)removeParkedCar;	// IMP=0x0010000000a471a2
- (void)updateParkedCar;	// IMP=0x0010000000a47190
- (void)_updateParkedCarMapItem;	// IMP=0x0010000000a46cf3
- (void)_updateParkedCar;	// IMP=0x0010000000a464cf
- (void)resolveMapItemFromVehicleEvent:(id)arg1 overrideCoordinate:(struct CLLocationCoordinate2D)arg2 referenceFrame:(int)arg3 callback:(CDUnknownBlockType)arg4;	// IMP=0x0010000000a4607b
- (void)setParkedCarWithMapItem:(id)arg1 overrideCoordinate:(struct CLLocationCoordinate2D)arg2 referenceFrame:(int)arg3 vehicleEvent:(id)arg4;	// IMP=0x0010000000a45b79
- (void)updateParkedCarWithVehicleEvent:(id)arg1 coordinate:(struct CLLocationCoordinate2D)arg2 referenceFrame:(int)arg3;	// IMP=0x0010000000a45835
- (void)fetchParkedCar:(CDUnknownBlockType)arg1;	// IMP=0x0010000000a45766
- (void)removeParkedCarObserver:(id)arg1;	// IMP=0x0010000000a45750
- (void)addParkedCarObserver:(id)arg1;	// IMP=0x0010000000a456e6
- (void)_willResume:(id)arg1;	// IMP=0x0010000000a456d4
- (void)_authDidChange:(id)arg1;	// IMP=0x0010000000a45667
- (void)dealloc;	// IMP=0x0010000000a455bb
- (id)init;	// IMP=0x0010000000a4534f

@end

