//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEORPWatchAuxiliaryControl, NSString;

__attribute__((visibility("hidden")))
@interface RAPAuxiliaryControlWatch : NSObject
{
    NSString *_serialNumber;	// 8 = 0x8
    _Bool _active;	// 16 = 0x10
    GEORPWatchAuxiliaryControl *_reportAProblemControlMessage;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000079070c
@property(readonly, nonatomic) GEORPWatchAuxiliaryControl *reportAProblemControlMessage; // @synthesize reportAProblemControlMessage=_reportAProblemControlMessage;
@property(readonly, nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
- (_Bool)isSameControlAsControl:(id)arg1;	// IMP=0x0010000000790678
- (id)initWithPropertiesOfDevice:(id)arg1;	// IMP=0x001000000079048b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

