//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, RAPQuestion;
@protocol RAPMenuItem;

__attribute__((visibility("hidden")))
@interface RAPMainQuestion
{
    NSArray *_homeWorkCategories;	// 56 = 0x38
    NSArray *_homeWorkMenuItems;	// 64 = 0x40
    NSArray *_incidentMenuItems;	// 72 = 0x48
    RAPQuestion<RAPMenuItem> *_otherIssueMenuItem;	// 80 = 0x50
}

+ (id)localizedHeaderText;	// IMP=0x004000000021ee7a
- (void).cxx_destruct;	// IMP=0x002000000021f9a5
@property(retain, nonatomic) RAPQuestion<RAPMenuItem> *otherIssueMenuItem; // @synthesize otherIssueMenuItem=_otherIssueMenuItem;
@property(retain, nonatomic) NSArray *incidentMenuItems; // @synthesize incidentMenuItems=_incidentMenuItems;
@property(retain, nonatomic) NSArray *homeWorkMenuItems; // @synthesize homeWorkMenuItems=_homeWorkMenuItems;
- (id)_alternateMapViewContext;	// IMP=0x001000000021f919
- (void)_fillSubmissionParameters:(id)arg1;	// IMP=0x001000000021f724
- (id)followUpQuestionForCategory:(long long)arg1;	// IMP=0x001000000021f522
- (_Bool)canDisplayMenuItemForQuestionCategory:(long long)arg1;	// IMP=0x001000000021f3cf
- (void)resetMenu;	// IMP=0x001000000021f358
- (id)menuItems;	// IMP=0x001000000021eec8
- (_Bool)shouldShowSubtitles;	// IMP=0x001000000021eec0
- (_Bool)shouldShowIcons;	// IMP=0x001000000021eeb8
- (int)analyticTarget;	// IMP=0x001000000021ee6f
- (id)mainMenuQuestionCategories;	// IMP=0x001000000021ee37
- (id)_questionsFromLayoutItems:(id)arg1;	// IMP=0x001000000021ebb0
- (id)_incidentQuestionsFromLayoutItems:(id)arg1;	// IMP=0x001000000021e974
- (void)updateCategoriesFromLayoutManager:(id)arg1;	// IMP=0x001000000021e6b5

@end

