//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, RAPEditLocationViewController, RAPIncidentsQuestion, RAPReportComposerCommentPart, RAPReportComposerMapFeaturePickerPart;

__attribute__((visibility("hidden")))
@interface RAPReportComposerIncidentsEditorViewController
{
    RAPIncidentsQuestion *_question;	// 8 = 0x8
    RAPEditLocationViewController *_mapPicker;	// 16 = 0x10
    RAPReportComposerMapFeaturePickerPart *_labelMarkerPickerPart;	// 24 = 0x18
    RAPReportComposerCommentPart *_commentPart;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000638c0c
- (void)_presentMapPicker;	// IMP=0x0010000000638897
- (void)inlineMapViewModelRequestsDisplayPowerActions:(id)arg1;	// IMP=0x0010000000638885
- (id)tableParts;	// IMP=0x0010000000638656
@property(readonly, nonatomic) int analyticTarget;
- (id)initWithReport:(id)arg1 question:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000063856c

// Remaining properties
@property(readonly, nonatomic) int backAction;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *eventValue;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

