//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class RAPQuestion;
@protocol RAPSnippetProtocol;

__attribute__((visibility("hidden")))
@interface RAPReportComposerSnippetSection
{
    RAPQuestion<RAPSnippetProtocol> *_question;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000ae93dc
- (double)heightForRowAtIndex:(long long)arg1;	// IMP=0x0010000000ae9229
- (id)cellForRowAtIndex:(long long)arg1;	// IMP=0x0010000000ae8f52
- (_Bool)isCurrentLocation;	// IMP=0x0010000000ae8eba
- (long long)rowsCount;	// IMP=0x0010000000ae8e8d
- (id)headerTitle;	// IMP=0x0010000000ae8d91
- (id)initWithQuestion:(id)arg1;	// IMP=0x0010000000ae8cec

@end

