//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class RAPWebBundleHomeViewController, UINavigationController;

__attribute__((visibility("hidden")))
@interface RAPWebBundleContaineeViewController
{
    RAPWebBundleHomeViewController *_contentViewController;	// 8 = 0x8
    UINavigationController *_navController;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000015d0a2
- (void)enableDismissByGesture:(_Bool)arg1;	// IMP=0x001000000015d08a
- (double)heightForLayout:(unsigned long long)arg1;	// IMP=0x001000000015d03a
- (void)_setupConstraints;	// IMP=0x001000000015ccae
- (void)_setupViews;	// IMP=0x001000000015caec
- (void)viewDidLoad;	// IMP=0x001000000015ca87
- (id)initWithReport:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000015c9ae

@end

