//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSPredicate;

__attribute__((visibility("hidden")))
@interface RecentsDataFilter : NSObject
{
    unsigned int _searchMode;	// 8 = 0x8
    NSPredicate *_filterPredicate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000001ab1cb
@property(readonly, nonatomic) unsigned int searchMode; // @synthesize searchMode=_searchMode;
@property(readonly, nonatomic) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
- (id)filteredRecents:(id)arg1 excludingDuplicatesOfEntries:(id)arg2;	// IMP=0x00100000001a9b5d
- (id)init;	// IMP=0x00100000001a9b46
- (id)initWithFilterPredicate:(id)arg1;	// IMP=0x00100000001a9b2c
- (id)initWithSearchMode:(unsigned int)arg1;	// IMP=0x00100000001a9b18
- (id)initWithSearchMode:(unsigned int)arg1 filterPredicate:(id)arg2;	// IMP=0x00100000001a9aa2

@end

