//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewController.h>

@class ContactRequirements, INRestaurantGuestDisplayPreferences, NSArray, NSPersonNameComponents, NSString, ReservationInputCell;
@protocol ReservationContactInfoViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface ReservationContactInfoViewController : UITableViewController
{
    id <ReservationContactInfoViewControllerDelegate> _contactDelegate;	// 8 = 0x8
    ReservationInputCell *_firstNameCell;	// 16 = 0x10
    ReservationInputCell *_lastNameCell;	// 24 = 0x18
    ReservationInputCell *_phoneNumberCell;	// 32 = 0x20
    ReservationInputCell *_emailCell;	// 40 = 0x28
    NSString *_footerText;	// 48 = 0x30
    NSPersonNameComponents *_initializedNameComponents;	// 56 = 0x38
    NSString *_initializedPhoneNumber;	// 64 = 0x40
    NSString *_initializedEmailAddress;	// 72 = 0x48
    NSArray *_contactItems;	// 80 = 0x50
    INRestaurantGuestDisplayPreferences *_guestDisplayPreferences;	// 88 = 0x58
    ContactRequirements *_requirements;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x0020000000180b60
@property(copy, nonatomic) ContactRequirements *requirements; // @synthesize requirements=_requirements;
@property(copy, nonatomic) INRestaurantGuestDisplayPreferences *guestDisplayPreferences; // @synthesize guestDisplayPreferences=_guestDisplayPreferences;
@property(retain, nonatomic) NSArray *contactItems; // @synthesize contactItems=_contactItems;
@property(retain, nonatomic) NSString *initializedEmailAddress; // @synthesize initializedEmailAddress=_initializedEmailAddress;
@property(retain, nonatomic) NSString *initializedPhoneNumber; // @synthesize initializedPhoneNumber=_initializedPhoneNumber;
@property(retain, nonatomic) NSPersonNameComponents *initializedNameComponents; // @synthesize initializedNameComponents=_initializedNameComponents;
@property(copy, nonatomic) NSString *footerText; // @synthesize footerText=_footerText;
@property(retain, nonatomic) ReservationInputCell *emailCell; // @synthesize emailCell=_emailCell;
@property(retain, nonatomic) ReservationInputCell *phoneNumberCell; // @synthesize phoneNumberCell=_phoneNumberCell;
@property(retain, nonatomic) ReservationInputCell *lastNameCell; // @synthesize lastNameCell=_lastNameCell;
@property(retain, nonatomic) ReservationInputCell *firstNameCell; // @synthesize firstNameCell=_firstNameCell;
@property(nonatomic) __weak id <ReservationContactInfoViewControllerDelegate> contactDelegate; // @synthesize contactDelegate=_contactDelegate;
@property(readonly, nonatomic) NSString *phoneNumber;
@property(readonly, nonatomic) NSString *emailAddress;
@property(readonly, nonatomic) NSPersonNameComponents *nameComponents;
- (id)stringForNameMissing:(_Bool)arg1 phoneNumberMissing:(_Bool)arg2 emailAddressMissing:(_Bool)arg3;	// IMP=0x00100000001804e0
- (void)updateFooterText;	// IMP=0x00100000001803f3
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;	// IMP=0x00100000001803e1
- (id)inputCellForType:(unsigned long long)arg1;	// IMP=0x00100000001803ab
- (void)syncStateForInputCell:(id)arg1 type:(unsigned long long)arg2;	// IMP=0x001000000018035c
- (id)titleStringForContactCellType:(unsigned long long)arg1;	// IMP=0x0010000000180229
- (long long)inputCellTypeForContactCellType:(unsigned long long)arg1;	// IMP=0x0010000000180208
- (id)textFieldTextForContactCellType:(unsigned long long)arg1;	// IMP=0x001000000017ff0f
- (void)configureCell:(id)arg1 withItem:(id)arg2;	// IMP=0x001000000017fc98
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x001000000017fae9
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x001000000017faa5
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x001000000017fa9a
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;	// IMP=0x001000000017fa8c
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x001000000017fa01
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x001000000017f91d
- (void)doneButtonTapped:(id)arg1;	// IMP=0x001000000017f8d1
- (void)configureTableView;	// IMP=0x001000000017f759
- (id)itemsForGuestDisplayPreferences:(id)arg1 requirements:(id)arg2;	// IMP=0x001000000017f3f0
- (void)configureContactItems;	// IMP=0x001000000017f356
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x001000000017f2e5
- (void)viewDidLoad;	// IMP=0x001000000017f28f
- (id)initWithNameComponents:(id)arg1 emailAddress:(id)arg2 phoneNumber:(id)arg3 guestDisplayPreferences:(id)arg4 requirements:(id)arg5;	// IMP=0x001000000017f0d0

@end

