//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MKViewWithHairline, NSString, UIColor, UIFont, UILabel;

__attribute__((visibility("hidden")))
@interface RestaurantReservationSectionHeaderTableViewCell
{
    UILabel *_headerLabel;	// 8 = 0x8
    MKViewWithHairline *_hairlineContainer;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000871098
@property(retain, nonatomic) MKViewWithHairline *hairlineContainer; // @synthesize hairlineContainer=_hairlineContainer;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(retain, nonatomic) UIFont *font;
@property(nonatomic) _Bool hidesHairline;
@property(copy, nonatomic) NSString *text;
@property(retain, nonatomic) UIColor *textColor;
- (void)updateTheme;	// IMP=0x0010000000870cc3
- (void)initConstraints;	// IMP=0x00100000008704e9
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0010000000870237

@end

