//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSLayoutConstraint, NSLayoutDimension, UIButton, UIVisualEffectView;

__attribute__((visibility("hidden")))
@interface SharedTripNavBannerView
{
    UIVisualEffectView *_backgroundView;	// 8 = 0x8
    UIButton *_shareETAButton;	// 16 = 0x10
    NSLayoutConstraint *_buttonHeightConstraint;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000759df2
- (void)addTarget:(id)arg1 action:(SEL)arg2;	// IMP=0x0010000000759dcf
- (void)updateTheme;	// IMP=0x0010000000759d56
- (double)buttonHeightConstant;	// IMP=0x0010000000759cd0
- (void)_updateFonts;	// IMP=0x0010000000759bfb
- (void)_updateButtonHeightConstraint;	// IMP=0x0010000000759bc5
- (void)updateButtonTitle;	// IMP=0x0010000000759aa5
- (_Bool)bannerShouldShow;	// IMP=0x0010000000759a2c
@property(readonly, nonatomic) NSLayoutDimension *contentHeightAnchor;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x001000000075990e
- (void)dealloc;	// IMP=0x0010000000759899
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000759256

@end

