//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface ShortcutSuggestionsDataSource
{
    NSArray *_suggestions;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000685acf
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000685ab6
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000685a9d
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x001000000068597f
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;	// IMP=0x001000000068590f
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x00100000006857cc
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;	// IMP=0x00100000006856ee
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00100000006855b9
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0010000000685575
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x001000000068556a
- (void)didTapOnAccessoryView:(id)arg1 withType:(long long)arg2 object:(id)arg3;	// IMP=0x00100000006853f8
- (int)targetForDragAnalytics;	// IMP=0x00100000006853f0
- (id)objectsForAnalytics;	// IMP=0x00100000006853e8
- (void)setActive:(_Bool)arg1;	// IMP=0x001000000068539d
- (void)shortcutSelected:(id)arg1;	// IMP=0x0010000000685328
- (id)objectAtIndexPath:(id)arg1;	// IMP=0x0010000000685250
- (id)currentSuggestions;	// IMP=0x001000000068522b
- (id)shortcutManager;	// IMP=0x00100000006851e4
- (void)_updateSuggestions:(id)arg1;	// IMP=0x0010000000685165
- (void)_loadContentAndSuggestions;	// IMP=0x0010000000684faf
- (id)initWithTableView:(id)arg1 updateLocation:(_Bool)arg2;	// IMP=0x0010000000684eea

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

