//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface TraceBookmarkRow : NSObject
{
    NSString *_name;	// 8 = 0x8
    NSString *_detail;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000d084c
- (void)configureCell:(id)arg1;	// IMP=0x00100000000d079a
- (id)initWithName:(id)arg1 detail:(id)arg2;	// IMP=0x00100000000d0701

@end

