//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class GEOTransitBoardingInfoEntry, GEOTransitExitPlanInfo, HairlineView, MKMultiPartLabel, MapsLargerHitTargetButton, NSArray, NSLayoutConstraint, TransitDirectionsExitPlanView, TransitDirectionsOccupancyStatusView, UIStackView;

__attribute__((visibility("hidden")))
@interface TransitDirectionsBoardingInfoView : UIView
{
    MKMultiPartLabel *_label;	// 8 = 0x8
    MapsLargerHitTargetButton *_button;	// 16 = 0x10
    TransitDirectionsOccupancyStatusView *_occupancyStatusView;	// 24 = 0x18
    TransitDirectionsExitPlanView *_exitPlanView;	// 32 = 0x20
    UIStackView *;	// 40 = 0x28
    UIStackView *_occupancyAndExitStackView;	// 48 = 0x30
    GEOTransitExitPlanInfo *_exitPlanInfo;	// 56 = 0x38
    HairlineView *_trailingHairline;	// 64 = 0x40
    _Bool _forceVerticalAxis;	// 72 = 0x48
    _Bool _useAlternativeInstruction;	// 73 = 0x49
    GEOTransitBoardingInfoEntry *_entry;	// 80 = 0x50
    NSArray *_preboardingStrings;	// 88 = 0x58
    unsigned long long _entryType;	// 96 = 0x60
    unsigned long long _preferredLayout;	// 104 = 0x68
    NSLayoutConstraint *_fixedWidthConstraint;	// 112 = 0x70
}

- (void).cxx_destruct;	// IMP=0x0020000000880ea1
@property(retain, nonatomic) NSLayoutConstraint *fixedWidthConstraint; // @synthesize fixedWidthConstraint=_fixedWidthConstraint;
@property(nonatomic) _Bool useAlternativeInstruction; // @synthesize useAlternativeInstruction=_useAlternativeInstruction;
@property(nonatomic) _Bool forceVerticalAxis; // @synthesize forceVerticalAxis=_forceVerticalAxis;
@property(nonatomic) unsigned long long preferredLayout; // @synthesize preferredLayout=_preferredLayout;
@property(nonatomic) unsigned long long entryType; // @synthesize entryType=_entryType;
@property(readonly, nonatomic) NSArray *preboardingStrings; // @synthesize preboardingStrings=_preboardingStrings;
@property(readonly, nonatomic) GEOTransitExitPlanInfo *exitPlanInfo; // @synthesize exitPlanInfo=_exitPlanInfo;
@property(readonly, nonatomic) GEOTransitBoardingInfoEntry *entry; // @synthesize entry=_entry;
- (void)_refreshContent;	// IMP=0x0010000000880332
- (void)setButtonTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;	// IMP=0x0010000000880245
- (void)setPreboardingStrings:(id)arg1;	// IMP=0x001000000088016b
- (void)setBoardingInfoEntry:(id)arg1 exitPlan:(id)arg2;	// IMP=0x0010000000880060
- (void)_updateLayout;	// IMP=0x001000000087fed2
- (unsigned long long)resolvedLayout;	// IMP=0x001000000087fe83
@property(nonatomic) _Bool separatorHidden;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000087f232

@end

