//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface TransitScheduleCardVehiclePositionAnnotationView
{
}

+ (double)shadowBlur;	// IMP=0x004000000080432f
- (struct CGSize)intrinsicContentSize;	// IMP=0x0040000000804298

@end

