//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface TransitDirectionsBoardingInfoStackView : UIView
{
    NSArray *_verticalLayoutConstraints;	// 8 = 0x8
    NSArray *_horizontalLayoutConstraints;	// 16 = 0x10
    long long _axis;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000895a10
@property(nonatomic) long long axis; // @synthesize axis=_axis;
- (id)bottomView;	// IMP=0x00100000008959e7
- (id)topView;	// IMP=0x00100000008959cf
- (void)_axisDidChange;	// IMP=0x0010000000895959
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000895095

@end

