//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface UGCPhotosForm
{
    NSMutableArray *_activePhotoList;	// 8 = 0x8
    NSMutableArray *_removedExistingPhotos;	// 16 = 0x10
    long long _actionType;	// 24 = 0x18
}

+ (unsigned long long)maximumNumberOfPhotos;	// IMP=0x002000000023bc30
+ (unsigned long long)maximumNumberOfPhotosPerSubmission;	// IMP=0x001000000023bc19
+ (id)addPhotosFormWithPlaceQuestionnaire:(id)arg1 photosWithMetadata:(id)arg2;	// IMP=0x001000000023a585
+ (id)editPhotosFormWithPlaceQuestionnaire:(id)arg1 previouslySubmittedImages:(id)arg2;	// IMP=0x001000000023a306
- (void).cxx_destruct;	// IMP=0x002000000023bc58
@property(readonly, nonatomic) long long actionType; // @synthesize actionType=_actionType;
- (void)_fillSubmissionFieldsForDelete:(id)arg1;	// IMP=0x001000000023b883
- (void)_fillSubmissionFieldsForAddOrEdit:(id)arg1;	// IMP=0x001000000023b3e7
- (void)fillSubmissionFields:(id)arg1;	// IMP=0x001000000023b399
@property(readonly, nonatomic) _Bool isEdited;
@property(readonly, nonatomic) _Bool isEmpty;
- (_Bool)_isCompleteForDelete;	// IMP=0x001000000023b259
- (_Bool)_isCompleteForAddOrEdit;	// IMP=0x001000000023b247
@property(readonly, nonatomic) _Bool passesMinimumRequirementsToBeSubmittable;
- (_Bool)isComplete;	// IMP=0x001000000023b1ee
- (id)addedPhotos;	// IMP=0x001000000023b1a6
- (unsigned long long)numberOfAddedPhotos;	// IMP=0x001000000023b162
@property(readonly, nonatomic) NSArray *removedExistingPhotos;
@property(readonly, nonatomic) NSArray *currentExistingPhotos;
- (long long)indexOfPhotoWithIdentifier:(id)arg1;	// IMP=0x001000000023ae2b
@property(readonly, nonatomic) NSArray *addedPhotosWithMetadata;
@property(readonly, nonatomic) NSArray *activePhotoList;
- (_Bool)removePhotoWithIdentifier:(id)arg1;	// IMP=0x001000000023a9c2
- (_Bool)_addPhoto:(id)arg1;	// IMP=0x001000000023a95c
- (void)addPhotoListWithMetadata:(id)arg1;	// IMP=0x001000000023a80a
- (void)addPhoto:(id)arg1;	// IMP=0x001000000023a6bb
- (id)initWithActionType:(long long)arg1 initialPhotos:(id)arg2;	// IMP=0x001000000023a60d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

