//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, UGCAddPhotoCollectionViewCell, UIBarButtonItem, UICollectionView, UICollectionViewDiffableDataSource, UIColor, UIView, UIViewController;
@protocol UGCPhotoCarouselRequestDelegate;

__attribute__((visibility("hidden")))
@interface UGCPhotoCarouselController : NSObject
{
    NSMutableArray *_viewModels;	// 8 = 0x8
    UICollectionViewDiffableDataSource *_diffableDataSource;	// 16 = 0x10
    UGCAddPhotoCollectionViewCell *_addCell;	// 24 = 0x18
    UICollectionView *_collectionView;	// 32 = 0x20
    unsigned long long _maximumNumberOfPhotos;	// 40 = 0x28
    NSString *_downloadToken;	// 48 = 0x30
    UIViewController *_presentingViewController;	// 56 = 0x38
    id <UGCPhotoCarouselRequestDelegate> _delegate;	// 64 = 0x40
    UIBarButtonItem *_anchoringBarButtonItem;	// 72 = 0x48
    UIColor *_cellBackgroundColor;	// 80 = 0x50
    CDUnknownBlockType _changeHandler;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x00200000008c3a92
@property(copy, nonatomic) CDUnknownBlockType changeHandler; // @synthesize changeHandler=_changeHandler;
@property(nonatomic) unsigned long long maximumNumberOfPhotos; // @synthesize maximumNumberOfPhotos=_maximumNumberOfPhotos;
@property(retain, nonatomic) UIColor *cellBackgroundColor; // @synthesize cellBackgroundColor=_cellBackgroundColor;
@property(readonly, nonatomic) __weak UIBarButtonItem *anchoringBarButtonItem; // @synthesize anchoringBarButtonItem=_anchoringBarButtonItem;
@property(nonatomic) __weak id <UGCPhotoCarouselRequestDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
- (void)photoCellDidCancel:(id)arg1;	// IMP=0x00100000008c39a1
@property(readonly, nonatomic) __weak UIView *anchoringView;
- (id)_buildSnapshotFromCurrentState;	// IMP=0x00100000008c3657
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00100000008c3564
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 itemIdentifier:(id)arg3;	// IMP=0x00100000008c3029
- (id)_viewModelForIdentifier:(id)arg1;	// IMP=0x00100000008c2e64
- (void)_updateAddButtonState;	// IMP=0x00100000008c2e05
- (void)_removeImageForIdentifier:(id)arg1;	// IMP=0x00100000008c2bab
@property(readonly, nonatomic) unsigned long long totalNumberOfItems;
- (void)_cellRequestsRemoveImageForIdentifier:(id)arg1;	// IMP=0x00100000008c2a5c
- (void)setupCollectionView:(id)arg1;	// IMP=0x00100000008c28ee
- (void)_invokeChangeHandler;	// IMP=0x00100000008c287d
- (void)_addViewModel:(id)arg1;	// IMP=0x00100000008c27d2
- (id)visibleImageViewForIdentifier:(id)arg1;	// IMP=0x00100000008c253c
- (void)addImageURL:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x00100000008c249b
- (void)addImage:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x00100000008c23fa
- (void)removeImageForIdentifier:(id)arg1;	// IMP=0x00100000008c23e8
- (void)dealloc;	// IMP=0x00100000008c21da
- (id)initWithDelegate:(id)arg1 maximumNumberOfPhotos:(unsigned long long)arg2;	// IMP=0x00100000008c2126
@property(readonly, nonatomic) NSString *downloadToken; // @synthesize downloadToken=_downloadToken;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

