//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ACAccount, ContainerHeaderView, NSString, UserProfileCollectionViewController, UserProfileHeaderView;
@protocol ActionCoordination;

__attribute__((visibility("hidden")))
@interface UserProfileContaineeViewController
{
    UserProfileCollectionViewController *_contentViewController;	// 8 = 0x8
    ContainerHeaderView *_headerView;	// 16 = 0x10
    id <ActionCoordination> _actionCoordinator;	// 24 = 0x18
    long long numberOfRows;	// 32 = 0x20
    ACAccount *_account;	// 40 = 0x28
    UserProfileHeaderView *_userProfileHeaderView;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000079ae04
@property(retain, nonatomic) UserProfileHeaderView *userProfileHeaderView; // @synthesize userProfileHeaderView=_userProfileHeaderView;
@property(retain, nonatomic) ACAccount *account; // @synthesize account=_account;
@property(nonatomic) long long numberOfRows; // @synthesize numberOfRows;
- (void)userDataDidUpdate;	// IMP=0x001000000079ad6a
- (void)_proceedToTravelPreferences;	// IMP=0x001000000079ad4a
- (void)_proceedToVirtualGarage;	// IMP=0x001000000079ad02
- (void)_proceedToRatings;	// IMP=0x001000000079acba
- (void)_proceedToReports;	// IMP=0x001000000079ac72
- (void)_proceedToMyGuides;	// IMP=0x001000000079ab9b
- (void)_proceedToFavorites;	// IMP=0x001000000079ab5b
- (void)userProfileLinkTapped:(id)arg1;	// IMP=0x001000000079aa89
- (void)profileContentDidUpdate;	// IMP=0x001000000079a8bc
- (void)handleDismissAction:(id)arg1;	// IMP=0x001000000079a7fa
- (void)headerViewLinkTapped:(id)arg1;	// IMP=0x001000000079a766
- (void)headerViewButtonTapped:(id)arg1;	// IMP=0x001000000079a754
- (double)_calculateHeight;	// IMP=0x001000000079a640
- (double)heightForLayout:(unsigned long long)arg1;	// IMP=0x001000000079a4aa
- (void)_retrieveUserInformation;	// IMP=0x001000000079a14b
- (void)_setupConstraints;	// IMP=0x0010000000799da9
- (void)_setupViews;	// IMP=0x0010000000799300
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00100000007992d1
- (void)viewDidLoad;	// IMP=0x00100000007991c5
- (id)initWithAccount:(id)arg1;	// IMP=0x0010000000799056

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

