//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ComposedWaypointTask, GEOMapServiceTraits, NSMapTable, Result, WaypointControllerConfiguration;
@protocol OS_dispatch_queue, OS_os_activity, WaypointControllerDelegate;

__attribute__((visibility("hidden")))
@interface WaypointController : NSObject
{
    WaypointControllerConfiguration *_configuration;	// 8 = 0x8
    id <WaypointControllerDelegate> _delegate;	// 16 = 0x10
    Result *_resolvedWaypointSetResult;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_isolationQueue;	// 32 = 0x20
    ComposedWaypointTask *_originTask;	// 40 = 0x28
    ComposedWaypointTask *_destinationTask;	// 48 = 0x30
    NSMapTable *_receivedResults;	// 56 = 0x38
    GEOMapServiceTraits *_traitsForNextTask;	// 64 = 0x40
    NSObject<OS_os_activity> *_activity;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x00200000001b87a1
@property(retain, nonatomic) NSObject<OS_os_activity> *activity; // @synthesize activity=_activity;
@property(copy, nonatomic) GEOMapServiceTraits *traitsForNextTask; // @synthesize traitsForNextTask=_traitsForNextTask;
@property(retain, nonatomic) NSMapTable *receivedResults; // @synthesize receivedResults=_receivedResults;
@property(retain, nonatomic) ComposedWaypointTask *destinationTask; // @synthesize destinationTask=_destinationTask;
@property(retain, nonatomic) ComposedWaypointTask *originTask; // @synthesize originTask=_originTask;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *isolationQueue; // @synthesize isolationQueue=_isolationQueue;
@property(retain) Result *resolvedWaypointSetResult; // @synthesize resolvedWaypointSetResult=_resolvedWaypointSetResult;
@property(nonatomic) __weak id <WaypointControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) WaypointControllerConfiguration *configuration; // @synthesize configuration=_configuration;
- (void)rebroadcastWaypoints;	// IMP=0x00100000001b849e
- (void)_refreshDynamicOrigin;	// IMP=0x00100000001b82bf
- (void)refreshDynamicOrigin;	// IMP=0x00100000001b80b0
- (void)_processTaskFinished;	// IMP=0x00100000001b7ac8
- (void)_submitTask:(id)arg1;	// IMP=0x00100000001b736d
- (void)refresh;	// IMP=0x00100000001b71dc
@property(readonly, nonatomic) _Bool isRunning;
- (void)_stopOnIsolationQueue;	// IMP=0x00100000001b6f54
- (void)stop;	// IMP=0x00100000001b6e6b
- (void)_startOnIsolationQueue;	// IMP=0x00100000001b6a50
- (void)start;	// IMP=0x00100000001b67e2
- (id)initWithConfiguration:(id)arg1;	// IMP=0x00100000001b6430

@end

