//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIButton.h>

@class MISSING_TYPE, NSString;

__attribute__((visibility("hidden")))
@interface _TtC18SharingViewService19SVSStereoPairButton : UIButton
{
    MISSING_TYPE *centerLabel;	// 8 = 0x8
    MISSING_TYPE *interiorLocalizedTextKey;	// 16 = 0x10
    MISSING_TYPE *interiorFontSize;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x004000000013e0e0
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x001000000013e040
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000013d6d0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000013d5e0
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;	// IMP=0x001000000013d550
@property(nonatomic) double interiorFontSize; // @synthesize interiorFontSize;
@property(nonatomic, copy) NSString *interiorLocalizedTextKey;

@end

