//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AFVoiceInfo, NSString, NSTimer, SFSession;
@protocol SUICVoicePreviewingDelegate;

__attribute__((visibility("hidden")))
@interface HomePodSetupSiriVoicePreviewer : NSObject
{
    NSTimer *_powerLevelUpdaterTimer;	// 8 = 0x8
    id <SUICVoicePreviewingDelegate> _voicePreviewerDelegate;	// 16 = 0x10
    AFVoiceInfo *_voicePreviewing;	// 24 = 0x18
    SFSession *_session;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000001d32ea
@property(nonatomic) __weak SFSession *session; // @synthesize session=_session;
@property __weak id <SUICVoicePreviewingDelegate> delegate;
- (void)_updatePowerOutputLevel;	// IMP=0x00100000001d31fd
- (void)previewVoice:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001d2f5b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

