//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProxCardKit/PRXCardContentViewController.h>

@class CUBluetoothClient, NSString, ProximityPairingViewControllerProxy;

__attribute__((visibility("hidden")))
@interface SVSSpatialAudioViewController : PRXCardContentViewController
{
    _Bool _budsInEar;	// 8 = 0x8
    ProximityPairingViewControllerProxy *_mainController;	// 16 = 0x10
    CUBluetoothClient *_bluetoothClient;	// 24 = 0x18
}

+ (void)setSpatialAudioEnabled:(_Bool)arg1;	// IMP=0x00400000001bad58
- (void).cxx_destruct;	// IMP=0x00200000001b8b2c
@property(nonatomic) _Bool budsInEar; // @synthesize budsInEar=_budsInEar;
@property(retain, nonatomic) CUBluetoothClient *bluetoothClient; // @synthesize bluetoothClient=_bluetoothClient;
@property(nonatomic) __weak ProximityPairingViewControllerProxy *mainController; // @synthesize mainController=_mainController;
- (void)_setUpActions;	// IMP=0x00100000001b878e
- (void)_setUpTitleAndSubtitle;	// IMP=0x00100000001b841b
@property(readonly, copy, nonatomic) NSString *placeInEarAlertTitle;
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00100000001b8287
- (void)viewDidLoad;	// IMP=0x00100000001b7d10

@end

