//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NRDevice, NSArray, NSMutableArray, NSString, OBBoldTrayButton, UITableView;

@interface COSRestoreSelectionViewController
{
    NSMutableArray *_restoreInstances;	// 8 = 0x8
    long long _backupIndex;	// 16 = 0x10
    NRDevice *_device;	// 24 = 0x18
    NSArray *_backups;	// 32 = 0x20
    MISSING_TYPE *_pairedDevices;	// 40 = 0x28
    UITableView *_backupsTableView;	// 48 = 0x30
    OBBoldTrayButton *_continueButton;	// 56 = 0x38
}

+ (_Bool)controllerNeedsToRun;	// IMP=0x002000000003e3fb
- (void).cxx_destruct;	// IMP=0x002000000003ea11
@property(retain, nonatomic) OBBoldTrayButton *continueButton; // @synthesize continueButton=_continueButton;
@property(retain, nonatomic) UITableView *backupsTableView; // @synthesize backupsTableView=_backupsTableView;
@property(retain, nonatomic) NSArray *pairedDevices; // @synthesize pairedDevices=_pairedDevices;
@property(retain, nonatomic) NSArray *backups; // @synthesize backups=_backups;
@property(retain, nonatomic) NRDevice *device; // @synthesize device=_device;
@property(nonatomic) long long backupIndex; // @synthesize backupIndex=_backupIndex;
@property(retain, nonatomic) NSMutableArray *restoreInstances; // @synthesize restoreInstances=_restoreInstances;
- (void)device:(id)arg1 propertyDidChange:(id)arg2 fromValue:(id)arg3;	// IMP=0x001000000003e803
- (void)backupsChanged:(unsigned long long)arg1;	// IMP=0x001000000003e5c2
- (id)holdActivityIdentifier;	// IMP=0x001000000003e5b5
- (id)localizedWaitScreenDescription;	// IMP=0x001000000003e549
- (double)waitScreenPushGracePeriod;	// IMP=0x001000000003e53b
- (_Bool)holdWithWaitScreen;	// IMP=0x001000000003e533
- (_Bool)holdBeforeDisplaying;	// IMP=0x001000000003e41a
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x001000000003e2f7
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x001000000003e217
- (void)_skipRestoreFromBackup;	// IMP=0x001000000003e170
- (void)_restoreCompletedWithSuccess;	// IMP=0x001000000003e0b3
- (void)_restoreFailedWithError:(id)arg1;	// IMP=0x001000000003de25
- (void)_triggerRestoreFromDeviceIndex:(long long)arg1;	// IMP=0x001000000003daaa
- (void)_triggerRestoreFromBackupIndex:(long long)arg1;	// IMP=0x001000000003d774
- (void)_triggerRestoreFromIndex:(long long)arg1;	// IMP=0x001000000003d5ef
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x001000000003d582
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;	// IMP=0x001000000003d4d5
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x001000000003d4c7
- (void)tappedNewButton:(id)arg1;	// IMP=0x001000000003d4b5
- (void)tappedContinueButton:(id)arg1;	// IMP=0x001000000003d36b
- (void)viewDidLoad;	// IMP=0x001000000003cea0
- (_Bool)controllerAllowsNavigatingBackFrom;	// IMP=0x001000000003ce53
- (_Bool)controllerAllowsNavigatingBackTo;	// IMP=0x001000000003ce4b
- (void)dealloc;	// IMP=0x001000000003cd8b
- (id)init;	// IMP=0x001000000003cc53

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

