//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSEnumerator.h>

@class NSDirectoryEnumerator, SRSensorsCache;

@interface SRSensorDescriptionEnumerator : NSEnumerator
{
    SRSensorsCache *_sensorsCache;	// 8 = 0x8
    unsigned long long _currentSensorDirectoryIndex;	// 16 = 0x10
    NSDirectoryEnumerator *_descriptionFileEnumerator;	// 24 = 0x18
}

- (id)nextObject;	// IMP=0x002000000001ce90
- (void)dealloc;	// IMP=0x001000000001ce30

@end

