//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AXIndexMap, BRLTTable, MISSING_TYPE, NSArray, NSAttributedString, NSCondition, NSData, NSDictionary, NSMutableCharacterSet, NSString, SCRCTargetSelectorTimer, SCRCThreadKey, SCROBrailleClient, VOTElement, _KSTextReplacementClientStore, _VOTBrailleManagerStatus;

@interface VOTBrailleManager : NSObject
{
    VOTElement *_brailleElement;	// 8 = 0x8
    struct _NSRange _brailleDescriptionRange;	// 16 = 0x10
    struct _NSRange _brailleLineRange;	// 32 = 0x20
    long long _brailleLineOffset;	// 48 = 0x30
    SCRCTargetSelectorTimer *_hintTimer;	// 56 = 0x38
    unsigned long long _brailleElementIndex;	// 64 = 0x40
    _Bool _brailleEnabled;	// 72 = 0x48
    _Bool _usesBrailleSubstitutions;	// 73 = 0x49
    NSDictionary *_brailleSubstitutions;	// 80 = 0x50
    NSMutableCharacterSet *_delimiters;	// 88 = 0x58
    BRLTTable *_currentDefaultTable;	// 96 = 0x60
    BRLTTable *_currentSetTable;	// 104 = 0x68
    _VOTBrailleManagerStatus *_status;	// 112 = 0x70
    _Bool _hasActiveDisplay;	// 120 = 0x78
    _Bool _testingHasActiveDisplay;	// 121 = 0x79
    _Bool _testingKeyboardHelpOn;	// 122 = 0x7a
    AXIndexMap *_commands;	// 128 = 0x80
    id _rotorSelection;	// 136 = 0x88
    _Bool _shouldPreferPositionOverRotorSelection;	// 144 = 0x90
    int _primaryDisplayToken;	// 148 = 0x94
    _Bool _primaryDisplayIsBluetooth;	// 152 = 0x98
    SCROBrailleClient *_brailleClient;	// 160 = 0xa0
    NSCondition *_brailleClientConnectionCondition;	// 168 = 0xa8
    int _lastBraillePanDirection;	// 176 = 0xb0
    SCRCThreadKey *_threadKey;	// 184 = 0xb8
    unsigned int _toggledModifiers;	// 192 = 0xc0
    _KSTextReplacementClientStore *_textReplacementStore;	// 200 = 0xc8
    MISSING_TYPE *_textReplacementEntries;	// 208 = 0xd0
    NSData *_testingAggregatedStatus;	// 216 = 0xd8
    SCRCTargetSelectorTimer *_updateRealtimeStatusTimer;	// 224 = 0xe0
    double _lastRealtimeUpdate;	// 232 = 0xe8
    _Bool _autoAdvanceEnabled;	// 240 = 0xf0
    _Bool _braille2DInvert;	// 241 = 0xf1
    _Bool _testingBrailleElementLocked;	// 242 = 0xf2
    int _lastRefreshTrigger;	// 244 = 0xf4
    BRLTTable *_brailleTableFromSettings;	// 248 = 0xf8
    VOTElement *_previousTouchContainer;	// 256 = 0x100
    NSString *_brailleSubstitutionLanguage;	// 264 = 0x108
    double _braille2DIntensity;	// 272 = 0x110
    double _braille2DZoom;	// 280 = 0x118
    double _lastUserInteractionTime;	// 288 = 0x120
    long long _bookCursorPosition;	// 296 = 0x128
    long long _trailingBookCursorPosition;	// 304 = 0x130
    SCROBrailleClient *_testingBrailleClient;	// 312 = 0x138
    NSArray *_testingTextShortcuts;	// 320 = 0x140
    double _threadWaitTime;	// 328 = 0x148
    CDUnknownBlockType _tableSetCallback;	// 336 = 0x150
    CDUnknownBlockType _elementSetCallback;	// 344 = 0x158
    CDUnknownBlockType _keypressCallback;	// 352 = 0x160
    CDUnknownBlockType _brailleStringSetCallback;	// 360 = 0x168
    struct CGPoint _braille2DOrigin;	// 368 = 0x170
}

+ (double)currentDefaultBrailleAlertTimeout;	// IMP=0x00400000000f4dcd
+ (id)manager;	// IMP=0x00100000000f4dbc
+ (void)initialize;	// IMP=0x00100000000f4d87
- (void).cxx_destruct;	// IMP=0x00200000001023bc
@property(copy, nonatomic) CDUnknownBlockType brailleStringSetCallback; // @synthesize brailleStringSetCallback=_brailleStringSetCallback;
@property(copy, nonatomic) CDUnknownBlockType keypressCallback; // @synthesize keypressCallback=_keypressCallback;
@property(copy, nonatomic) CDUnknownBlockType elementSetCallback; // @synthesize elementSetCallback=_elementSetCallback;
@property(copy, nonatomic) CDUnknownBlockType tableSetCallback; // @synthesize tableSetCallback=_tableSetCallback;
@property(nonatomic) double threadWaitTime; // @synthesize threadWaitTime=_threadWaitTime;
@property(nonatomic) _Bool testingBrailleElementLocked; // @synthesize testingBrailleElementLocked=_testingBrailleElementLocked;
@property(retain, nonatomic) NSArray *testingTextShortcuts; // @synthesize testingTextShortcuts=_testingTextShortcuts;
@property(retain, nonatomic) SCROBrailleClient *testingBrailleClient; // @synthesize testingBrailleClient=_testingBrailleClient;
@property(nonatomic) int lastRefreshTrigger; // @synthesize lastRefreshTrigger=_lastRefreshTrigger;
@property(nonatomic) long long trailingBookCursorPosition; // @synthesize trailingBookCursorPosition=_trailingBookCursorPosition;
@property(nonatomic) long long bookCursorPosition; // @synthesize bookCursorPosition=_bookCursorPosition;
@property(readonly, nonatomic) struct _NSRange brailleLineRange; // @synthesize brailleLineRange=_brailleLineRange;
@property(nonatomic) double lastUserInteractionTime; // @synthesize lastUserInteractionTime=_lastUserInteractionTime;
@property(nonatomic) struct CGPoint braille2DOrigin; // @synthesize braille2DOrigin=_braille2DOrigin;
@property(nonatomic) _Bool braille2DInvert; // @synthesize braille2DInvert=_braille2DInvert;
@property(nonatomic) double braille2DZoom; // @synthesize braille2DZoom=_braille2DZoom;
@property(nonatomic) double braille2DIntensity; // @synthesize braille2DIntensity=_braille2DIntensity;
@property(readonly, nonatomic) NSArray *textReplacementEntries; // @synthesize textReplacementEntries=_textReplacementEntries;
@property(retain) NSString *brailleSubstitutionLanguage; // @synthesize brailleSubstitutionLanguage=_brailleSubstitutionLanguage;
@property(retain, nonatomic) VOTElement *previousTouchContainer; // @synthesize previousTouchContainer=_previousTouchContainer;
@property(retain, nonatomic) BRLTTable *brailleTableFromSettings; // @synthesize brailleTableFromSettings=_brailleTableFromSettings;
@property(nonatomic) _Bool usesBrailleSubstitutions; // @synthesize usesBrailleSubstitutions=_usesBrailleSubstitutions;
@property(nonatomic) _Bool brailleEnabled; // @synthesize brailleEnabled=_brailleEnabled;
- (void)resetTestingAggregatedStatus;	// IMP=0x001000000010210b
- (id)testingAggregatedStatus;	// IMP=0x00100000001020e0
- (_Bool)testingKeyboardHelpIsOn;	// IMP=0x00100000001020d7
- (void)configureForUnitTesting;	// IMP=0x0010000000102087
- (void)unitTestHandleBrailleKeypress:(id)arg1;	// IMP=0x0010000000102075
- (struct _NSRange)rangeOfCellRepresentingCharacterAtIndex:(long long)arg1;	// IMP=0x0010000000101f36
@property(readonly, nonatomic) NSAttributedString *testingMainAttributedString;
- (id)testingBrailleElement;	// IMP=0x0010000000101f0f
@property(readonly, nonatomic) unsigned long long testingBrailleElementIndex;
@property(nonatomic) _Bool testingHasActiveDisplay;
- (id)_localeIdentifierForTableIdentifier:(id)arg1;	// IMP=0x0010000000101d15
- (id)_localeIdentifierForCurrentTable;	// IMP=0x0010000000101c8d
- (id)_tableIdentifierFromDefaultRotorItem:(id)arg1 forLocale:(id)arg2;	// IMP=0x0010000000101be5
- (id)_defaultLanguageRotorItem;	// IMP=0x0010000000101a16
- (id)currentBrailleTableIdentifier;	// IMP=0x00100000001018d3
- (void)handleBrailleStartEditing;	// IMP=0x0010000000101756
- (void)handleBrailleDidShowNextAnnouncement:(id)arg1;	// IMP=0x00100000001016be
- (void)handleBrailleDidShowPreviousAnnouncement:(id)arg1;	// IMP=0x0010000000101626
- (void)_handleDisplayModeChanged:(id)arg1;	// IMP=0x0010000000101595
- (void)handleDisplayModeChanged:(id)arg1;	// IMP=0x001000000010151d
- (void)_handleBraillePlayCommandNotSupportedSound;	// IMP=0x00100000001014a5
- (void)handleBraillePlayCommandNotSupportedSound;	// IMP=0x0010000000101444
- (void)_handleBraillePlayBorderHitSound;	// IMP=0x00100000001013cc
- (void)handleBraillePlayBorderHitSound;	// IMP=0x001000000010136b
- (void)_updateTactileGraphicsDisplays;	// IMP=0x0010000000101083
- (void)_handleBraillePlayDisplayConnectionSound:(id)arg1;	// IMP=0x0010000000100fd2
- (void)handleBraillePlayDisplayConnectionSound:(id)arg1;	// IMP=0x0010000000100f5a
@property(nonatomic) unsigned int persistentKeyModifiers;
- (void)setImageData:(id)arg1;	// IMP=0x0010000000100cfe
- (void)setBrailleMap:(id)arg1;	// IMP=0x0010000000100c3b
- (void)_dispatchBrailleDidPanWithSuccess:(id)arg1 elementToken:(id)arg2 appToken:(id)arg3 direction:(id)arg4 lineOffset:(id)arg5;	// IMP=0x00100000001004ec
- (_Bool)_brailleShouldTryToTurnPage:(id)arg1 direction:(long long)arg2;	// IMP=0x0010000000100461
- (void)handleBrailleDisplayCopyStringToClipboard:(id)arg1;	// IMP=0x00100000001003eb
- (void)handleBrailleDidPanRight:(id)arg1 elementToken:(id)arg2 appToken:(id)arg3 lineOffset:(id)arg4;	// IMP=0x00100000001002a5
- (void)handleBrailleDidPanLeft:(id)arg1 elementToken:(id)arg2 appToken:(id)arg3 lineOffset:(id)arg4;	// IMP=0x0010000000100162
- (void)handleBrailleDeletedUntranslatedText:(id)arg1 speakLiterally:(_Bool)arg2;	// IMP=0x00100000000ffc27
- (void)handleBrailleInsertedUntranslatedText:(id)arg1 speakLiterally:(_Bool)arg2;	// IMP=0x00100000000ff826
- (void)_handleBrailleReplaceTextRange:(id)arg1 withString:(id)arg2 cursor:(id)arg3;	// IMP=0x00100000000fec1f
- (_Bool)_handleKeyboardModifierCommands:(id)arg1;	// IMP=0x00100000000fe1c6
- (void)_handleBrailleKeypress:(id)arg1;	// IMP=0x00100000000fd27b
- (void)handleBrailleReplaceTextRange:(struct _NSRange)arg1 withString:(id)arg2 cursor:(unsigned long long)arg3;	// IMP=0x00100000000fcd32
- (void)handleUserEventOccured;	// IMP=0x00100000000fccee
- (void)handleBrailleKeypress:(id)arg1;	// IMP=0x00100000000fcc41
- (void)_updateOnscreenKeyboardSettings;	// IMP=0x00100000000fc7fc
- (void)_handleBrailleConfigurationChanged:(id)arg1;	// IMP=0x00100000000fc312
- (void)handleBrailleDidReconnect:(id)arg1;	// IMP=0x00100000000fc2ba
- (void)handleBrailleDidDisconnect:(id)arg1;	// IMP=0x00100000000fc265
- (void)handleBrailleConfigurationChanged:(id)arg1;	// IMP=0x00100000000fc19f
- (void)_displayBrailleElementHint;	// IMP=0x00100000000fbf20
@property(retain, nonatomic) VOTElement *brailleElement; // @synthesize brailleElement=_brailleElement;
- (void)_refreshBrailleLinePreferringPositionOverRotorSelection:(_Bool)arg1 knownLineRange:(_Bool)arg2 updatedPosition:(id)arg3;	// IMP=0x00100000000fb860
- (void)_refreshBrailleLine;	// IMP=0x00100000000fb847
- (void)refreshBrailleLine;	// IMP=0x00100000000fb7e6
- (void)_resetBrailleCursor;	// IMP=0x00100000000fb7c5
- (void)_setBrailleElement:(id)arg1 resetBrailleCursor:(id)arg2 rotorSelection:(id)arg3;	// IMP=0x00100000000fb53b
- (void)setBrailleElement:(id)arg1 resetBrailleCursor:(_Bool)arg2 rotorSelection:(id)arg3;	// IMP=0x00100000000fb42f
- (void)_setBrailleString:(id)arg1 type:(id)arg2 timeout:(id)arg3 priority:(id)arg4 langCode:(id)arg5 brailleLineRangeValue:(id)arg6;	// IMP=0x00100000000fabd0
- (void)setBrailleString:(id)arg1 type:(int)arg2 timeout:(double)arg3 langCode:(id)arg4 brailleLineRange:(struct _NSRange)arg5 isBrailleLineRangeKnown:(_Bool)arg6;	// IMP=0x00100000000faa1e
- (void)_filterUnacceptableBrailleStrings:(id)arg1;	// IMP=0x00100000000fa8ef
- (void)applyBrailleSubstitutions:(id)arg1;	// IMP=0x00100000000fa81b
- (void)_handleStatusRouterForIndex:(long long)arg1;	// IMP=0x00100000000fa61b
- (void)_updateStatusCells;	// IMP=0x00100000000f9c65
- (_Bool)statusCellShowsText;	// IMP=0x00100000000f9c4f
- (_Bool)statusCellShowsGeneral;	// IMP=0x00100000000f9c39
- (void)_updateStatusCellPrefs;	// IMP=0x00100000000f9b0d
@property(readonly, nonatomic) _Bool bluetoothBrailleDisplayConnected;
- (void)setSingleLetterQuickNavOn:(_Bool)arg1;	// IMP=0x00100000000f9ad7
- (void)_updateHelpEnabled;	// IMP=0x00100000000f9a30
@property(nonatomic) _Bool autoAdvanceEnabled;
- (void)_updateBrailleAutoAdvancePrefs;	// IMP=0x00100000000f99b8
- (void)updateBrailleAutoAdvancePrefs;	// IMP=0x00100000000f9957
- (void)_updateBrailleKeyDebouncePrefs;	// IMP=0x00100000000f98f6
- (void)_updateWordWrapPrefs;	// IMP=0x00100000000f9807
- (void)_initializeExpandedStatusCellDictionaries;	// IMP=0x00100000000f923a
- (void)_handleBrailleTranslate:(id)arg1;	// IMP=0x00100000000f9234
- (void)_handleBrailleStatusRouter:(id)arg1;	// IMP=0x00100000000f91aa
- (void)_handleBrailleRouter:(id)arg1;	// IMP=0x00100000000f8b58
- (void)_handleBrailleAnnouncementModeOn:(id)arg1;	// IMP=0x00100000000f8b0e
- (void)testingExitDisplayMode;	// IMP=0x00100000000f8aad
- (void)_exitDisplayMode;	// IMP=0x00100000000f8a94
- (void)_handleBrailleToggleEightDot:(id)arg1;	// IMP=0x00100000000f88fd
- (void)_handleBrailleNextOutputMode:(id)arg1;	// IMP=0x00100000000f88e9
- (void)_handleBrailleNextInputMode:(id)arg1;	// IMP=0x00100000000f88d2
- (void)_handleBrailleMode:(id)arg1 input:(_Bool)arg2;	// IMP=0x00100000000f8666
- (void)updateBrailleMode:(_Bool)arg1;	// IMP=0x00100000000f8532
- (MISSING_TYPE *)inputContractionMode;	// IMP=0x00100000000f84be
- (long long)outputContractionMode;	// IMP=0x00100000000f844a
- (_Bool)_supportsMode:(long long)arg1;	// IMP=0x00100000000f83bd
- (void)_handleBrailleToggleContractions:(id)arg1;	// IMP=0x00100000000f8264
- (void)_handleBraillePanRight:(id)arg1;	// IMP=0x00100000000f81f2
- (void)_handleBraillePanLeft:(id)arg1;	// IMP=0x00100000000f8180
- (void)_initializeCommands;	// IMP=0x00100000000f7dd0
- (void)_handleEvent:(id)arg1;	// IMP=0x00100000000f7cc9
- (void)handleEvent:(id)arg1;	// IMP=0x00100000000f7c51
- (void)updateStatusCellPrefs;	// IMP=0x00100000000f7bf0
- (void)handleSettingsChange:(id)arg1;	// IMP=0x00100000000f7ac1
- (_Bool)_languageIsCJK;	// IMP=0x00100000000f79a2
- (void)setTextSearchModeOn:(_Bool)arg1;	// IMP=0x00100000000f7989
- (void)updateUsesNemethForMath;	// IMP=0x00100000000f7925
- (void)_setBrailleSubstitutionLanguage:(id)arg1;	// IMP=0x00100000000f7913
- (void)_setBrailleTable:(id)arg1;	// IMP=0x00100000000f77b5
- (void)updateBrailleLanguage;	// IMP=0x00100000000f75fc
- (void)handleKeyboardChanged;	// IMP=0x00100000000f7456
- (long long)_adjustedRotorIndex:(long long)arg1 inDirection:(long long)arg2 rotorItems:(id)arg3;	// IMP=0x00100000000f7413
- (_Bool)_shouldIncludeServiceNameForSpokenBrailleRotorAnnouncementOfTable:(id)arg1 rotorItems:(id)arg2 locale:(id)arg3;	// IMP=0x00100000000f6fbf
- (long long)_indexOfBrailleTable:(id)arg1 inRotorItems:(id)arg2;	// IMP=0x00100000000f6e14
- (void)announceBrailleTable:(id)arg1 isDefault:(_Bool)arg2;	// IMP=0x00100000000f6c5b
- (id)adjustBrailleLanguageRotorInDirection:(long long)arg1 isDefault:(out _Bool *)arg2;	// IMP=0x00100000000f687b
- (void)_updateRealtimeElementStatus;	// IMP=0x00100000000f632f
- (void)_updateRealtimeElementStatusFromTimer;	// IMP=0x00100000000f62ec
- (void)updateRealtimeElements:(id)arg1;	// IMP=0x00100000000f62a9
- (void)_waitForBrailleClientConnection;	// IMP=0x00100000000f620e
- (void)_setBrailleClientEnabled:(id)arg1;	// IMP=0x00100000000f6063
- (void)_updateBrailleInputSettings;	// IMP=0x00100000000f5e1e
- (void)updateBrailleInputSettings;	// IMP=0x00100000000f5deb
- (void)updateBrailleOutputSettings;	// IMP=0x00100000000f5dbb
- (void)_updateBrailleOutputSettings;	// IMP=0x00100000000f5ca6
- (void)_textShortcutsDidChange;	// IMP=0x00100000000f5c67
- (void)textShortcutsDidChange;	// IMP=0x00100000000f5c38
- (void)dealloc;	// IMP=0x00100000000f5bca
- (id)init;	// IMP=0x00100000000f4e24

@end

