//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, VOTAppLauncher, VOTElement;
@protocol VOTGesturedTextInputManagerDelegate;

@interface VOTGesturedTextInputManager : NSObject
{
    _Bool _active;	// 8 = 0x8
    id <VOTGesturedTextInputManagerDelegate> _delegate;	// 16 = 0x10
    long long _rotorType;	// 24 = 0x18
    NSDictionary *_localizedWebRotorMap;	// 32 = 0x20
    VOTAppLauncher *_appLauncher;	// 40 = 0x28
    VOTElement *_appLauncherManitorElement;	// 48 = 0x30
    NSString *_currentInputString;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000062491
@property(copy, nonatomic) NSString *currentInputString; // @synthesize currentInputString=_currentInputString;
@property(retain, nonatomic) VOTElement *appLauncherManitorElement; // @synthesize appLauncherManitorElement=_appLauncherManitorElement;
@property(retain, nonatomic) VOTAppLauncher *appLauncher; // @synthesize appLauncher=_appLauncher;
@property(retain, nonatomic) NSDictionary *localizedWebRotorMap; // @synthesize localizedWebRotorMap=_localizedWebRotorMap;
@property(nonatomic) long long rotorType; // @synthesize rotorType=_rotorType;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(nonatomic) __weak id <VOTGesturedTextInputManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)appLauncher:(id)arg1 didLaunchAppOrNil:(id)arg2;	// IMP=0x0010000000062269
- (void)appLauncher:(id)arg1 didFilterApps:(id)arg2 didSwitchAppFocus:(id)arg3 withPrefix:(id)arg4;	// IMP=0x0010000000061f6a
- (unsigned long long)_numberOfCharactersToDeleteStartingAtIndex:(unsigned long long)arg1 toDesiredLength:(unsigned long long)arg2 fromString:(id)arg3;	// IMP=0x0010000000061e5b
- (unsigned long long)_numberOfCharactersToDeleteToDesiredLength:(unsigned long long)arg1 fromString:(id)arg2;	// IMP=0x0010000000061df0
- (void)_updateLocalizedResources;	// IMP=0x0010000000061b1e
- (_Bool)_processLaunchEvent:(id)arg1 forElement:(id)arg2;	// IMP=0x00100000000617e3
- (_Bool)_processRawInputEvent:(id)arg1 forElement:(id)arg2 withAttributes:(id)arg3;	// IMP=0x0010000000061530
- (_Bool)_performWordBackspaceForElement:(id)arg1;	// IMP=0x00100000000613c4
- (void)_deleteFromCurrentInputStringIfNeeded;	// IMP=0x00100000000612aa
- (_Bool)_processWebRotorEvent:(id)arg1;	// IMP=0x00100000000611bf
- (void)eventFactoryDidBeginSplitGesture:(id)arg1;	// IMP=0x00100000000611b9
- (id)hintForAppLaunch;	// IMP=0x00100000000611b1
- (_Bool)shouldAllowRotorEvents;	// IMP=0x00100000000611a9
- (void)didInputWordBackspace;	// IMP=0x00100000000611a3
- (void)didInputBackspace;	// IMP=0x001000000006119d
- (_Bool)performNextBrailleTableCommand;	// IMP=0x0010000000061195
- (_Bool)performNextKeyboardLanguage;	// IMP=0x001000000006118d
- (_Bool)performCustomWordBackspace;	// IMP=0x0010000000061185
- (_Bool)performCustomBackspace;	// IMP=0x001000000006117d
- (void)applyPreviousSuggestionToElement:(id)arg1;	// IMP=0x0010000000132eea
- (void)applyNextSuggestionToElement:(id)arg1;	// IMP=0x0010000000132ebf
- (_Bool)isNextBrailleTableEvent:(id)arg1;	// IMP=0x0010000000132e91
- (_Bool)isNextKeyboardLanguageEvent:(id)arg1;	// IMP=0x0010000000132e63
- (_Bool)isLaunchAppEvent:(id)arg1;	// IMP=0x0010000000132e35
- (_Bool)isPreviousSuggestionEvent:(id)arg1;	// IMP=0x0010000000132e07
- (_Bool)isNextSuggestionEvent:(id)arg1;	// IMP=0x0010000000132dd9
- (_Bool)isReturnKeyEvent:(id)arg1;	// IMP=0x0010000000132dab
- (_Bool)isWordBackspaceEvent:(id)arg1;	// IMP=0x0010000000132d7d
- (_Bool)isBackspaceEvent:(id)arg1;	// IMP=0x0010000000132d4f
- (_Bool)isSpaceEvent:(id)arg1;	// IMP=0x0010000000132d21
- (void)clearCurrentString;	// IMP=0x0010000000061164
- (id)currentString;	// IMP=0x0010000000061152
- (void)sendCarriageReturnForElement:(id)arg1;	// IMP=0x0010000000061121
- (void)pressReturnKeyForElement:(id)arg1;	// IMP=0x00100000000610f0
- (void)inputSpaceForElement:(id)arg1;	// IMP=0x0010000000061088
- (_Bool)processEvent:(id)arg1;	// IMP=0x0010000000060a28
- (id)currentElementAttributes;	// IMP=0x00100000000608bb
- (void)updateWithString:(id)arg1;	// IMP=0x001000000005ffd6
- (long long)valueChangeOriginator;	// IMP=0x0010000000132cf7
- (void)appendString:(id)arg1;	// IMP=0x001000000005ff2d
- (_Bool)processTapWithFingerCount:(unsigned long long)arg1;	// IMP=0x001000000005feb6
- (id)init;	// IMP=0x001000000005fe3c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

