//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableString, NSString, VOTBrailleManager;

@interface VOTTextSearchManager : NSObject
{
    NSMutableArray *_history;	// 8 = 0x8
    NSMutableString *_buffer;	// 16 = 0x10
    long long _bufferIndex;	// 24 = 0x18
    long long _historyIndex;	// 32 = 0x20
    _Bool _textSearchModeIsOn;	// 40 = 0x28
    VOTBrailleManager *_brailleManager;	// 48 = 0x30
}

+ (id)sharedManager;	// IMP=0x00400000001268cb
+ (void)initialize;	// IMP=0x0010000000126896
- (void).cxx_destruct;	// IMP=0x00200000001279d0
@property(readonly, nonatomic) _Bool textSearchModeIsOn; // @synthesize textSearchModeIsOn=_textSearchModeIsOn;
@property(retain, nonatomic) VOTBrailleManager *brailleManager; // @synthesize brailleManager=_brailleManager;
- (void)_updateBrailleWithBuffer;	// IMP=0x001000000012779f
- (void)handleReplaceRange:(struct _NSRange)arg1 withString:(id)arg2 cursor:(long long)arg3;	// IMP=0x00100000001276df
- (void)handleTextSearchEvent:(id)arg1;	// IMP=0x00100000001275ef
- (void)_handleLetter:(id)arg1;	// IMP=0x0010000000127280
- (void)_handleDelete:(id)arg1;	// IMP=0x0010000000126fbe
- (void)_handleArrowKey:(id)arg1;	// IMP=0x0010000000126f37
- (void)_handleUpDownMovement:(id)arg1;	// IMP=0x0010000000126def
- (void)_handleRightLeftMovement:(id)arg1;	// IMP=0x0010000000126b9b
@property(copy, nonatomic) NSString *currentSearchValue; // @dynamic currentSearchValue;
- (void)endTextSearchSession;	// IMP=0x0010000000126aea
- (void)beginNewTextSearchSession;	// IMP=0x0000000000126aa5
- (void)_syncSearchBufferHistory;	// IMP=0x0010000000126a07
- (id)init;	// IMP=0x00100000001268dc

@end

