//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData;

@interface MCProfileServiceProfileHandler
{
    struct __SecIdentity *_identity;	// 40 = 0x28
    NSData *_persistentID;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000006e11b
- (void)removeWithInstaller:(id)arg1 options:(id)arg2;	// IMP=0x001000000006e01a
- (void)unsetAside;	// IMP=0x001000000006df36
- (void)setAsideWithInstaller:(id)arg1;	// IMP=0x001000000006de52
- (void)didInstallOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x001000000006dbc6
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x001000000006d9dc
- (id)fetchFinalProfileWithClient:(id)arg1 outProfileData:(id *)arg2 outError:(id *)arg3;	// IMP=0x001000000006cbf0
- (void)_releaseDependencyBetweenPersistentID:(id)arg1 andUUID:(id)arg2 forSystem:(_Bool)arg3 user:(_Bool)arg4;	// IMP=0x001000000006cb19
- (void)_retainDependencyBetweenPersistentID:(id)arg1 andUUID:(id)arg2 forSystem:(_Bool)arg3 user:(_Bool)arg4;	// IMP=0x001000000006ca42
- (id)_badIdentityError;	// IMP=0x001000000006c9c1
- (void)dealloc;	// IMP=0x001000000006c97b
- (id)initWithProfile:(id)arg1;	// IMP=0x001000000006c8a8

@end

