//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MCMError, NSObject;
@protocol OS_xpc_object;

@protocol MCMXPCReply <NSObject>
@property(readonly, nonatomic) MCMError *error;
- (id)initWithError:(MCMError *)arg1;
- (_Bool)encodeReplyOntoXPCObject:(NSObject<OS_xpc_object> *)arg1;
@end

