//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSTimer;

@interface CRAlert : NSObject
{
    struct __CFUserNotification *_alert;	// 8 = 0x8
    _Bool _alertAutoDismissed;	// 16 = 0x10
    NSTimer *_alertDismissTimer;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000004479
@property(nonatomic) _Bool alertAutoDismissed; // @synthesize alertAutoDismissed=_alertAutoDismissed;
@property(retain, nonatomic) NSTimer *alertDismissTimer; // @synthesize alertDismissTimer=_alertDismissTimer;
- (_Bool)dismissAlert;	// IMP=0x001000000000442f
- (_Bool)presentAlertWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000000401e
- (id)_alertContents;	// IMP=0x0010000000003ce7
- (_Bool)_isDeviceUnlocked;	// IMP=0x0010000000003cdf
- (id)iconImagePath;	// IMP=0x0010000000003c63
- (id)alertOtherButtonTitle;	// IMP=0x0010000000003c5b
- (id)alertDeclineButtonTitle;	// IMP=0x0010000000003c53
- (id)alertAcceptButtonTitle;	// IMP=0x0010000000003c4b
- (id)alertMessage;	// IMP=0x0010000000003c43
- (id)alertTitle;	// IMP=0x0010000000003c3b
- (id)lockscreenMessage;	// IMP=0x0010000000003c33
- (id)lockscreenTitle;	// IMP=0x0010000000003c22
- (_Bool)requiresUnlockedDevice;	// IMP=0x0010000000003c1a
- (double)alertDismissal;	// IMP=0x0010000000003c11
- (_Bool)allowInCar;	// IMP=0x0010000000003c09
- (void)_setAlert:(struct __CFUserNotification *)arg1;	// IMP=0x0010000000003bd8

@end

