//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC11FlusherUtil13FlusherClient : NSObject
{
    MISSING_TYPE *connection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x004000000004d799
- (id)init;	// IMP=0x001000000004e5e1
- (void)dealloc;	// IMP=0x001000000004d77c

@end

