//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC10healthappd34DaemonBackgroundGenerationActivity : _TtCs12_SwiftObject
{
    MISSING_TYPE *identifier;	// 16 = 0x10
    MISSING_TYPE *healthExperienceStoreOracle;	// 32 = 0x20
    MISSING_TYPE *feedPopulationManagerOracle;	// 40 = 0x28
    MISSING_TYPE *longRunningProcessOracle;	// 48 = 0x30
    MISSING_TYPE *countryOracle;	// 56 = 0x38
}

- (void)debuggingInfoRequestedWithNote:(id)arg1;	// IMP=0x00200000000056d0

@end

