//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CARLeafIcon, NSLayoutConstraint, NSString, UIImageView;
@protocol CARIconProviding;

@interface CARAppDockButton
{
    _Bool _active;	// 8 = 0x8
    _Bool _showBadge;	// 9 = 0x9
    NSString *_bundleIdentifier;	// 16 = 0x10
    UIImageView *_iconImageView;	// 24 = 0x18
    UIImageView *_iconFocusRingImageView;	// 32 = 0x20
    UIImageView *_iconFocusRingUnreadImageView;	// 40 = 0x28
    id <CARIconProviding> _iconProvider;	// 48 = 0x30
    CARLeafIcon *_icon;	// 56 = 0x38
    UIImageView *_badgeView;	// 64 = 0x40
    NSLayoutConstraint *_iconFocusRingUnreadImageViewCenterConstraint;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x00200000000b129b
@property(retain, nonatomic) NSLayoutConstraint *iconFocusRingUnreadImageViewCenterConstraint; // @synthesize iconFocusRingUnreadImageViewCenterConstraint=_iconFocusRingUnreadImageViewCenterConstraint;
@property(nonatomic) _Bool showBadge; // @synthesize showBadge=_showBadge;
@property(retain, nonatomic) UIImageView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) CARLeafIcon *icon; // @synthesize icon=_icon;
@property(nonatomic) __weak id <CARIconProviding> iconProvider; // @synthesize iconProvider=_iconProvider;
@property(retain, nonatomic) UIImageView *iconFocusRingUnreadImageView; // @synthesize iconFocusRingUnreadImageView=_iconFocusRingUnreadImageView;
@property(retain, nonatomic) UIImageView *iconFocusRingImageView; // @synthesize iconFocusRingImageView=_iconFocusRingImageView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000b0fa3
- (void)setBundleIdentifier:(id)arg1 animated:(_Bool)arg2;	// IMP=0x00100000000b0dad
- (void)_updateImageForBundleIdentifier:(_Bool)arg1 crossfade:(_Bool)arg2;	// IMP=0x00100000000b0094
- (void)iconAccessoriesDidUpdate:(id)arg1;	// IMP=0x00100000000afe6a
- (void)iconImageDidUpdate:(id)arg1;	// IMP=0x00100000000afe4e
- (void)setShowBadge:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00100000000afd41
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00100000000afd1b
- (void)_updateFocusRings;	// IMP=0x00100000000afc5d
- (_Bool)canBecomeFocused;	// IMP=0x00100000000afc48
- (void)setBadgeHidden:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00100000000af831
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00100000000af7f0
- (void)_setupImagesIfNecessary;	// IMP=0x00100000000af52a
- (void)_updateCenterXConstraintConstant;	// IMP=0x00100000000af48a
- (void)setFocusHighlightColor:(id)arg1;	// IMP=0x00100000000af3c4
- (id)initWithIconProvider:(id)arg1;	// IMP=0x00100000000ae9d0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

