//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CARDateFormatter : NSObject
{
}

+ (id)_formatIntervalFromDate:(id)arg1 toDate:(id)arg2 withToken:(id)arg3;	// IMP=0x002000000003d62e
+ (id)formattedRangeTimestamp:(id)arg1;	// IMP=0x001000000003d588
+ (id)formattedRangeDateTimestamp:(id)arg1;	// IMP=0x001000000003d4e2
+ (id)formattedRange:(id)arg1;	// IMP=0x001000000003d43c
+ (id)formattedRangeTimestampStart:(id)arg1 end:(id)arg2;	// IMP=0x001000000003d360
+ (id)formattedRangeDateTimeStampStart:(id)arg1 end:(id)arg2;	// IMP=0x001000000003d284
+ (id)formattedRangeStart:(id)arg1 end:(id)arg2;	// IMP=0x001000000003d1a8
+ (id)_formatDate:(id)arg1 withToken:(id)arg2;	// IMP=0x001000000003d019
+ (id)formattedTimeStamp:(id)arg1;	// IMP=0x001000000003cf62
+ (id)formattedTime:(id)arg1;	// IMP=0x001000000003ceab
+ (id)formattedDateTimeStamp:(id)arg1;	// IMP=0x001000000003cdf4
+ (id)formattedDate:(id)arg1;	// IMP=0x001000000003cd3a
+ (id)formattedNow;	// IMP=0x001000000003ccd4
+ (id)_dateIntervalFormatterFromToken:(id)arg1;	// IMP=0x001000000003cbbc
+ (id)dateIntervalFormatterForToken:(id)arg1;	// IMP=0x001000000003ca96
+ (id)dateIntervalFormatters;	// IMP=0x001000000003ca41
+ (id)_dateFormatterFromToken:(id)arg1;	// IMP=0x001000000003c929
+ (id)dateFormatterForToken:(id)arg1;	// IMP=0x001000000003c803
+ (id)dateFormatters;	// IMP=0x001000000003c7ae

@end

