//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIImage, UIImageView;

@interface CARStatusBarHomeButton
{
    unsigned long long _displayState;	// 8 = 0x8
    UIImage *_iconsImage;	// 16 = 0x10
    UIImage *_dashboardImage;	// 24 = 0x18
    UIImageView *_focusRingImageView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000132df
@property(retain, nonatomic) UIImageView *focusRingImageView; // @synthesize focusRingImageView=_focusRingImageView;
@property(retain, nonatomic) UIImage *dashboardImage; // @synthesize dashboardImage=_dashboardImage;
@property(retain, nonatomic) UIImage *iconsImage; // @synthesize iconsImage=_iconsImage;
@property(nonatomic) unsigned long long displayState; // @synthesize displayState=_displayState;
- (void)_installSelectGestureRecognizer;	// IMP=0x0010000000013259
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000001316b
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000001307d
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x001000000001303a
- (void)_updateDisplayState:(_Bool)arg1;	// IMP=0x0010000000012e4a
- (void)_setupImagesIfNecessary;	// IMP=0x0010000000012bf0
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0010000000012baf
- (void)setFocusHighlightColor:(id)arg1;	// IMP=0x0010000000012b1b
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000001278b

@end

