//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CPLCloudKitFakeDynamicDerivatives : NSObject
{
}

+ (id)transformData:(id)arg1 fileType:(id)arg2 matchingResource:(id)arg3 error:(id *)arg4;	// IMP=0x00200000000963a4
+ (_Bool)transformFromURL:(id)arg1 fileType:(id)arg2 toTargetURL:(id)arg3 matchingResource:(id)arg4 error:(id *)arg5;	// IMP=0x0010000000096117
+ (_Bool)_transferImageFromSource:(struct CGImageSource *)arg1 toDestination:(struct CGImageDestination *)arg2 matchingResource:(id)arg3;	// IMP=0x00100000000960bc
+ (id)_outputOptionsFromSource:(struct CGImageSource *)arg1 matchingResource:(id)arg2;	// IMP=0x0010000000095f05
+ (id)_metadataWithoutOrientation:(id)arg1;	// IMP=0x0010000000095e1b
+ (unsigned long long)realResourceTypeForResource:(id)arg1;	// IMP=0x0010000000095d79
+ (_Bool)isFakeDerivative:(id)arg1;	// IMP=0x0010000000095cf4
+ (id)overriddenResourcesFromResources:(id)arg1;	// IMP=0x00100000000959a2
+ (_Bool)usesFakeDerivatives;	// IMP=0x0010000000095996
+ (void)setAllowsFakeDerivatives:(_Bool)arg1;	// IMP=0x0010000000095535
+ (id)fakeDerivativesDescription;	// IMP=0x001000000009531d
+ (_Bool)allowsFakeDerivatives;	// IMP=0x0010000000095311

@end

