//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MIInstallableParallelPlaceholder
{
}

- (_Bool)performInstallationWithError:(id *)arg1;	// IMP=0x0040000000009d5c
- (_Bool)shouldModifyExistingContainers;	// IMP=0x0010000000009d54

@end

