//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <EmailDaemon/EDDaemonInterfaceFactory.h>

@class EDFetchController;

@interface DaemonInterfaceFactory : EDDaemonInterfaceFactory
{
    EDFetchController *_sharedFetchController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000186e7
- (id)newOutgoingMessageRepository;	// IMP=0x00100000000185cd
- (id)newFetchController;	// IMP=0x00100000000185b7
- (id)initWithPersistence:(id)arg1 categorySubsystem:(id)arg2 sharedFetchController:(id)arg3;	// IMP=0x0010000000018521

@end

