//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MFMailboxUid, NSString;

@interface MFDFetch
{
    CDUnknownBlockType _completionAfterFetchCompleted;	// 8 = 0x8
    MFMailboxUid *_waitingForMailbox;	// 16 = 0x10
}

+ (id)exportedInterface;	// IMP=0x0020000000072c18
- (void).cxx_destruct;	// IMP=0x0020000000073a48
- (void)fetchMessagesForMailboxWithName:(id)arg1 options:(long long)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000734cb
- (void)_autoFetchCompleted:(id)arg1;	// IMP=0x00100000000732d2
- (void)_waitForFetchCompletedForMailbox:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000007319a
- (_Bool)_isWaitingForMailboxFetch;	// IMP=0x0010000000073185
- (id)_findMailboxWithName:(id)arg1 inAccounts:(id)arg2;	// IMP=0x0010000000072f67
- (id)_mailboxWithName:(id)arg1 forAccount:(id)arg2;	// IMP=0x0010000000072e78
- (void)dealloc;	// IMP=0x0010000000072d20
- (id)initWithClient:(id)arg1;	// IMP=0x0010000000072c38

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

