//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSSet;

@interface MFMailAccountsProviderState : NSObject
{
    unsigned long long _numberOfActiveAccounts;	// 8 = 0x8
    unsigned long long _numberOfInactiveAccounts;	// 16 = 0x10
    NSSet *_displayedAccountsIdentifiers;	// 24 = 0x18
    NSArray *_mailAccounts;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000083996
@property(readonly, copy, nonatomic) NSArray *mailAccounts; // @synthesize mailAccounts=_mailAccounts;
@property(readonly, copy, nonatomic) NSSet *displayedAccountsIdentifiers; // @synthesize displayedAccountsIdentifiers=_displayedAccountsIdentifiers;
@property(readonly, nonatomic) unsigned long long numberOfInactiveAccounts; // @synthesize numberOfInactiveAccounts=_numberOfInactiveAccounts;
@property(readonly, nonatomic) unsigned long long numberOfActiveAccounts; // @synthesize numberOfActiveAccounts=_numberOfActiveAccounts;
- (id)initFromProvider:(id)arg1;	// IMP=0x0010000000083822

@end

