//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MFAttachmentManager, MFLibraryMessage;

@interface MFMessageResultsGenerator
{
    void *_addressBook;	// 8 = 0x8
    _Bool _shouldDownload;	// 16 = 0x10
    MFAttachmentManager *_attachmentManager;	// 24 = 0x18
    MFLibraryMessage *_message;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000090e1c
@property(retain, nonatomic) MFLibraryMessage *message; // @synthesize message=_message;
@property(retain, nonatomic) MFAttachmentManager *attachmentManager; // @synthesize attachmentManager=_attachmentManager;
- (id)_headerValueForKey:(id)arg1;	// IMP=0x0010000000090bf8
- (id)_headerData:(id)arg1;	// IMP=0x0010000000090b4c
- (id)_bestAlternativePart:(id)arg1;	// IMP=0x0010000000090b1f
- (id)_rfc822Data:(id)arg1;	// IMP=0x00100000000909c7
- (id)_attachmentValueForKey:(id)arg1;	// IMP=0x001000000008fe18
- (CDUnknownBlockType)_testForAttachmentLimiterType:(id)arg1;	// IMP=0x001000000008fd80
- (id)_knownAttachmentLimiterTests;	// IMP=0x001000000008fc0e
- (id)_suppressionContexts:(id)arg1;	// IMP=0x001000000008f924
- (id)_mailboxType:(id)arg1;	// IMP=0x001000000008f895
- (id)_outgoing:(id)arg1;	// IMP=0x001000000008f805
- (id)_isLocalDraft:(id)arg1;	// IMP=0x001000000008f715
- (id)_status:(id)arg1;	// IMP=0x001000000008f5f5
- (id)_dateReceived:(id)arg1;	// IMP=0x001000000008f5c8
- (id)_dateSent:(id)arg1;	// IMP=0x001000000008f59b
- (id)_receivingAddresses:(id)arg1;	// IMP=0x001000000008f52c
- (id)_recipientTo:(id)arg1;	// IMP=0x001000000008f4ae
- (id)_recipientCc:(id)arg1;	// IMP=0x001000000008f430
- (id)_recipientBcc:(id)arg1;	// IMP=0x001000000008f3b2
- (id)_sender:(id)arg1;	// IMP=0x001000000008f334
- (id)_convertEmailAddresses:(id)arg1;	// IMP=0x001000000008f0d1
- (id)_convertEmailAddress:(id)arg1;	// IMP=0x001000000008ef67
- (void *)_addressBook;	// IMP=0x001000000008ef3b
- (id)_copyPredictiveModelSummaryForMessage:(id)arg1 downloadIfNecessary:(_Bool)arg2;	// IMP=0x001000000008e7d5
- (id)_defaultAttachmentManager;	// IMP=0x001000000008e76a
- (id)_predictiveModelSummary:(id)arg1;	// IMP=0x001000000008e73a
- (id)_bodySummary:(id)arg1;	// IMP=0x001000000008e6dc
- (id)_subject:(id)arg1;	// IMP=0x001000000008e66d
- (id)_messageIDHash:(id)arg1;	// IMP=0x001000000008e5e7
- (id)_mailboxURL:(id)arg1;	// IMP=0x001000000008e578
- (id)_accountReference:(id)arg1;	// IMP=0x001000000008e509
- (id)_conversationReference:(id)arg1;	// IMP=0x001000000008e49a
- (id)_publisherBulletinID:(id)arg1;	// IMP=0x001000000008e3d2
- (id)_localMessageReference:(id)arg1;	// IMP=0x001000000008e363
- (id)_messageReference:(id)arg1;	// IMP=0x001000000008e2c6
- (id)_messageLibraryID:(id)arg1;	// IMP=0x001000000008e278
- (CDUnknownBlockType)blockForKey:(id)arg1;	// IMP=0x001000000008da57
- (void)dealloc;	// IMP=0x001000000008d9df
- (id)initWithKeys:(id)arg1 downloadIfNecessary:(_Bool)arg2;	// IMP=0x001000000008d97f

@end

