//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MFNanoServerMessageFetchService : NSObject
{
}

- (id)_criterionForFilterType:(unsigned long long)arg1;	// IMP=0x00400000000aa930
- (id)_filterTypeCriterionForMailbox:(id)arg1;	// IMP=0x00100000000aa6a7
- (id)criterionForMailboxUrl:(id)arg1;	// IMP=0x00100000000aa317
- (id)_criterionForMessagesFromMailbox:(id)arg1 param:(id)arg2;	// IMP=0x00100000000a9e7d
- (id)_criterionForMessagesFromMailboxes:(id)arg1 param:(id)arg2;	// IMP=0x00100000000a9c16
- (id)messagesForMailboxes:(id)arg1 param:(id)arg2;	// IMP=0x00100000000a9af3

@end

