//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class EFProcessTransaction, NSString, UMUserSyncTask;

@interface MFUserSyncStakeholder : NSObject
{
    _Bool _runningInSyncBubble;	// 8 = 0x8
    EFProcessTransaction *_transaction;	// 16 = 0x10
    UMUserSyncTask *_task;	// 24 = 0x18
    _Bool _exitWhenDone;	// 32 = 0x20
}

+ (id)sharedStakeholder;	// IMP=0x00200000000c40e9
- (void).cxx_destruct;	// IMP=0x00200000000c48ae
- (void)_processingDidFinish:(id)arg1;	// IMP=0x00100000000c4835
- (void)_processingDidStart:(id)arg1;	// IMP=0x00100000000c47f5
- (void)_networkConfigurationChanged:(id)arg1;	// IMP=0x00100000000c46ef
- (void)processQueueAndExit;	// IMP=0x00100000000c4669
- (void)printDeliveryQueue;	// IMP=0x00100000000c45e0
- (void)willSwitchUser;	// IMP=0x00100000000c44ee
- (void)uploadContent;	// IMP=0x00100000000c42c1
- (void)endTask;	// IMP=0x00100000000c428f
- (void)createAndStartTask;	// IMP=0x00100000000c419f
- (id)init;	// IMP=0x00100000000c3ec0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

