//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class PDURLSessionProxyResponse, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyGetAuthHeaders : PBCodable
{
    PDURLSessionProxyResponse *_response;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000000000dd91
@property(retain, nonatomic) PDURLSessionProxyResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000000dcb6
- (unsigned long long)hash;	// IMP=0x001000000000dc69
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000dba1
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000db03
- (void)copyTo:(id)arg1;	// IMP=0x001000000000daa0
- (void)writeTo:(id)arg1;	// IMP=0x001000000000da43
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000000d848
- (id)dictionaryRepresentation;	// IMP=0x001000000000d773
- (id)description;	// IMP=0x001000000000d6c4
@property(readonly, nonatomic) _Bool hasResponse;
@property(readonly, nonatomic) _Bool hasTask;

@end

