//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TLDMobileAssetManager : NSObject
{
    unsigned long long _installedAssetVersion;	// 8 = 0x8
}

@property unsigned long long installedAssetVersion; // @synthesize installedAssetVersion=_installedAssetVersion;
- (void)moveInstalledAsset:(id)arg1 withVersion:(unsigned long long)arg2;	// IMP=0x001000000003c3a4
- (void)moveFileAtomicallyAndCheckIntegrity:(id)arg1 toLocation:(id)arg2;	// IMP=0x001000000003c04f
- (void)downloadAsset:(id)arg1;	// IMP=0x001000000003befa
- (void)findBestAssetFrom:(id)arg1;	// IMP=0x001000000003b6bb
- (void)queryAndFindBestAsset;	// IMP=0x001000000003b4ad

@end

