//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AccountEventEntity
{
}

+ (Class)memoryEntityClass;	// IMP=0x00400000000d4dbe
+ (id)defaultProperties;	// IMP=0x00100000000d4d15
+ (id)databaseTable;	// IMP=0x00100000000d4d08

@end

