//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AssetPromise, InAppDownloadStatus, InAppDownloadTimeEstimator, NSDictionary, NSNumber, NSString, NSTimer;

@interface InAppDownloadTask
{
    AssetPromise *_assetPromise;	// 8 = 0x8
    NSDictionary *_downloadInfo;	// 16 = 0x10
    NSString *_downloadPath;	// 24 = 0x18
    NSString *_installPath;	// 32 = 0x20
    NSTimer *_statusTimer;	// 40 = 0x28
    InAppDownloadStatus *_pendingDownloadStatus;	// 48 = 0x30
    InAppDownloadTimeEstimator *_timeEstimator;	// 56 = 0x38
    _Bool _paused;	// 64 = 0x40
    struct _BOMCopier *_copier;	// 72 = 0x48
    unsigned long long _expectedInstallSize;	// 80 = 0x50
    unsigned long long _totalInstalledSize;	// 88 = 0x58
    NSNumber *_downloadID;	// 96 = 0x60
    CDUnknownBlockType _statusBlock;	// 104 = 0x68
    InAppDownloadStatus *_status;	// 112 = 0x70
    NSString *_bundleID;	// 120 = 0x78
}

- (void).cxx_destruct;	// IMP=0x00200000001951d1
@property(retain, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(retain, nonatomic) InAppDownloadStatus *status; // @synthesize status=_status;
@property(copy, nonatomic) CDUnknownBlockType statusBlock; // @synthesize statusBlock=_statusBlock;
@property(copy, nonatomic) NSNumber *downloadID; // @synthesize downloadID=_downloadID;
- (id)_bomInstallFromPath:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000194a83
- (void)_bomInstall;	// IMP=0x001000000019447b
- (void)_updateDownloadStatus:(id)arg1;	// IMP=0x00100000001943f4
- (void)_sendDownloadStatus;	// IMP=0x0010000000194333
- (void)_install;	// IMP=0x0010000000194321
- (void)_finalizeTaskWithError:(id)arg1;	// IMP=0x0010000000194000
- (void)_downloadedBytes:(long long)arg1 expectedBytes:(long long)arg2;	// IMP=0x0010000000193ef9
- (void)pause;	// IMP=0x0010000000193dd5
- (void)cancel;	// IMP=0x0010000000193c2f
- (void)main;	// IMP=0x0010000000192fcf
- (id)initWithDownloadID:(id)arg1 info:(id)arg2 client:(id)arg3;	// IMP=0x0010000000192e73

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

