//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface MigratorConfigurationStore : NSObject
{
    NSMutableDictionary *_configuration;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000b951d
- (id)_writeConfigurationToUserDefaultsRepresentation:(id)arg1;	// IMP=0x00100000000b9403
- (id)_readConfigurationFromUserDefaultsRepresentation:(id)arg1;	// IMP=0x00100000000b9202
- (void)writeConfiguration:(id)arg1;	// IMP=0x00100000000b9195
- (void)willBeginMigratorType:(id)arg1;	// IMP=0x00100000000b9139
- (void)synchronize:(_Bool)arg1;	// IMP=0x00100000000b8fb7
- (_Bool)hasMigrations;	// IMP=0x00100000000b8f9a
- (id)migrationsLeft;	// IMP=0x00100000000b8e2f
- (void)enumerateUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000b8d32
- (void)didCompleteMigratorType:(id)arg1;	// IMP=0x00100000000b8cfb
- (void)clearMigrations;	// IMP=0x00100000000b8ce2
- (id)init;	// IMP=0x00100000000b8c1a

@end

