//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSRecursiveLock, UnfairLock;
@protocol OS_dispatch_source;

@interface ODRManager : NSObject
{
    NSMutableDictionary *_applicationMapping;	// 8 = 0x8
    UnfairLock *_applicationMappingLock;	// 16 = 0x10
    NSRecursiveLock *_resourcesLock;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_lowDisk;	// 32 = 0x20
}

+ (_Bool)isAppRunning:(id)arg1;	// IMP=0x0040000000062e73
+ (long long)_availableSpaceCushion;	// IMP=0x0010000000061aba
+ (long long)_availableSpaceOnDeviceRootVolume;	// IMP=0x0010000000061a0b
+ (void)initialize;	// IMP=0x00100000000618d5
+ (id)defaultManager;	// IMP=0x0010000000061848
- (void).cxx_destruct;	// IMP=0x0020000000064340
- (void)_enumerateAllPurgeableAssetPacksUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000006426a
- (void)_enumerateAllNonRunningAppAssetsLastUsedLaterThan:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000063e62
- (id)_currentDownloadStatus;	// IMP=0x0010000000063669
- (id)status;	// IMP=0x0010000000063579
- (void)purgeAssetWithIdentifier:(id)arg1 forReason:(long long)arg2;	// IMP=0x00100000000632d9
- (void)purgeAllAssetsForApplication:(id)arg1 forReason:(long long)arg2;	// IMP=0x0010000000062fce
- (long long)purgeBytes:(long long)arg1 odrOnly:(_Bool)arg2;	// IMP=0x0010000000062e6b
- (void)performResourceAccessBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000062ddc
- (void)performResourceAccessBlock:(CDUnknownBlockType)arg1 forApplicationBundleID:(id)arg2;	// IMP=0x0010000000062bc3
- (void)handleInstalledApplication:(id)arg1;	// IMP=0x00100000000626eb
- (_Bool)expireAssetURLsForBundleIDs:(id)arg1;	// IMP=0x0010000000061d9d
- (_Bool)checkAndRequestRequiredSpaceForRequest:(long long)arg1;	// IMP=0x0010000000061b0c
- (id)init;	// IMP=0x0010000000061953

@end

