//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSURL;
@protocol OS_dispatch_source;

@interface RequestThrottlePersistence : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    NSURL *_url;	// 16 = 0x10
    NSMutableDictionary *_records;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_timer;	// 32 = 0x20
}

+ (_Bool)_writeRecords:(id)arg1 toURL:(id)arg2 error:(id *)arg3;	// IMP=0x00400000001cddf2
+ (id)_readRecordsFromURL:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001cdd1c
+ (_Bool)_deleteRecordsAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001cdc9b
- (void).cxx_destruct;	// IMP=0x00200000001ce64a
- (void)_writeRecords;	// IMP=0x00100000001ce49e
- (void)_readRecords;	// IMP=0x00100000001ce140
- (void)_deleteRecords;	// IMP=0x00100000001cdffe
- (void)_dirtyRecords;	// IMP=0x00100000001cde80
- (void)filterRecordsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001cdadd
- (id)fetchRecordForItemID:(id)arg1;	// IMP=0x00100000001cda68
- (void)deleteRecords;	// IMP=0x00100000001cda1b
- (_Bool)deleteRecordForItemID:(id)arg1;	// IMP=0x00100000001cd979
- (void)addRecord:(id)arg1;	// IMP=0x00100000001cd8b8
- (id)initWithURL:(id)arg1;	// IMP=0x00100000001cd836
- (id)initWithPath:(id)arg1;	// IMP=0x00100000001cd7dc

@end

