//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppleMediaServices/AMSURLRequestEncoder.h>

@interface SwitchAppOwnerURLRequestEncoder : AMSURLRequestEncoder
{
}

- (id)requestByEncodingRequest:(id)arg1 parameters:(id)arg2;	// IMP=0x004000000025ae72
- (id)initWithBag:(id)arg1;	// IMP=0x001000000025ae21

@end

