//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AMSProcessInfo, NSString, NSUUID, XPCServiceClient;
@protocol OS_voucher, XPCNotificationClient;

@interface XPCRequestToken : NSObject
{
    NSString *_transactionID;	// 8 = 0x8
    _Bool _internal;	// 16 = 0x10
    NSUUID *_externalID;	// 24 = 0x18
    NSString *_logUUID;	// 32 = 0x20
    AMSProcessInfo *_processInfo;	// 40 = 0x28
    XPCServiceClient *_serviceClient;	// 48 = 0x30
    NSObject<OS_voucher> *_voucher;	// 56 = 0x38
}

+ (id)internalRequestTokenWithProcessInfo:(id)arg1;	// IMP=0x0040000000284174
+ (id)internalRequestToken;	// IMP=0x0010000000284149
+ (id)currentRequestTokenWithProcessInfo:(id)arg1;	// IMP=0x00100000002840c1
+ (id)currentRequestToken;	// IMP=0x001000000028405a
- (void).cxx_destruct;	// IMP=0x0020000000284514
@property(readonly, getter=isInternal) _Bool internal; // @synthesize internal=_internal;
@property(readonly) NSObject<OS_voucher> *voucher; // @synthesize voucher=_voucher;
@property(readonly) XPCServiceClient *serviceClient; // @synthesize serviceClient=_serviceClient;
@property(readonly) AMSProcessInfo *processInfo; // @synthesize processInfo=_processInfo;
@property(readonly) NSString *logUUID; // @synthesize logUUID=_logUUID;
@property(readonly) NSUUID *externalID; // @synthesize externalID=_externalID;
- (id)description;	// IMP=0x001000000028447c
@property(readonly) id <XPCNotificationClient> notificationClient;
- (void)dealloc;	// IMP=0x0010000000284425
- (id)_initWithServiceClient:(id)arg1 processInfo:(id)arg2;	// IMP=0x0010000000284256
- (id)_initWithServiceClient:(id)arg1;	// IMP=0x00100000002841c3

@end

