//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CARSessionStatus, GEOCompanionRouteContext, GEOCompanionRouteDetails, GEOCompanionRouteStatus, GEOCompanionRouteUpdate, MNCompanionNavigationAdapter, MapsDistanceUnitUpdater, NSLock, NSString, NavigationSettingsMonitor;

__attribute__((visibility("hidden")))
@interface NMCNavigationProxy : NSObject
{
    _Bool _activeDeviceSupportsNavigation;	// 8 = 0x8
    _Bool _activeDeviceNeedsUnpackedPointsRemoved;	// 9 = 0x9
    _Bool _sendAllUpdates;	// 10 = 0xa
    _Bool _isNavigating;	// 11 = 0xb
    NSLock *_routeLock;	// 16 = 0x10
    GEOCompanionRouteDetails *_companionRouteDetails;	// 24 = 0x18
    GEOCompanionRouteStatus *_companionRouteStatus;	// 32 = 0x20
    GEOCompanionRouteStatus *_lastSentCompanionRouteStatus;	// 40 = 0x28
    GEOCompanionRouteUpdate *_companionRouteUpdate;	// 48 = 0x30
    GEOCompanionRouteContext *_companionRouteContext;	// 56 = 0x38
    MNCompanionNavigationAdapter *_adapter;	// 64 = 0x40
    MapsDistanceUnitUpdater *_distanceUnitUpdater;	// 72 = 0x48
    NavigationSettingsMonitor *_settingsMonitor;	// 80 = 0x50
    CARSessionStatus *_carSessionStatus;	// 88 = 0x58
}

+ (id)sharedInstance;	// IMP=0x0020000000005558
- (void).cxx_destruct;	// IMP=0x002000000000965b
- (void)sessionDidDisconnect:(id)arg1;	// IMP=0x0010000000009542
- (void)sessionDidConnect:(id)arg1;	// IMP=0x0010000000009429
- (_Bool)_isCarPlayConnected;	// IMP=0x00100000000093f2
- (void)_legacy_sendPreviewRouteDetails:(id)arg1 context:(id)arg2;	// IMP=0x0010000000009209
- (void)_sendRouteUpdate:(id)arg1 routeContext:(id)arg2;	// IMP=0x001000000000906e
- (_Bool)_shouldSendRouteStatus:(id)arg1 previousRouteStatus:(id)arg2;	// IMP=0x0010000000008cdc
- (void)_sendRouteStatus:(id)arg1 routeContext:(id)arg2;	// IMP=0x0010000000008af2
- (void)_sendRouteDetails:(id)arg1 routeStatus:(id)arg2 routeContext:(id)arg3;	// IMP=0x0010000000008793
- (void)_cleanupNavigation;	// IMP=0x00100000000086b3
- (void)_setupForNavigationWithRouteID:(id)arg1 context:(id)arg2;	// IMP=0x0010000000008425
- (void)_updateNavigationRouteDetails:(id)arg1 routeStatus:(id)arg2 routeUpdated:(_Bool)arg3;	// IMP=0x0010000000008103
- (void)updateNavigationRouteWithUpdate:(id)arg1;	// IMP=0x0010000000008060
- (void)updateNavigationRouteStatus:(id)arg1;	// IMP=0x0010000000008046
- (void)updateNavigationRouteDetails:(id)arg1 routeStatus:(id)arg2;	// IMP=0x001000000000802e
- (void)_openOrCloseNavigationService;	// IMP=0x0010000000007de1
- (void)_updateForActiveDevice;	// IMP=0x0010000000007c14
- (void)connectionNeedsStateSynchronization:(id)arg1;	// IMP=0x0010000000007c02
- (void)connection:(id)arg1 didChangeDeviceNearby:(_Bool)arg2;	// IMP=0x0010000000007bf0
- (void)_handleMessage:(id)arg1;	// IMP=0x00100000000068fb
- (void)_registerMessageObservers;	// IMP=0x001000000000654e
- (void)stopNavigation;	// IMP=0x00100000000064a8
- (void)_launchMapsForNavigation;	// IMP=0x001000000000611e
- (_Bool)_prepareToStartNavigationWithStartDetails:(id)arg1;	// IMP=0x0010000000005e38
- (void)startNavigationWithDetails:(id)arg1;	// IMP=0x0010000000005cef
- (void)startNavigationWithRouteID:(id)arg1 routeIndex:(unsigned long long)arg2 companionRouteContext:(id)arg3;	// IMP=0x00100000000058bc
- (void)dealloc;	// IMP=0x0010000000005839
- (id)init;	// IMP=0x00100000000055e9

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

