//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface BMSyncStreamID : NSObject
{
    NSString *_path;	// 8 = 0x8
    NSString *_name;	// 16 = 0x10
    unsigned long long _type;	// 24 = 0x18
}

+ (id)identifierFromDescriptor:(id)arg1;	// IMP=0x0020000000021457
+ (id)identifierForRestrictedStreamNamed:(id)arg1;	// IMP=0x001000000002134b
+ (id)identifierForPublicStreamNamed:(id)arg1;	// IMP=0x00100000000211ae
- (void).cxx_destruct;	// IMP=0x002000000002183d
// Error: Property attributes should begin with the type ('T') attribute, property name: type
// Property attributes: (null)

@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000002181e
- (id)description;	// IMP=0x00100000000217c4
@property(readonly, nonatomic) NSString *descriptor;
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000216e2
- (unsigned long long)hash;	// IMP=0x001000000002166f
- (id)config;	// IMP=0x00100000000215fc
@property(readonly, nonatomic) NSString *path;

@end

