//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIButton.h>

@class UIView, UIVisualEffectView;

@interface CARWallpaperPreviewButton : UIButton
{
    UIView *_platterView;	// 8 = 0x8
    UIVisualEffectView *_darkMaterial;	// 16 = 0x10
    UIVisualEffectView *_lightMaterial;	// 24 = 0x18
    UIView *_focusHighlightView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000177d3
@property(retain, nonatomic) UIView *focusHighlightView; // @synthesize focusHighlightView=_focusHighlightView;
@property(retain, nonatomic) UIVisualEffectView *lightMaterial; // @synthesize lightMaterial=_lightMaterial;
@property(retain, nonatomic) UIVisualEffectView *darkMaterial; // @synthesize darkMaterial=_darkMaterial;
@property(retain, nonatomic) UIView *platterView; // @synthesize platterView=_platterView;
- (void)_updateMaterialForInterfaceStyle:(long long)arg1;	// IMP=0x0010000000017560
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00100000000174e2
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x001000000001746a
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x00100000000173ec
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000016502

@end

