//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLCorrectiveCompensatedLocationProviderAdapter
{
}

+ (id)getSilo;	// IMP=0x002000000031aeb1
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000031ae98
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x001000000031ae3b
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x002000000031b09c
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x001000000031b06f
- (void);	// IMP=0x001000000031b047
- (void *)adaptee;	// IMP=0x001000000031b014
- (void)endService;	// IMP=0x001000000031aff9
- (void)beginService;	// IMP=0x001000000031af4a
- (id)init;	// IMP=0x001000000031af0d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

