//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class CKContainer, CKRecordZoneID, CKSyncEngine, CLTimer, MISSING_TYPE, NSString;

@interface CLVO2MaxCloudKitManager : CLIntersiloService
{
    struct shared_ptr<CLVO2MaxInputCache> fInputCache;	// 8 = 0x8
    struct shared_ptr<CLVO2MaxInputStore> fInputStore;	// 24 = 0x18
    struct unique_ptr<CLVO2MaxStagingOutputStore, std::default_delete<CLVO2MaxStagingOutputStore>> fStagingOutputStore;	// 40 = 0x28
    struct unique_ptr<CLVO2MaxRetrocomputeRecorderDb, std::default_delete<CLVO2MaxRetrocomputeRecorderDb>> fRetrocomputeDb;	// 48 = 0x30
    _Bool fFetchChangesForInputZone;	// 56 = 0x38
    struct unique_ptr<CLDataProtectionManager_Type::Client, std::default_delete<CLDataProtectionManager_Type::Client>> fDataProtectionClient;	// 64 = 0x40
    _Bool fDeviceUnlocked;	// 72 = 0x48
    int fMaxSessionsForUploadThrottling;	// 76 = 0x4c
    double fMinTimeBetweenForcedFetches;	// 80 = 0x50
    CKRecordZoneID *fOutputZoneID;	// 88 = 0x58
    CKRecordZoneID *fInputZoneID;	// 96 = 0x60
    struct CLVO2MaxCloudKitStats fDailyStats;	// 104 = 0x68
    CLTimer *fDailyStatsTimer;	// 168 = 0xa8
    double fDailyStatsTimerInterval;	// 176 = 0xb0
    double fDailyStatsStartTime;	// 184 = 0xb8
    CKContainer *_container;	// 192 = 0xc0
    CKSyncEngine *_syncEngine;	// 200 = 0xc8
}

+ (_Bool)isSupported;	// IMP=0x0020000000102def
+ (id)getSilo;	// IMP=0x0010000000102d56
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0010000000102d3d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000102ce0
- (id).cxx_construct;	// IMP=0x002000000010b1fd
- (void).cxx_destruct;	// IMP=0x001000000010b183
@property(readonly, nonatomic) CKSyncEngine *syncEngine; // @synthesize syncEngine=_syncEngine;
@property(readonly, nonatomic) CKContainer *container; // @synthesize container=_container;
- (void)syncEngine:(id)arg1 didUpdateMetadata:(id)arg2;	// IMP=0x001000000010b019
- (void)syncEngine:(id)arg1 recordWithIDWasDeleted:(id)arg2 recordType:(id)arg3;	// IMP=0x001000000010af21
- (void)syncEngine:(id)arg1 didFetchRecord:(id)arg2;	// IMP=0x001000000010ac7c
- (_Bool)syncEngine:(id)arg1 shouldFetchChangesForZoneID:(id)arg2;	// IMP=0x001000000010a9df
- (void)syncEngine:(id)arg1 failedToDeleteRecordWithID:(id)arg2 error:(id)arg3;	// IMP=0x001000000010a872
- (void)syncEngine:(id)arg1 didDeleteRecordWithID:(id)arg2;	// IMP=0x001000000010a790
- (void)syncEngine:(id)arg1 failedToSaveRecord:(id)arg2 error:(id)arg3;	// IMP=0x001000000010a4a8
- (void)syncEngine:(id)arg1 didSaveRecord:(id)arg2;	// IMP=0x001000000010a20d
- (id)syncEngine:(id)arg1 recordToSaveForRecordID:(id)arg2;	// IMP=0x0010000000109e16
- (void)syncEngine:(id)arg1 zoneWithIDWasPurged:(id)arg2;	// IMP=0x0010000000109d09
- (void)syncEngine:(id)arg1 zoneWithIDWasDeleted:(id)arg2;	// IMP=0x0010000000109bfc
- (void)syncEngine:(id)arg1 zoneWithIDChanged:(id)arg2;	// IMP=0x0010000000109b1a
- (void)syncEngine:(id)arg1 failedToDeleteRecordZoneWithID:(id)arg2 error:(id)arg3;	// IMP=0x0010000000109a22
- (void)syncEngine:(id)arg1 failedToSaveRecordZone:(id)arg2 error:(id)arg3;	// IMP=0x00100000001098ba
- (void)syncEngine:(id)arg1 didDeleteRecordZoneWithID:(id)arg2;	// IMP=0x00100000001097ad
- (void)syncEngine:(id)arg1 didSaveRecordZone:(id)arg2;	// IMP=0x00100000001096cb
- (void)receiveVO2MaxCloudKitDailyStatsFromWatch:(id)arg1;	// IMP=0x0010000000108d1e
- (void)resetDailyStats;	// IMP=0x0010000000108cdf
- (void)stopSyncing:(_Bool)arg1;	// IMP=0x0010000000108c7d
- (void)handleZonePurge:(id)arg1;	// IMP=0x0010000000108ab9
- (void)handleZoneDeleted:(id)arg1;	// IMP=0x00100000001088bd
- (void)handleZoneNotFound:(id)arg1;	// IMP=0x0010000000108672
- (void)handleUnknownItem:(id)arg1;	// IMP=0x00100000001084a2
- (void)handleServerRecordChanged:(id)arg1;	// IMP=0x0010000000108204
- (void)handleFetchedInputRecord:(id)arg1;	// IMP=0x0010000000107f72
- (void)updateInputSystemFields:(id)arg1 inputRecord:(id)arg2;	// IMP=0x0010000000107c13
- (id)createCKRecordForInput:(id)arg1;	// IMP=0x0010000000107677
- (void)handleFetchedOutputRecord:(id)arg1;	// IMP=0x00100000001073f9
- (void)updateOutputSystemFields:(id)arg1 outputRecord:(id)arg2;	// IMP=0x001000000010709a
- (id)createCKRecordForOutput:(id)arg1;	// IMP=0x0010000000106b21
- (id)getSystemFieldsFromCKRecord:(id)arg1;	// IMP=0x0010000000106aae
- (void)bulkUploadRecordIDsShouldReupload:(_Bool)arg1 shouldUploadToOutputZone:(_Bool)arg2 shouldUploadToInputZone:(_Bool)arg3 shouldThrottle:(_Bool)arg4;	// IMP=0x001000000010639c
- (void)addRecordIDsForSessionId:(id)arg1 shouldUploadToOutputZone:(_Bool)arg2 shouldUploadToInputZone:(_Bool)arg3;	// IMP=0x0010000000106024
- (MISSING_TYPE *)deleteZone: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000105ef3
- (void)createVO2MaxInputZone;	// IMP=0x0010000000105da1
- (void)createVO2MaxOutputZone;	// IMP=0x0010000000105c4f
- (void)initializeSyncEngine;	// IMP=0x0010000000105891
- (struct VO2MaxCloudKitSyncEngineMetadata)getCKSyncEngineMetadata;	// IMP=0x0010000000105762
- (void)updateDeviceUnlocked:(_Bool)arg1;	// IMP=0x001000000010566c
- (id)getUserRecordIDName;	// IMP=0x00100000001055ac
- (void)setUserRecordIDName:(id)arg1;	// IMP=0x0010000000105488
- (_Bool)shouldKeepLocalDataOnAccountChange;	// IMP=0x00100000001053ec
- (void)validateAccount;	// IMP=0x0010000000104b87
- (void)cloudKitAccountDidChange:(id)arg1;	// IMP=0x0010000000104b75
- (void)handleSyncUpload:(id)arg1;	// IMP=0x0010000000104611
- (void)onSyncActivity:(id)arg1;	// IMP=0x001000000010443c
- (void)resetSyncActivity:(id)arg1 withDelay:(long long)arg2;	// IMP=0x00100000001041b4
- (void)setUpSyncActivity;	// IMP=0x0010000000103a19
- (void)onDataProtectionNotification:(const int *)arg1 data:(const NotificationData_6933e140 *)arg2;	// IMP=0x00100000001039b8
- (void)saveRetrocomputedOutputs;	// IMP=0x0010000000103795
- (void)saveInputsAndOutputsForSessionId:(id)arg1;	// IMP=0x001000000010374d
- (void)endService;	// IMP=0x00100000001035e4
- (void)beginService;	// IMP=0x0010000000102e43
- (id)init;	// IMP=0x0010000000102db2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

