//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class HKHealthStore, NSMutableSet, NSString;

@interface CLVO2MaxService : CLIntersiloService
{
    HKHealthStore *fHkHealthStore;	// 8 = 0x8
    struct shared_ptr<CLVO2MaxInputCache> fInputCache;	// 16 = 0x10
    struct shared_ptr<CLVO2MaxInputStore> fInputStore;	// 32 = 0x20
    struct unique_ptr<CLVO2MaxStagingOutputStore, std::default_delete<CLVO2MaxStagingOutputStore>> fStagingOutputStore;	// 48 = 0x30
    struct unique_ptr<CLVO2MaxRetrocomputeRecorderDb, std::default_delete<CLVO2MaxRetrocomputeRecorderDb>> fRetrocomputeDb;	// 56 = 0x38
    int fDeleteHealthKitSamplesAttempts;	// 64 = 0x40
    _Bool fDeleteHealthKitSamplesSuccess;	// 68 = 0x44
    int fUpdateRetrocomputedDataAttempts;	// 72 = 0x48
    _Bool fUpdateRetrocomputedDataSuccess;	// 76 = 0x4c
    _Bool fTriggerRetrocomputeInProgress;	// 77 = 0x4d
    struct unique_ptr<CLNatalimetryNotifier_Type::Client, std::default_delete<CLNatalimetryNotifier_Type::Client>> fUserInfoClient;	// 80 = 0x50
    struct CLBodyMetrics fUserInfo;	// 88 = 0x58
    struct vector<VO2MaxStagingOutput, std::allocator<VO2MaxStagingOutput>> fPendingHealthKitWrites;	// 152 = 0x98
    NSMutableSet *_retrocomputeStatusClients;	// 176 = 0xb0
}

+ (_Bool)isSupported;	// IMP=0x00200000001455df
+ (id)getSilo;	// IMP=0x0010000000145546
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000014552d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000001454d0
- (id).cxx_construct;	// IMP=0x002000000014efa2
- (void).cxx_destruct;	// IMP=0x001000000014ef19
@property(retain, nonatomic) NSMutableSet *retrocomputeStatusClients; // @synthesize retrocomputeStatusClients=_retrocomputeStatusClients;
- (void)onUserInfoUpdate:(const int *)arg1 data:(const union NotificationData *)arg2;	// IMP=0x001000000014ec40
- (_Bool)updateRetrocomputeLastTimestampToHealthKit:(double)arg1;	// IMP=0x001000000014eb8a
- (void)updateRetrocomputeStatus:(int)arg1 unavailableReasons:(unsigned int)arg2;	// IMP=0x001000000014e8c6
- (void)deleteSessionsFromHealthKit:(vector_908f1be2)arg1 withRetry:(_Bool)arg2;	// IMP=0x001000000014e310
- (void)handleRetryHealthKitDeleteSamples:(id)arg1;	// IMP=0x001000000014e086
- (void)onRetryHealthKitDeleteSamples:(id)arg1;	// IMP=0x001000000014deb1
- (void)retryHealthKitDeleteSamples;	// IMP=0x001000000014dbbe
- (void)deleteHealthKitSamples:(_Bool)arg1;	// IMP=0x001000000014d8be
- (void)handleRetryTriggerRetrocompute:(id)arg1;	// IMP=0x001000000014d206
- (void)onRetryTriggerRetrocompute:(id)arg1;	// IMP=0x001000000014d031
- (void)retryTriggerRetrocompute;	// IMP=0x001000000014cc92
- (void)promoteStagingData:(id)arg1;	// IMP=0x001000000014cb0f
- (void)onRetrocomputeHealthKitSampleFailed:(id)arg1;	// IMP=0x001000000014caea
- (void)onRetrocomputeHealthKitSampleSavedWithStartTime:(double)arg1 activity:(id)arg2;	// IMP=0x001000000014c75c
- (void)saveStagingOutputToHealthKit:(struct VO2MaxStagingOutput)arg1 activity:(id)arg2;	// IMP=0x001000000014bf39
- (void)triggerRetrocompute:(CDUnknownBlockType)arg1;	// IMP=0x001000000014bb53
- (unsigned int)updateRetrocomputeHistoryPostProcessing:(struct VO2MaxRetrocomputeHistory *)arg1;	// IMP=0x001000000014b134
- (void)updateRetrocomputeHistory:(struct VO2MaxRetrocomputeHistory *)arg1 withResult:(struct VO2MaxRetrocomputeSessionResult)arg2;	// IMP=0x001000000014ad21
- (void)persistRetrocomputeResultsToStagingTables:(struct VO2MaxRetrocomputeSessionResult)arg1;	// IMP=0x001000000014aa13
- (unsigned int)retrocomputeSession:(const struct VO2MaxSessionAttributes *)arg1 withHealthKitSample:(struct VO2MaxHealthKitSample)arg2 withRetrocomputeHistory:(struct VO2MaxRetrocomputeHistory *)arg3;	// IMP=0x0010000000149697
- (int)getIndexInHealthKitSamples:(const void *)arg1 forSessionAttributes:(const struct VO2MaxSessionAttributes *)arg2 withStartIndex:(int)arg3;	// IMP=0x00100000001493dc
- (unsigned int)retrocomputeForSamples:(const void *)arg1 withRetrocomputeHistory:(struct VO2MaxRetrocomputeHistory *)arg2;	// IMP=0x0010000000148cc8
- (void)markXpcActivityDone:(id)arg1;	// IMP=0x0010000000148bc5
- (void)executeRetrocomputePreprocessing:(id)arg1;	// IMP=0x00100000001472b4
- (void)queryVO2MaxRetrocomputeStatusWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0010000000146f4f
- (void)onRetrocomputePreprocessingActivity:(id)arg1;	// IMP=0x0010000000146cda
- (void)resetRetrocomputePreProcessingActivity:(id)arg1 withDelay:(long long)arg2;	// IMP=0x0010000000146b18
- (void)scheduleRetrocomputePreprocessing;	// IMP=0x00100000001463bb
- (void)sendRetroComputeAnalytics;	// IMP=0x0010000000145d57
- (void)unregisterForRetrocomputeStatusUpdates:(byref id)arg1;	// IMP=0x0010000000145d26
- (void)registerForRetrocomputeStatusUpdates:(byref id)arg1;	// IMP=0x0010000000145b9c
- (void)endService;	// IMP=0x0010000000145aab
- (void)beginService;	// IMP=0x0010000000145625
- (id)init;	// IMP=0x00100000001455a2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

