//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CalTrackFinder;
@protocol CMStrideCalLocationFSMDelegate;

@interface CMStrideCalLocationFSM : NSObject
{
    int fLocationState;	// 8 = 0x8
    CalTrackFinder *fTrackFinder;	// 16 = 0x10
    int fSource;	// 24 = 0x18
    id <CMStrideCalLocationFSMDelegate> _delegate;	// 32 = 0x20
}

@property(nonatomic) id <CMStrideCalLocationFSMDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) int locationState; // @synthesize locationState=fLocationState;
- (void)feedPedometerData:(const union NotificationData *)arg1;	// IMP=0x00100000005817e8
- (void)feedGpsOdometerData:(const union NotificationData *)arg1;	// IMP=0x00100000005817a9
- (void)feedLocationData:(const void *)arg1;	// IMP=0x001000000058164e
- (int)originDeviceToGpsSource:(int)arg1 locationType:(int)arg2;	// IMP=0x00100000005815e7
- (void)requestTransitionToLocationState:(int)arg1;	// IMP=0x0010000000581354
- (void)dealloc;	// IMP=0x0010000000581308

@end

