//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface TRANSITPbLocationFingerprint : PBCodable
{
    struct {
        unsigned long long *list;
        unsigned long long count;
        unsigned long long size;
    } _macs;	// 8 = 0x8
    struct {
        double *list;
        unsigned long long count;
        unsigned long long size;
    } _modes;	// 32 = 0x20
    double _latitude;	// 56 = 0x38
    unsigned long long _locationId;	// 64 = 0x40
    double _longitude;	// 72 = 0x48
    struct {
        unsigned int latitude:1;
        unsigned int locationId:1;
        unsigned int longitude:1;
    } _has;	// 80 = 0x50
}

@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(nonatomic) unsigned long long locationId; // @synthesize locationId=_locationId;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000493ff6
- (unsigned long long)hash;	// IMP=0x0010000000493d8a
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000493ca4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000493bce
- (void)copyTo:(id)arg1;	// IMP=0x0010000000493a57
- (void)writeTo:(id)arg1;	// IMP=0x0010000000493971
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000493964
- (id)dictionaryRepresentation;	// IMP=0x00100000004932e2
- (id)description;	// IMP=0x001000000049326b
- (void)setModes:(double *)arg1 count:(unsigned long long)arg2;	// IMP=0x0010000000493254
- (double)modesAtIndex:(unsigned long long)arg1;	// IMP=0x00100000004931ba
- (void)addModes:(double)arg1;	// IMP=0x00100000004931a9
- (void)clearModes;	// IMP=0x0010000000493198
@property(readonly, nonatomic) double *modes;
@property(readonly, nonatomic) unsigned long long modesCount;
- (void)setMacs:(unsigned long long *)arg1 count:(unsigned long long)arg2;	// IMP=0x001000000049315e
- (unsigned long long)macsAtIndex:(unsigned long long)arg1;	// IMP=0x00100000004930c5
- (void)addMacs:(unsigned long long)arg1;	// IMP=0x00100000004930b1
- (void)clearMacs;	// IMP=0x00100000004930a0
@property(readonly, nonatomic) unsigned long long *macs;
@property(readonly, nonatomic) unsigned long long macsCount;
@property(nonatomic) _Bool hasLongitude;
@property(nonatomic) _Bool hasLatitude;
@property(nonatomic) _Bool hasLocationId;
- (void)dealloc;	// IMP=0x0010000000492f50

@end

