//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC15ScreenTimeAgent6Daemon : NSObject
{
    MISSING_TYPE *factory;	// 8 = 0x8
    MISSING_TYPE *$__lazy_storage_$_mirroringMonitor;	// 128 = 0x80
    MISSING_TYPE *$__lazy_storage_$_persistenceController;	// 136 = 0x88
    MISSING_TYPE *$__lazy_storage_$_notificationManager;	// 144 = 0x90
    MISSING_TYPE *$__lazy_storage_$_screenTimeOrganizationController;	// 152 = 0x98
    MISSING_TYPE *$__lazy_storage_$_askForTimeListener;	// 160 = 0xa0
    MISSING_TYPE *$__lazy_storage_$_askForTimeListenerDelegate;	// 168 = 0xa8
    MISSING_TYPE *$__lazy_storage_$_askForTimeEventRelay;	// 176 = 0xb0
    MISSING_TYPE *$__lazy_storage_$_askForTimeResponseHandler;	// 184 = 0xb8
    MISSING_TYPE *$__lazy_storage_$_commandLineToolListener;	// 192 = 0xc0
    MISSING_TYPE *$__lazy_storage_$_commandLineToolListenerDelegate;	// 200 = 0xc8
    MISSING_TYPE *$__lazy_storage_$_publicAgentListener;	// 208 = 0xd0
    MISSING_TYPE *$__lazy_storage_$_privateAgentListener;	// 216 = 0xd8
    MISSING_TYPE *$__lazy_storage_$_contactsAgentListener;	// 224 = 0xe0
    MISSING_TYPE *$__lazy_storage_$_agentListenerDelegate;	// 232 = 0xe8
    MISSING_TYPE *$__lazy_storage_$_coreAnalyticsManager;	// 240 = 0xf0
    MISSING_TYPE *$__lazy_storage_$_storeServer;	// 248 = 0xf8
    MISSING_TYPE *$__lazy_storage_$_bootstrapperQueue;	// 256 = 0x100
    MISSING_TYPE *$__lazy_storage_$_xpcServiceProvider;	// 264 = 0x108
    MISSING_TYPE *organizationControllerAdapter;	// 272 = 0x110
    MISSING_TYPE *reactor;	// 280 = 0x118
}

- (void).cxx_destruct;	// IMP=0x00000000000ac1a0
- (id)init;	// IMP=0x00100000000ac120
- (void)start;	// IMP=0x00100000000ab630

@end

