//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableDictionary, NSString;

@interface STUnifiedTransportPayload : NSObject
{
    NSDictionary *_payloadDictionary;	// 8 = 0x8
    NSMutableDictionary *_userInfo;	// 16 = 0x10
    NSArray *_destinations;	// 24 = 0x18
}

+ (id)classFallbacksForKeyedArchiver;	// IMP=0x002000000009df13
+ (_Bool)supportsSecureCoding;	// IMP=0x001000000009dbaa
+ (id)_descriptionDictionaryForPayloadDictionary:(id)arg1 type:(id)arg2;	// IMP=0x001000000009d58d
+ (id)_descriptionDictionaryForSettingsPayloadDictionary:(id)arg1;	// IMP=0x001000000009d47f
+ (id)_descriptionDictionaryForBlueprintPayloadDictionary:(id)arg1;	// IMP=0x001000000009d371
+ (id)_descriptionDictionaryForCheckinResponsePayloadDictionary:(id)arg1;	// IMP=0x001000000009cf81
+ (id)_descriptionDictionaryForCheckinRequestPayloadDictionary:(id)arg1;	// IMP=0x001000000009c960
+ (id)_descriptionDictionariesForSettingsDictionaries:(id)arg1;	// IMP=0x001000000009c38a
+ (id)_descriptionDictionariesForBlueprintDictionaries:(id)arg1;	// IMP=0x001000000009be84
- (void).cxx_destruct;	// IMP=0x002000000009dfa5
@property(copy, nonatomic) NSArray *destinations; // @synthesize destinations=_destinations;
@property(readonly, nonatomic) NSMutableDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(readonly, copy, nonatomic) NSDictionary *payloadDictionary; // @synthesize payloadDictionary=_payloadDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000009df20
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000009dea5
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000009dbb2
- (id)description;	// IMP=0x001000000009da81
@property(readonly, copy, nonatomic) NSString *payloadType;
@property(copy, nonatomic) NSString *UUID;
- (id)initWithPayload:(id)arg1 userInfo:(id)arg2;	// IMP=0x001000000009bc7d
- (id)initWithPayload:(id)arg1 type:(id)arg2 userInfo:(id)arg3;	// IMP=0x001000000009bbda
- (id)initWithPayload:(id)arg1 type:(id)arg2;	// IMP=0x001000000009bbc5

@end

