//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKSystemAppHeartbeat, BKSystemShellClient, BKSystemShellControlServiceListener, BKSystemShellDescriptor, BKSystemShellServiceListener, BSCompoundAssertion, NSArray, NSMapTable, NSMutableDictionary, NSMutableOrderedSet, NSMutableSet, NSSet, NSString;

@interface BKSystemShellSentinel : NSObject
{
    BKSystemShellServiceListener *_shellListener;	// 8 = 0x8
    BKSystemShellControlServiceListener *_controlListener;	// 16 = 0x10
    BKSystemAppHeartbeat *_heartbeat;	// 24 = 0x18
    struct os_unfair_lock_s _lock;	// 32 = 0x20
    BKSystemShellClient *_lock_systemApp;	// 40 = 0x28
    NSMutableDictionary *_lock_pidToClient;	// 48 = 0x30
    NSMutableOrderedSet *_lock_connectedSystemApps;	// 56 = 0x38
    NSMutableSet *_lock_shellsFinishedStartup;	// 64 = 0x40
    NSMapTable *_lock_checkinCompletionsBySystemApp;	// 72 = 0x48
    _Bool _lock_migratorDidComplete;	// 80 = 0x50
    _Bool _lock_systemAppBlocked;	// 81 = 0x51
    NSString *_lock_activeAlternateSystemAppBundleIdentifier;	// 88 = 0x58
    NSString *_lock_activeAlternateSystemAppJobLabel;	// 96 = 0x60
    struct os_unfair_lock_s _collectivePingDataLock;	// 104 = 0x68
    NSMutableSet *_collectivePingDataLock_collectivePingShells;	// 112 = 0x70
    BSCompoundAssertion *_observers;	// 120 = 0x78
    int _overrideConnectionPID;	// 128 = 0x80
}

+ (id)sharedInstance;	// IMP=0x002000000005c4a7
- (void).cxx_destruct;	// IMP=0x002000000005bf51
- (void)terminateShellWithJobLabel:(id)arg1;	// IMP=0x001000000005bbc2
- (oneway void)setWatchdogMonitoringEnabled:(id)arg1;	// IMP=0x001000000005bb43
- (oneway void)restartWithOptions:(id)arg1;	// IMP=0x001000000005baaa
- (oneway void)finishedLaunching;	// IMP=0x001000000005b73a
- (void)checkInAndWaitForDataMigration:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000005b379
- (_Bool)_lock_unblockSystemApp;	// IMP=0x001000000005b2d3
- (_Bool)_lock_blockSystemApp;	// IMP=0x001000000005af62
- (void)_lock_handleRelaunchRequestFromSystemApp:(id)arg1 withOptions:(unsigned long long)arg2;	// IMP=0x001000000005ae6a
- (void)_lock_updatePrimarySystemApp;	// IMP=0x001000000005a6dd
- (void)_lock_bootstrapSystemApp;	// IMP=0x001000000005a569
- (id)_lock_currentConnectionShell;	// IMP=0x001000000005a487
- (_Bool)_pingSystemShellForCollectiveWatchdog:(id)arg1;	// IMP=0x001000000005a28c
- (id)_collectivePingSystemShellSet;	// IMP=0x001000000005a24e
- (void)_removeSystemShellFromCollectivePingSet:(id)arg1;	// IMP=0x001000000005a1fa
- (void)_addSystemShellToCollectivePingSet:(id)arg1;	// IMP=0x001000000005a183
- (id)systemApp;	// IMP=0x001000000005a171
- (id)systemApplications;	// IMP=0x001000000005a15f
- (void)systemShellDidTerminate:(int)arg1;	// IMP=0x0010000000059f66
- (void)systemShellDidConnect:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000059cda
- (_Bool)unblockSystemApp;	// IMP=0x0010000000059ca3
- (_Bool)blockSystemApp;	// IMP=0x0010000000059c6c
- (_Bool)collectiveWatchdogPing;	// IMP=0x0010000000059a34
- (void)dataMigratorDidComplete;	// IMP=0x00100000000599fe
- (void)startSystemAppCheckInServer;	// IMP=0x00100000000599c3
- (id)systemShellState;	// IMP=0x0010000000059880
@property(readonly, copy, nonatomic) NSSet *shellsFinishedStartup;
@property(readonly, copy, nonatomic) NSArray *systemShells;
@property(readonly, copy, nonatomic) BKSystemShellDescriptor *primarySystemShell;
@property(copy) NSString *activeAlternateSystemAppBundleIdentifier;
- (_Bool)auditTokenRepresentsSystemApp:(CDStruct_6ad76789 *)arg1;	// IMP=0x0010000000059621
- (id)addSystemShellObserver:(id)arg1 reason:(id)arg2;	// IMP=0x0010000000059602
@property(readonly, copy) NSString *description;
- (void)invalidate;	// IMP=0x00100000000594df
- (id)init;	// IMP=0x001000000005930f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

