//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSSet;

__attribute__((visibility("hidden")))
@interface ABSContactsReality : NSObject
{
    NSSet *_meIdentifiers;	// 8 = 0x8
    _Bool _ignoreContactAccountIDs;	// 16 = 0x10
}

+ (id)containerForContact:(id)arg1 store:(id)arg2;	// IMP=0x004000000001ad58
- (void).cxx_destruct;	// IMP=0x002000000001b9d5
@property(nonatomic) _Bool ignoreContactAccountIDs; // @synthesize ignoreContactAccountIDs=_ignoreContactAccountIDs;
- (MISSING_TYPE *)isMeContact: /* Error: Ran out of types for this method. */;	// IMP=0x001000000001b9ad
- (void)reloadMeIdentifiersForStore:(id)arg1;	// IMP=0x001000000001b5d2
- (id)accountExternalIdentifierForContact:(id)arg1 inStore:(id)arg2;	// IMP=0x001000000001b04d
- (id)init;	// IMP=0x001000000001ad29

@end

