//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class ABSPBAlert, ABSPBDate, MISSING_TYPE, NSMutableArray, NSString;

@interface ABSPBContact : PBCodable
{
    NSMutableArray *_addresses;	// 8 = 0x8
    ABSPBDate *_birthday;	// 16 = 0x10
    ABSPBAlert *_callAlert;	// 24 = 0x18
    NSString *_departmentName;	// 32 = 0x20
    NSMutableArray *_emails;	// 40 = 0x28
    NSString *_familyName;	// 48 = 0x30
    NSString *_givenName;	// 56 = 0x38
    NSString *_identifier;	// 64 = 0x40
    NSString *_jobTitle;	// 72 = 0x48
    NSString *_middleName;	// 80 = 0x50
    NSString *_namePrefix;	// 88 = 0x58
    NSString *_nameSuffix;	// 96 = 0x60
    NSString *_nickname;	// 104 = 0x68
    MISSING_TYPE *_nonGregorianBirthday;	// 112 = 0x70
    NSString *_note;	// 120 = 0x78
    NSString *_organizationName;	// 128 = 0x80
    NSMutableArray *_phoneNumbers;	// 136 = 0x88
    NSString *_phonemeData;	// 144 = 0x90
    NSString *_phoneticFamilyName;	// 152 = 0x98
    NSString *_phoneticGivenName;	// 160 = 0xa0
    NSString *_phoneticMiddleName;	// 168 = 0xa8
    NSString *_phoneticOrganizationName;	// 176 = 0xb0
    NSString *_preferredChannel;	// 184 = 0xb8
    NSString *_previousFamilyName;	// 192 = 0xc0
    NSString *_pronunciationFamilyName;	// 200 = 0xc8
    NSString *_pronunciationGivenName;	// 208 = 0xd0
    ABSPBAlert *_textAlert;	// 216 = 0xd8
    NSMutableArray *_urls;	// 224 = 0xe0
}

+ (Class)addressesType;	// IMP=0x0020000000008cb6
+ (Class)emailsType;	// IMP=0x0010000000008be4
+ (Class)urlsType;	// IMP=0x0010000000008b12
+ (Class)phoneNumbersType;	// IMP=0x0010000000008a40
+ (id)toPBContact:(id)arg1;	// IMP=0x001000000001f11f
- (void).cxx_destruct;	// IMP=0x001000000000c944
@property(retain, nonatomic) NSString *preferredChannel; // @synthesize preferredChannel=_preferredChannel;
@property(retain, nonatomic) NSMutableArray *addresses; // @synthesize addresses=_addresses;
@property(retain, nonatomic) NSMutableArray *emails; // @synthesize emails=_emails;
@property(retain, nonatomic) NSMutableArray *urls; // @synthesize urls=_urls;
@property(retain, nonatomic) NSMutableArray *phoneNumbers; // @synthesize phoneNumbers=_phoneNumbers;
@property(retain, nonatomic) ABSPBAlert *textAlert; // @synthesize textAlert=_textAlert;
@property(retain, nonatomic) ABSPBAlert *callAlert; // @synthesize callAlert=_callAlert;
@property(retain, nonatomic) NSString *phonemeData; // @synthesize phonemeData=_phonemeData;
@property(retain, nonatomic) NSString *pronunciationFamilyName; // @synthesize pronunciationFamilyName=_pronunciationFamilyName;
@property(retain, nonatomic) NSString *pronunciationGivenName; // @synthesize pronunciationGivenName=_pronunciationGivenName;
@property(retain, nonatomic) NSString *phoneticMiddleName; // @synthesize phoneticMiddleName=_phoneticMiddleName;
@property(retain, nonatomic) NSString *phoneticGivenName; // @synthesize phoneticGivenName=_phoneticGivenName;
@property(retain, nonatomic) NSString *phoneticFamilyName; // @synthesize phoneticFamilyName=_phoneticFamilyName;
@property(retain, nonatomic) NSString *phoneticOrganizationName; // @synthesize phoneticOrganizationName=_phoneticOrganizationName;
@property(retain, nonatomic) ABSPBDate *nonGregorianBirthday; // @synthesize nonGregorianBirthday=_nonGregorianBirthday;
@property(retain, nonatomic) ABSPBDate *birthday; // @synthesize birthday=_birthday;
@property(retain, nonatomic) NSString *note; // @synthesize note=_note;
@property(retain, nonatomic) NSString *jobTitle; // @synthesize jobTitle=_jobTitle;
@property(retain, nonatomic) NSString *departmentName; // @synthesize departmentName=_departmentName;
@property(retain, nonatomic) NSString *organizationName; // @synthesize organizationName=_organizationName;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) NSString *nameSuffix; // @synthesize nameSuffix=_nameSuffix;
@property(retain, nonatomic) NSString *previousFamilyName; // @synthesize previousFamilyName=_previousFamilyName;
@property(retain, nonatomic) NSString *familyName; // @synthesize familyName=_familyName;
@property(retain, nonatomic) NSString *middleName; // @synthesize middleName=_middleName;
@property(retain, nonatomic) NSString *givenName; // @synthesize givenName=_givenName;
@property(retain, nonatomic) NSString *namePrefix; // @synthesize namePrefix=_namePrefix;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000000bdb1
- (unsigned long long)hash;	// IMP=0x001000000000ba86
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000b47a
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000ab40
- (void)copyTo:(id)arg1;	// IMP=0x001000000000a5b8
- (void)writeTo:(id)arg1;	// IMP=0x0010000000009f3d
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000009f30
- (id)dictionaryRepresentation;	// IMP=0x0010000000008d8b
- (id)description;	// IMP=0x0010000000008cdc
@property(readonly, nonatomic) _Bool hasPreferredChannel;
- (id)addressesAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000008c99
- (unsigned long long)addressesCount;	// IMP=0x0010000000008c7c
- (void)addAddresses:(id)arg1;	// IMP=0x0010000000008c12
- (void)clearAddresses;	// IMP=0x0010000000008bf5
- (id)emailsAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000008bc7
- (unsigned long long)emailsCount;	// IMP=0x0010000000008baa
- (void)addEmails:(id)arg1;	// IMP=0x0010000000008b40
- (void)clearEmails;	// IMP=0x0010000000008b23
- (id)urlsAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000008af5
- (unsigned long long)urlsCount;	// IMP=0x0010000000008ad8
- (void)addUrls:(id)arg1;	// IMP=0x0010000000008a6e
- (void)clearUrls;	// IMP=0x0010000000008a51
- (id)phoneNumbersAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000008a23
- (unsigned long long)phoneNumbersCount;	// IMP=0x0010000000008a06
- (void)addPhoneNumbers:(id)arg1;	// IMP=0x001000000000899c
- (void)clearPhoneNumbers;	// IMP=0x001000000000897f
@property(readonly, nonatomic) _Bool hasTextAlert;
@property(readonly, nonatomic) _Bool hasCallAlert;
@property(readonly, nonatomic) _Bool hasPhonemeData;
@property(readonly, nonatomic) _Bool hasPronunciationFamilyName;
@property(readonly, nonatomic) _Bool hasPronunciationGivenName;
@property(readonly, nonatomic) _Bool hasPhoneticMiddleName;
@property(readonly, nonatomic) _Bool hasPhoneticGivenName;
@property(readonly, nonatomic) _Bool hasPhoneticFamilyName;
@property(readonly, nonatomic) _Bool hasPhoneticOrganizationName;
@property(readonly, nonatomic) _Bool hasNonGregorianBirthday;
@property(readonly, nonatomic) _Bool hasBirthday;
@property(readonly, nonatomic) _Bool hasNote;
@property(readonly, nonatomic) _Bool hasJobTitle;
@property(readonly, nonatomic) _Bool hasDepartmentName;
@property(readonly, nonatomic) _Bool hasOrganizationName;
@property(readonly, nonatomic) _Bool hasNickname;
@property(readonly, nonatomic) _Bool hasNameSuffix;
@property(readonly, nonatomic) _Bool hasPreviousFamilyName;
@property(readonly, nonatomic) _Bool hasFamilyName;
@property(readonly, nonatomic) _Bool hasMiddleName;
@property(readonly, nonatomic) _Bool hasGivenName;
@property(readonly, nonatomic) _Bool hasNamePrefix;
@property(readonly, nonatomic) _Bool hasIdentifier;
- (id)toContact;	// IMP=0x001000000001d470

@end

