//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SpringBoardUIServices/SBUIRemoteAlertServiceViewController.h>

@class FontInstallMissingNavigationController, MISSING_TYPE, NSArray, NSMutableArray, NSString, NSXPCConnection, UIImage, UIStoryboard, UIViewController;

@interface FontInstallMissingController : SBUIRemoteAlertServiceViewController
{
    UIStoryboard *_storyboard;	// 8 = 0x8
    UIViewController *_initialViewController;	// 16 = 0x10
    NSXPCConnection *_connection;	// 24 = 0x18
    NSString *_cancelTitle;	// 32 = 0x20
    NSString *_noncancelTitle;	// 40 = 0x28
    NSString *_alertTitle;	// 48 = 0x30
    NSString *_messageText;	// 56 = 0x38
    UIImage *_mainIcon;	// 64 = 0x40
    MISSING_TYPE *_subIcon;	// 72 = 0x48
    FontInstallMissingNavigationController *_detailPresentationController;	// 80 = 0x50
    NSArray *_input;	// 88 = 0x58
    NSMutableArray *_output;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x0020000000003cfa
@property(retain, nonatomic) NSMutableArray *output; // @synthesize output=_output;
@property(retain, nonatomic) NSArray *input; // @synthesize input=_input;
- (void)doneWithMissingFonts:(id)arg1 withDismissAnimated:(_Bool)arg2;	// IMP=0x0010000000003a95
- (void)prepareForActivationWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000003928
- (void)configureControllersForInput;	// IMP=0x0010000000002c89
- (void)configureWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000002ad8
- (void)connectToEndpoint:(id)arg1;	// IMP=0x00100000000028eb
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0010000000002869
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00100000000027e5
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0010000000002199

@end

