//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface BDSSyncUserDefaults : NSObject
{
}

+ (id)_stateForLog;	// IMP=0x00400000000065a8
+ (void)_setService:(struct __CFString *)arg1 enabled:(_Bool)arg2;	// IMP=0x00100000000064b1
+ (_Bool)_isServiceDisabledAlternative:(struct __CFString *)arg1;	// IMP=0x0010000000006438
+ (_Bool)_isServiceEnabledAlternative:(struct __CFString *)arg1;	// IMP=0x00100000000063bf
+ (_Bool)_isBundleIdentifierInArray:(struct __CFArray *)arg1;	// IMP=0x0010000000006334
+ (id)makeOSStateHandler;	// IMP=0x00100000000062e4
+ (id)iCloudIdentity;	// IMP=0x001000000000628d
+ (_Bool)isGlobalICloudDriveSyncOptedIn;	// IMP=0x0010000000006274
+ (_Bool)isCloudKitSyncOptedIn;	// IMP=0x00100000000061db
+ (_Bool)isSignedIntoICloud;	// IMP=0x0010000000006135

@end

