//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreData/NSManagedObject.h>

@class NSString, RMAssetPayload, RMConfigurationPayload;

@interface RMAssetPayloadReference : NSManagedObject
{
}

- (id)reportDetails;	// IMP=0x0020000000008d35

// Remaining properties
@property(retain, nonatomic) RMAssetPayload *asset; // @dynamic asset;
@property(copy, nonatomic) NSString *assetIdentifier; // @dynamic assetIdentifier;
@property(retain, nonatomic) RMConfigurationPayload *configuration; // @dynamic configuration;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

