//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface RMConfigurationStatusQuerier : NSObject
{
}

- (id)statusForChannel:(id)arg1 declarationType:(id)arg2 declarationIdentifier:(id)arg3 serverToken:(id)arg4;	// IMP=0x004000000002468f

@end

