//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC7remindd8RDDaemon : NSObject
{
    MISSING_TYPE *xpcDaemon;	// 8 = 0x8
    MISSING_TYPE *xpcClientConnectionListener;	// 24 = 0x18
    MISSING_TYPE *accountStoresRemovalEventHandler;	// 32 = 0x20
    MISSING_TYPE *alarmEngine;	// 40 = 0x28
    MISSING_TYPE *todayEngine;	// 48 = 0x30
    MISSING_TYPE *assignmentNotificationEngine;	// 56 = 0x38
    MISSING_TYPE *hashtagLabelUpdater;	// 64 = 0x40
    MISSING_TYPE *applicationShortcutEngine;	// 72 = 0x48
    MISSING_TYPE *coreSuggestionController;	// 112 = 0x70
    MISSING_TYPE *suggestedAttributesAutoTrainer;	// 120 = 0x78
    MISSING_TYPE *widgetRefresh;	// 128 = 0x80
    MISSING_TYPE *housekeepingActivityScheduler;	// 136 = 0x88
    MISSING_TYPE *cloudConfigurationUpdater;	// 176 = 0xb0
    MISSING_TYPE *extraneousAlarmCleaner;	// 184 = 0xb8
    MISSING_TYPE *manualSortHintUpdater;	// 192 = 0xc0
}

- (void).cxx_destruct;	// IMP=0x004000000035e6b0
- (id)init;	// IMP=0x001000000035e660

@end

