//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSOperationQueue.h>

@interface NSOperationQueue (CloudKit)
- (_Bool)containsOperationToSaveRecordID:(id)arg1;	// IMP=0x001000000006cbb0
- (id)existingOperationToSaveRecordID:(id)arg1;	// IMP=0x001000000006c9ad
- (_Bool)containsOperationToFetchRecordID:(id)arg1;	// IMP=0x001000000006c97a
- (id)existingOperationToFetchRecordID:(id)arg1;	// IMP=0x001000000006c822
- (_Bool)containsOperationToDeleteRecordID:(id)arg1;	// IMP=0x001000000006c7ef
- (id)existingOperationToDeleteRecordID:(id)arg1;	// IMP=0x001000000006c697
@end

