//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface REMCDImageAttachment
{
}

+ (id)cdEntityName;	// IMP=0x0010000000005c2e
+ (_Bool)isAbstract;	// IMP=0x0010000000005c26
+ (id)fetchRequest;	// IMP=0x0010000000055f67
- (void)objectWasPushedToCloudWithOperation:(id)arg1 serverRecord:(id)arg2;	// IMP=0x0020000000219df0
- (id)attachmentRepresentationAndReturnError:(id *)arg1;	// IMP=0x00100000002987e0

// Remaining properties
@property(nonatomic) short height; // @dynamic height;
@property(nonatomic) short width; // @dynamic width;

@end

