//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SDMLFeedbackResourceManager : NSObject
{
}

+ (id)allTextAttributes;	// IMP=0x004000000001b5bd
+ (id)allTextFeatures;	// IMP=0x001000000001b4e8
+ (id)logKeyNameForAttributeName:(id)arg1 forOption:(unsigned long long)arg2;	// IMP=0x001000000001b464
+ (id)logKeyNameForAttributeName:(id)arg1 forFeatures:(id)arg2;	// IMP=0x001000000001b43c

@end

