//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDFetchLocationOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0040000000052d60
+ (id)requiredEntitlements;	// IMP=0x0010000000052d53
+ (id)whitelistedClassesForRequest;	// IMP=0x0010000000052d21
- (void)runWithRequest:(id)arg1;	// IMP=0x0010000000052e8a

@end

