//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDRemoveEffectivePolicyOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0040000000074eb0
+ (id)requiredEntitlements;	// IMP=0x0010000000074d66
+ (id)whitelistedClassesForRequest;	// IMP=0x0010000000074d34
- (void)runWithRequest:(id)arg1;	// IMP=0x0040000000074d73

@end

