//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDSetMaximumResidentUsersOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x0040000000079463
+ (id)whitelistedClassesForRequest;	// IMP=0x0010000000079431
- (void)runWithRequest:(id)arg1;	// IMP=0x0010000000079470

@end

