//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKGameServicePrivateInterface
{
}

+ (void)configureInterface:(id)arg1;	// IMP=0x00400000001225a9
+ (id)interfaceProtocol;	// IMP=0x0010000000122598

@end

