//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKRealTimeMultiplayerInitiateBulletin
{
    _Bool _isReconnect;	// 112 = 0x70
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x004000000003af8f
+ (_Bool)supportsSecureCoding;	// IMP=0x001000000003af87
@property _Bool isReconnect; // @synthesize isReconnect=_isReconnect;
- (void)loadDataWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000003e075
- (void)handleDeclineAction;	// IMP=0x001000000003def8
- (void)handleAcceptAction;	// IMP=0x001000000003da86
- (void)handleAction:(id)arg1;	// IMP=0x001000000003d6cf
- (void)assembleBulletin;	// IMP=0x001000000003ccfe
- (void)parseClientData:(id)arg1;	// IMP=0x001000000003ca38
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000003c849
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000003c650
- (id)initWithPushNotification:(id)arg1;	// IMP=0x001000000003c464

@end

