//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface BMRSignatureValidator : NSObject
{
}

+ (_Bool)_checkExpiryForDSL:(id)arg1 error:(id *)arg2;	// IMP=0x0040000000014bae
+ (struct __SecKey *)_getPublicKeyFromCertificateChain:(id)arg1 error:(id *)arg2;	// IMP=0x001000000001485c
+ (_Bool)validateSignedDSLPayload:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000145d8

@end

