//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSLock, NSManagedObjectContext, NSMutableDictionary, NSPersistentContainer, NSString, NSURL;
@protocol OS_dispatch_queue;

@interface SYDCoreDataStore : NSObject
{
    _Bool _shouldLogValues;	// 8 = 0x8
    NSPersistentContainer *__persistentContainer;	// 16 = 0x10
    NSURL *_URL;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_persistentContainerQueue;	// 32 = 0x20
    NSString *_fileProtectionType;	// 40 = 0x28
    NSManagedObjectContext *_transactionContext;	// 48 = 0x30
    NSMutableDictionary *_contexts;	// 56 = 0x38
    NSLock *_contextsLock;	// 64 = 0x40
}

+ (_Bool)isInvalidTokenError:(id)arg1;	// IMP=0x004000000006c753
+ (_Bool)isCorruptionError:(id)arg1;	// IMP=0x001000000006c2a8
+ (id)managedObjectModel;	// IMP=0x001000000006b407
- (void).cxx_destruct;	// IMP=0x002000000006c8f4
@property(retain, nonatomic) NSLock *contextsLock; // @synthesize contextsLock=_contextsLock;
@property(retain, nonatomic) NSMutableDictionary *contexts; // @synthesize contexts=_contexts;
- (void);	// IMP=0x001000000006c8ad
@property(retain, nonatomic) NSManagedObjectContext *transactionContext; // @synthesize transactionContext=_transactionContext;
@property(retain, nonatomic) NSString *fileProtectionType; // @synthesize fileProtectionType=_fileProtectionType;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *persistentContainerQueue; // @synthesize persistentContainerQueue=_persistentContainerQueue;
@property(nonatomic) _Bool shouldLogValues; // @synthesize shouldLogValues=_shouldLogValues;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) NSPersistentContainer *_persistentContainer; // @synthesize _persistentContainer=__persistentContainer;
- (_Bool)_queue_handleCorruptionIfNecessaryFromError:(id)arg1 inPersistentStoreCoordinator:(id)arg2;	// IMP=0x001000000006c4c9
- (void)handleCorruptionIfNecessaryFromError:(id)arg1 inPersistentStoreCoordinator:(id)arg2;	// IMP=0x001000000006c182
- (void)transactionStoreDidSave:(id)arg1;	// IMP=0x001000000006c106
- (_Bool)saveTransaction:(id *)arg1;	// IMP=0x001000000006be84
- (id)transactionalStoreWithError:(id *)arg1;	// IMP=0x001000000006bd42
- (unsigned long long)fileSizeBytes;	// IMP=0x001000000006b8d4
- (void)_queue_destroyPersistentStoreInPersistentStoreCoordinator:(id)arg1;	// IMP=0x001000000006b730
- (void)destroyPersistentStore;	// IMP=0x001000000006b57e
- (id)persistentContainerWithError:(id *)arg1;	// IMP=0x001000000006abd6
- (_Bool)saveContext:(id)arg1 reason:(id)arg2 includingTransactionContext:(_Bool)arg3 error:(id *)arg4;	// IMP=0x001000000006aa09
- (void)clearContexts;	// IMP=0x001000000006a95d
- (id)_contextForStoreIdentifier:(id)arg1 persistentContainer:(id)arg2;	// IMP=0x001000000006a7a7
- (id)contextForStoreIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000006a69b
- (id)managedKeyValuesMatchingPredicate:(id)arg1 inContext:(id)arg2 error:(id *)arg3;	// IMP=0x001000000006a46d
- (id)managedKeyValueWithRecordName:(id)arg1 inStoreWithIdentifier:(id)arg2 inContext:(id)arg3 error:(id *)arg4;	// IMP=0x001000000006a234
- (id)managedKeyValueWithKey:(id)arg1 inStoreWithIdentifier:(id)arg2 createIfNecessary:(_Bool)arg3 forceCreateNewRow:(_Bool)arg4 inContext:(id)arg5 error:(id *)arg6;	// IMP=0x0010000000069da9
- (id)managedKeyValueWithKey:(id)arg1 inStoreWithIdentifier:(id)arg2 createIfNecessary:(_Bool)arg3 inContext:(id)arg4 error:(id *)arg5;	// IMP=0x0010000000069d88
- (id)managedStoreWithIdentifier:(id)arg1 createIfNecessary:(_Bool)arg2 inContext:(id)arg3 error:(id *)arg4;	// IMP=0x0010000000069a90
- (id)managedDatabaseCreateIfNecessary:(_Bool)arg1 inContext:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000069866
- (id)syncEngineMetadataWithError:(id *)arg1;	// IMP=0x00100000000695d7
- (_Bool)saveSyncEngineMetadata:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000069345
- (id)dictionaryRepresentationForStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000689bb
- (short)failedMigrationCountWithError:(id *)arg1;	// IMP=0x0010000000068789
- (_Bool)setFailedMigrationCount:(short)arg1 error:(id *)arg2;	// IMP=0x0010000000068467
- (_Bool)didMigrateFromPlistsWithError:(id *)arg1;	// IMP=0x0010000000068239
- (_Bool)setDidMigrateFromPlists:(_Bool)arg1 error:(id *)arg2;	// IMP=0x0010000000067f18
- (id)acAccountIdentifierWithError:(id *)arg1;	// IMP=0x0010000000067cc7
- (_Bool)setACAccountIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000679f7
- (_Bool)clearServerSystemFieldsRecordsForAllStoresWithError:(id *)arg1;	// IMP=0x00100000000674e3
- (id)changedKeysForStoreIdentifier:(id)arg1 sinceChangeToken:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000065cde
- (id)currentChangeTokenForStoreIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000657e1
- (unsigned long long)numberOfKeyValuesInStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000006544e
- (_Bool)clearServerSystemFieldsRecordsForAllKeyValuesInStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000064ed7
- (id)allStoreIdentifiersWithError:(id *)arg1;	// IMP=0x001000000006497d
- (id)allRecordNamesInStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000006442f
- (_Bool)deleteDataForStoresMatchingPredicate:(id)arg1 context:(id)arg2 error:(id *)arg3;	// IMP=0x001000000006415b
- (_Bool)deleteDataForAllStoresWithError:(id *)arg1;	// IMP=0x0010000000064096
- (_Bool)deleteDataForStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000063f7c
- (_Bool)saveServerSyncAnchorSystemFieldsRecordData:(id)arg1 forStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000063c0a
- (id)serverSyncAnchorSystemFieldsRecordDataForStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000638cb
- (_Bool)removeKeyValueForRecordName:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000063505
- (_Bool)removeKeyValueForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x00100000000634ed
- (_Bool)removeKeyValueForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 excludeFromChangeTracking:(_Bool)arg3 error:(id *)arg4;	// IMP=0x00100000000630cb
- (_Bool)saveKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x00100000000630b3
- (_Bool)_saveKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2 excludeFromChangeTracking:(_Bool)arg3 enforceQuota:(_Bool)arg4 forceCreateNewRow:(_Bool)arg5 error:(id *)arg6;	// IMP=0x001000000006266f
- (_Bool)saveKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2 excludeFromChangeTracking:(_Bool)arg3 enforceQuota:(_Bool)arg4 error:(id *)arg5;	// IMP=0x0010000000062653
- (_Bool)saveKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2 excludeFromChangeTracking:(_Bool)arg3 error:(id *)arg4;	// IMP=0x0010000000062631
- (id)keyValueFromManagedKeyValue:(id)arg1;	// IMP=0x00100000000624aa
- (id)keyValueForRecordName:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x001000000006212e
- (id)keyValueForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 createIfNecessary:(_Bool)arg3 error:(id *)arg4;	// IMP=0x0010000000061b6b
- (id)description;	// IMP=0x0010000000061ac9
- (void)dealloc;	// IMP=0x0010000000061a54
- (id)initWithURL:(id)arg1 fileProtectionType:(id)arg2 persistentContainer:(id)arg3 isTransactional:(_Bool)arg4;	// IMP=0x0010000000061790
- (id)initWithURL:(id)arg1 fileProtectionType:(id)arg2;	// IMP=0x0010000000061778
- (id)initWithURL:(id)arg1;	// IMP=0x001000000006175c

@end

