//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSString, SKUIApplicationController, ServiceProductPageConfiguration, UINavigationController;
@protocol ServiceStoreProductViewControllerDelegate;

@interface ServiceStoreProductViewController : UIViewController
{
    CDUnknownBlockType _starRatingCompletionBlock;	// 8 = 0x8
    SKUIApplicationController *_applicationController;	// 16 = 0x10
    _Bool _preview;	// 24 = 0x18
    _Bool _didPurchase;	// 25 = 0x19
    _Bool _didStart;	// 26 = 0x1a
    UINavigationController *_loadingPlaceholderViewController;	// 32 = 0x20
    ServiceProductPageConfiguration *_pageConfiguration;	// 40 = 0x28
    _Bool _didLoad;	// 48 = 0x30
    _Bool _didShow;	// 49 = 0x31
    _Bool _presentingOnboarding;	// 50 = 0x32
    NSString *_logKey;	// 56 = 0x38
    _Bool _shouldShowOnboarding;	// 64 = 0x40
    id <ServiceStoreProductViewControllerDelegate> _delegate;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0020000000011733
@property(nonatomic) _Bool shouldShowOnboarding; // @synthesize shouldShowOnboarding=_shouldShowOnboarding;
@property(nonatomic) __weak id <ServiceStoreProductViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;	// IMP=0x00100000000115ab
- (void)setupWithClientBundleID:(id)arg1 bagType:(long long)arg2;	// IMP=0x0010000000011436
- (void)setVisibleInClientWindow:(id)arg1;	// IMP=0x0010000000011430
- (void)setUsageContext:(id)arg1;	// IMP=0x001000000001142a
- (void)setShowsStoreButton:(_Bool)arg1;	// IMP=0x001000000001140d
- (void)setShowsRightBarButton:(_Bool)arg1;	// IMP=0x00100000000113f0
- (void)setScriptContextDictionary:(id)arg1;	// IMP=0x00100000000113d3
- (void)setRightBarButtonTitle:(id)arg1;	// IMP=0x00100000000113b6
- (void)setPromptString:(id)arg1;	// IMP=0x0010000000011399
- (void)setProductPageStyle:(id)arg1;	// IMP=0x001000000001135d
- (void)setPreview:(id)arg1;	// IMP=0x00100000000112d5
- (void)setClientIdentifier:(id)arg1;	// IMP=0x001000000001123d
- (void)setCancelButtonTitle:(id)arg1;	// IMP=0x0010000000011220
- (void)setAskToBuy:(_Bool)arg1;	// IMP=0x0010000000011203
- (void)setAffiliateIdentifier:(id)arg1;	// IMP=0x0010000000011189
- (void)setAdditionalBuyParameters:(id)arg1;	// IMP=0x001000000001110f
- (void)loadProductWithURL:(id)arg1;	// IMP=0x001000000001109d
- (void)loadProductWithRequest:(id)arg1;	// IMP=0x0010000000010f0a
- (void)loadProductWithPageDictionary:(id)arg1;	// IMP=0x0010000000010e32
- (void)finishStarRatingPromptWithRating:(id)arg1;	// IMP=0x0010000000010dce
- (void)finishImmediately;	// IMP=0x0010000000010dad
- (void)_sendDidFinishWithResult:(long long)arg1;	// IMP=0x0010000000010bf7
- (void)applicationDidDisplayFirstPage:(id)arg1;	// IMP=0x0010000000010aad
- (void)application:(id)arg1 didStopWithOptions:(id)arg2;	// IMP=0x00100000000108f5
- (void)application:(id)arg1 didFailToLoadWithError:(id)arg2;	// IMP=0x001000000001077b
- (void)application:(id)arg1 didCompleteSoftwarePurchase:(id)arg2;	// IMP=0x001000000001076a
- (void)application:(id)arg1 didCompletePurchase:(id)arg2;	// IMP=0x0010000000010759
- (id)legacyScriptInterfaceForApplication:(id)arg1;	// IMP=0x0010000000010740
- (void)_presentOnboardingIfNeededWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000001015a
- (void)_cancelButtonAction:(id)arg1;	// IMP=0x0010000000010146
- (id)_newCancelButtonItemWithClientContext:(id)arg1;	// IMP=0x001000000001004a
- (void)_sendInstallAttributionIfAllowed;	// IMP=0x001000000000fbe3
- (id)_clientViewControllerProxy;	// IMP=0x001000000000fb93
- (void)_startIfReady;	// IMP=0x001000000000f9fd
- (void)loadProductWithParameters:(id)arg1;	// IMP=0x001000000000f925
- (void)dealloc;	// IMP=0x001000000000f8c0
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x001000000000f85f
- (void)viewDidLayoutSubviews;	// IMP=0x001000000000f6f6
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x001000000000f489
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x001000000000f12b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

