//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface CKKSItemEncrypter : NSObject
{
}

+ (id)decryptDictionary:(id)arg1 key:(id)arg2 authenticatedData:(id)arg3 error:(id *)arg4;	// IMP=0x0040000000064342
+ (MISSING_TYPE *)encryptDictionary:key:authenticatedData:error: /* Error: Ran out of types for this method. */;	// IMP=0x00100000000641e1
+ (id)decryptItemToDictionary:(id)arg1 keyCache:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000063f90
+ (id)decryptItemToDictionaryVersion1or2:(id)arg1 keyCache:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000063c64
+ (id)decryptItemToDictionaryVersionNone:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000063bf1
+ (id)encryptCKKSItem:(id)arg1 dataDictionary:(id)arg2 updatingCKKSItem:(id)arg3 parentkey:(id)arg4 keyCache:(id)arg5 error:(id *)arg6;	// IMP=0x00100000000636af
+ (id)removePaddingFromData:(id)arg1;	// IMP=0x0010000000063617
+ (id)padData:(id)arg1 blockSize:(unsigned long long)arg2 additionalBlock:(_Bool)arg3;	// IMP=0x00100000000634bb

@end

