//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CKKSListenerCollection, NSString;

__attribute__((visibility("hidden")))
@interface OTSOSActualAdapter : NSObject
{
    _Bool sosEnabled;	// 8 = 0x8
    _Bool _essential;	// 9 = 0x9
    NSString *_providerID;	// 16 = 0x10
    CKKSListenerCollection *_peerChangeListeners;	// 24 = 0x18
}

+ (id)sosCKKSViewList;	// IMP=0x002000000008f3e5
- (void).cxx_destruct;	// IMP=0x002000000008e739
@property(retain) CKKSListenerCollection *peerChangeListeners; // @synthesize peerChangeListeners=_peerChangeListeners;
@property(readonly) NSString *providerID; // @synthesize providerID=_providerID;
@property _Bool essential; // @synthesize essential=_essential;
@property _Bool sosEnabled; // @synthesize sosEnabled;
- (_Bool)resetToOffering:(id *)arg1;	// IMP=0x001000000008e607
- (_Bool)joinAfterRestore:(id *)arg1;	// IMP=0x001000000008e534
- (_Bool)safariViewSyncingEnabled:(id *)arg1;	// IMP=0x001000000008e4cd
- (id)currentState;	// IMP=0x001000000008e3ec
- (void)sendTrustedPeerSetChangedUpdate;	// IMP=0x001000000008e36e
- (void)sendSelfPeerChangedUpdate;	// IMP=0x001000000008e2f0
- (void)registerForPeerChangeUpdates:(id)arg1;	// IMP=0x001000000008e27e
- (_Bool)updateCKKS4AllStatus:(_Bool)arg1 error:(id *)arg2;	// IMP=0x001000000008e109
- (_Bool)updateOctagonKeySetWithAccount:(id)arg1 error:(id *)arg2;	// IMP=0x001000000008d9c9
- (_Bool)preloadOctagonKeySetOnAccount:(id)arg1 error:(id *)arg2;	// IMP=0x001000000008d21f
- (id)fetchTrustedPeers:(id *)arg1;	// IMP=0x001000000008d02a
- (id)fetchSelfPeers:(id *)arg1;	// IMP=0x001000000008cfc8
- (id)currentSOSSelf:(id *)arg1;	// IMP=0x001000000008ca01
- (int)circleStatus:(id *)arg1;	// IMP=0x001000000008c9a7
@property(readonly, copy) NSString *description;
- (id)initAsEssential:(_Bool)arg1;	// IMP=0x001000000008c814

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

