//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString, SECC2MPGenericEventMetricValue;

__attribute__((visibility("hidden")))
@interface SECC2MPGenericEventMetric : PBCodable
{
    NSString *_key;	// 8 = 0x8
    SECC2MPGenericEventMetricValue *_value;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000836b1
@property(retain, nonatomic) SECC2MPGenericEventMetricValue *value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000835ed
- (unsigned long long)hash;	// IMP=0x00100000000835a0
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000834d8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000008343a
- (void)copyTo:(id)arg1;	// IMP=0x00100000000833d7
- (void)writeTo:(id)arg1;	// IMP=0x001000000008337a
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000008336d
- (id)dictionaryRepresentation;	// IMP=0x00100000000832bc
- (id)description;	// IMP=0x001000000008320d
@property(readonly, nonatomic) _Bool hasValue;
@property(readonly, nonatomic) _Bool hasKey;

@end

