//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, SOSAccount;

__attribute__((visibility("hidden")))
@interface SOSClient : NSObject
{
    SOSAccount *_account;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000228f2f
@property(retain) SOSAccount *account; // @synthesize account=_account;
- (id)sosIsEnabledString;	// IMP=0x0010000000228ebc
- (_Bool)sosIsEnabled;	// IMP=0x0000000000228dca
- (void)sosIsEnabledCB:(CDUnknownBlockType)arg1;	// IMP=0x0010000000228d0b
- (void)sosEnable;	// IMP=0x0010000000228c8d
- (void)sosDisable;	// IMP=0x0010000000228c0f
- (void)removeV0Peers:(CDUnknownBlockType)arg1;	// IMP=0x0010000000228b9d
- (void)iCloudIdentityStatus_internal:(CDUnknownBlockType)arg1;	// IMP=0x0010000000228b2b
- (void)rpcTriggerRingUpdate:(CDUnknownBlockType)arg1;	// IMP=0x0010000000228a6c
- (void)rpcTriggerBackup:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000022898e
- (void)keyStatusFor:(int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x0010000000228916
- (void)accountStatus:(CDUnknownBlockType)arg1;	// IMP=0x00100000002288a4
- (void)iCloudIdentityStatus:(CDUnknownBlockType)arg1;	// IMP=0x0010000000228832
- (void)ghostBustInfo:(CDUnknownBlockType)arg1;	// IMP=0x00100000002287c0
- (void)ghostBustPeriodic:(unsigned int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x0010000000228748
- (void)ghostBustTriggerTimed:(unsigned int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00100000002286d0
- (void)ghostBust:(unsigned int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x0010000000228658
- (void)setWatchdogParmeters:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00100000002285d2
- (void)getWatchdogParameters:(CDUnknownBlockType)arg1;	// IMP=0x0010000000228560
- (void)rpcTriggerSync:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00100000002284b2
- (void)importInitialSyncCredentials:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00100000002283cf
- (void)initialSyncCredentials:(unsigned int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x0010000000228301
- (void)joinCircleWithBlob:(id)arg1 version:(int)arg2 complete:(CDUnknownBlockType)arg3;	// IMP=0x0010000000228275
- (void)circleJoiningBlob:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00100000002281ef
- (void)circleHash:(CDUnknownBlockType)arg1;	// IMP=0x001000000022817d
- (void)myPeerInfo:(CDUnknownBlockType)arg1;	// IMP=0x001000000022810b
- (void)stashAccountCredential:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x0010000000228085
- (void)validatedStashedAccountCredential:(CDUnknownBlockType)arg1;	// IMP=0x0010000000228013
- (void)assertStashedAccountCredential:(CDUnknownBlockType)arg1;	// IMP=0x0010000000227fa1
- (void)stashedCredentialPublicKey:(CDUnknownBlockType)arg1;	// IMP=0x0010000000227f2f
- (void)rateLimitingPerformanceCounters:(CDUnknownBlockType)arg1;	// IMP=0x0010000000227ebd
- (void)kvsPerformanceCounters:(CDUnknownBlockType)arg1;	// IMP=0x0010000000227e4b
- (void)userPublicKey:(CDUnknownBlockType)arg1;	// IMP=0x0010000000227dd9
- (_Bool)checkEntitlement:(id)arg1;	// IMP=0x0010000000227dd1
- (id)initSOSClientWithAccount:(id)arg1;	// IMP=0x0010000000227d66

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

