//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class RDFileURLs;
@protocol OS_dispatch_queue, RDCacheDeleteDelegate;

@interface RDCacheDelete : NSObject
{
    id <RDCacheDeleteDelegate> _delegate;	// 8 = 0x8
    id <RDCacheDeleteDelegate> _analyticsDelegate;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_q;	// 24 = 0x18
    RDFileURLs *_fileURLs;	// 32 = 0x20
}

+ (void)initialize;	// IMP=0x00400000000034ab
- (void).cxx_destruct;	// IMP=0x0020000000003530
- (void)dealloc;	// IMP=0x00100000000034e6

@end

