//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary, NSNumber, NSString, NSURL;
@protocol GSAdditionStoring, GSAdditionStoring><GSAdditionStoringPrivate, NSCopying><NSSecureCoding;

@interface GSAddition : NSObject
{
    NSObject<GSAdditionStoring><GSAdditionStoringPrivate> *_storage;	// 8 = 0x8
    unsigned long long _options;	// 16 = 0x10
    NSNumber *_size;	// 24 = 0x18
    NSString *_namespace;	// 32 = 0x20
    NSURL *_url;	// 40 = 0x28
    NSString *_originalName;	// 48 = 0x30
    NSString *_displayName;	// 56 = 0x38
    NSDictionary *_userInfo;	// 64 = 0x40
}

+ (id)makeNameForUser:(unsigned int)arg1 name:(id)arg2;	// IMP=0x0040000000010310
- (void).cxx_destruct;	// IMP=0x002000000001035f
@property(readonly, nonatomic) NSObject<GSAdditionStoring> *storage; // @synthesize storage=_storage;
- (id);	// IMP=0x001000000001034b
@property(readonly, nonatomic) unsigned long long options; // @synthesize options=_options;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
- (id)replaceItemAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x001000000001023a
- (_Bool)copyAdditionContentToURL:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000101bf
- (_Bool)internalStat:(struct stat *)arg1;	// IMP=0x001000000001018e
- (_Bool)mergeUserInfo:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000010149
- (_Bool)setNameSpace:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000100b2
- (_Bool)setDisplayName:(id)arg1 error:(id *)arg2;	// IMP=0x001000000001004d
- (_Bool)setOptions:(unsigned long long)arg1 error:(id *)arg2;	// IMP=0x0010000000010019
- (id)_initWithStorage:(id)arg1 andDictionary:(id)arg2;	// IMP=0x001000000000ff79
- (void)_refreshWithDictionary:(id)arg1;	// IMP=0x001000000000fe68
- (id)init;	// IMP=0x001000000000fdfc
- (id)description;	// IMP=0x001000000000fd6f
- (unsigned long long)hash;	// IMP=0x001000000000fcf4
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000fbdc
- (_Bool)refreshWithError:(id *)arg1;	// IMP=0x001000000000fb80
@property(readonly, nonatomic) NSDictionary *userInfo;
- (id)userInfoWithError:(id *)arg1;	// IMP=0x001000000000fb17
@property(readonly, nonatomic) NSString *originalPOSIXName;
- (id)originalPOSIXNameWithError:(id *)arg1;	// IMP=0x001000000000f925
@property(readonly, nonatomic) NSString *displayName;
- (id)displayNameWithError:(id *)arg1;	// IMP=0x001000000000f83c
@property(readonly, nonatomic) id <NSCopying><NSSecureCoding> persistentIdentifier;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSNumber *size;
@property(readonly, nonatomic) _Bool isSavedConflict;
@property(readonly, nonatomic) NSData *sandboxExtension;

// Remaining properties
@property(readonly, nonatomic) NSString *nameSpace; // @synthesize nameSpace=_namespace;

@end

