//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC5FilesP33_6C1A47974E8480CF19F978326BC049AE23DOCCircularProgressView : UIView
{
    MISSING_TYPE *fractionCompleted;	// 8 = 0x8
    MISSING_TYPE *changeAnimationDuration;	// 16 = 0x10
    MISSING_TYPE *borderLayer;	// 24 = 0x18
    MISSING_TYPE *progressLayer;	// 32 = 0x20
    MISSING_TYPE *indeterminateLayer;	// 40 = 0x28
    MISSING_TYPE *minSize;	// 48 = 0x30
    MISSING_TYPE *progressBorderColor;	// 64 = 0x40
    MISSING_TYPE *progressFillColor;	// 72 = 0x48
    MISSING_TYPE *progressBackgroundColor;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x00400000001a6940
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000001a68c0
- (void)layoutSublayersOfLayer:(id)arg1;	// IMP=0x00100000001a54b0
- (void)tintColorDidChange;	// IMP=0x00100000001a5110
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000001a4da0

@end

