//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface _TtC5Files29DOCRecentsEmptyViewController
{
}

- (id)initWithCoder:(id)arg1;	// IMP=0x0040000000319030
- (void)effectiveAppearanceDidChange:(id)arg1;	// IMP=0x0010000000318f10
- (void)loadView;	// IMP=0x0010000000318ee0

@end

