//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@interface _TtC5Files30DOCModalBlurViewControllerView : UIView
{
}

- (id)initWithCoder:(id)arg1;	// IMP=0x00400000002820d0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000282060
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;	// IMP=0x0010000000281ff0

@end

