//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@interface _TtC5Files7DOCView : UIView
{
}

- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0040000000319fa0
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000319f50

@end

