//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreData/NSManagedObject.h>

@class NSDate, NSMutableSet, NSNumber, NSString;

@interface MicroPaymentClient : NSManagedObject
{
}

+ (id)entityForContext:(id)arg1;	// IMP=0x004000000003f5e4
- (void)setValuesWithClientIdentity:(id)arg1;	// IMP=0x002000000004087a
- (id)replacePayment:(id)arg1 withPurchaseResponse:(id)arg2;	// IMP=0x00100000000401b1
- (id)mergeResponse:(id)arg1 withOptions:(long long)arg2;	// IMP=0x001000000003f631

// Remaining properties
@property(retain, nonatomic) NSNumber *allowsBootstrapCellularData; // @dynamic allowsBootstrapCellularData;
@property(retain, nonatomic) NSString *bundleVersion; // @dynamic bundleVersion;
@property(retain, nonatomic) NSNumber *hidesConfirmationDialogs; // @dynamic hidesConfirmationDialogs;
@property(retain, nonatomic) NSString *identifier; // @dynamic identifier;
@property(retain, nonatomic) NSNumber *ignoresInAppPurchaseRestriction; // @dynamic ignoresInAppPurchaseRestriction;
@property(retain, nonatomic) NSDate *lastQueueCheckDate; // @dynamic lastQueueCheckDate;
@property(retain, nonatomic) NSMutableSet *payments; // @dynamic payments;
@property(retain, nonatomic) NSString *receiptDirectoryPath; // @dynamic receiptDirectoryPath;
@property(retain, nonatomic) NSNumber *requiresAuthenticationForPayment; // @dynamic requiresAuthenticationForPayment;
@property(retain, nonatomic) NSNumber *sandboxed; // @dynamic sandboxed;
@property(retain, nonatomic) NSNumber *storeIdentifier; // @dynamic storeIdentifier;
@property(retain, nonatomic) NSNumber *storeVersion; // @dynamic storeVersion;
@property(retain, nonatomic) NSNumber *usesIdentityAttributes; // @dynamic usesIdentityAttributes;
@property(retain, nonatomic) NSString *vendorIdentifier; // @dynamic vendorIdentifier;

@end

