//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CloudArtworkOperationQueue, ICConnectionConfiguration, ICURLSession, ML3MusicLibrary, MPMediaDownloadManager, MSVWatchdog, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface CloudArtworkImporter : NSObject
{
    ML3MusicLibrary *_musicLibrary;	// 8 = 0x8
    ICConnectionConfiguration *_configuration;	// 16 = 0x10
    long long _sourceType;	// 24 = 0x18
    ICURLSession *_artworkDownloadSession;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_artworkDownloadAccessQueue;	// 40 = 0x28
    CloudArtworkOperationQueue *_artworkDownloadOperationQueue;	// 48 = 0x30
    NSMutableDictionary *_artworkDownloadOperationMap;	// 56 = 0x38
    NSString *_powerAssertionIdentifier;	// 64 = 0x40
    MSVWatchdog *_artworkDownloadWatchdog;	// 72 = 0x48
    MPMediaDownloadManager *_downloadManager;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x00200000000ca8d0
@property(retain, nonatomic) MPMediaDownloadManager *downloadManager; // @synthesize downloadManager=_downloadManager;
@property(retain, nonatomic) MSVWatchdog *artworkDownloadWatchdog; // @synthesize artworkDownloadWatchdog=_artworkDownloadWatchdog;
@property(copy, nonatomic) NSString *powerAssertionIdentifier; // @synthesize powerAssertionIdentifier=_powerAssertionIdentifier;
@property(retain, nonatomic) NSMutableDictionary *artworkDownloadOperationMap; // @synthesize artworkDownloadOperationMap=_artworkDownloadOperationMap;
@property(retain, nonatomic) CloudArtworkOperationQueue *artworkDownloadOperationQueue; // @synthesize artworkDownloadOperationQueue=_artworkDownloadOperationQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *artworkDownloadAccessQueue; // @synthesize artworkDownloadAccessQueue=_artworkDownloadAccessQueue;
@property(retain, nonatomic) ICURLSession *artworkDownloadSession; // @synthesize artworkDownloadSession=_artworkDownloadSession;
@property(readonly, nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
@property(readonly, nonatomic) ICConnectionConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) ML3MusicLibrary *musicLibrary; // @synthesize musicLibrary=_musicLibrary;
- (void)_adjustOperationQueueStatusForMediaDownloads;	// IMP=0x00100000000ca695
- (void)downloadManager:(id)arg1 didCancelAssets:(id)arg2;	// IMP=0x00100000000ca683
- (void)downloadManager:(id)arg1 didFinishAsset:(id)arg2 withError:(id)arg3;	// IMP=0x00100000000ca671
- (void)downloadManager:(id)arg1 didUpdateDownloadProgress:(id)arg2;	// IMP=0x00100000000ca65f
- (void)downloadManager:(id)arg1 didEnqueueAssetDownloads:(id)arg2 didRemoveAssetDownloads:(id)arg3;	// IMP=0x00100000000ca64d
- (void)cancelAllImports;	// IMP=0x00100000000ca639
- (void)cancelAllImportsAndWaitForOperationsToFinish:(_Bool)arg1;	// IMP=0x00100000000ca582
- (void)increasePriorityForAllOperations;	// IMP=0x00100000000ca511
- (void)decreasePriorityForAllOperations;	// IMP=0x00100000000ca4a0
- (void)deprioritizeImportArtworkForCloudID:(unsigned long long)arg1 artworkType:(long long)arg2;	// IMP=0x00100000000ca419
- (void)importCloudArtworkForRequests:(id)arg1;	// IMP=0x00100000000ca362
- (void)importArtworkForCloudID:(unsigned long long)arg1 artworkType:(long long)arg2 token:(id)arg3 mediaType:(unsigned int)arg4 allowsCellularData:(_Bool)arg5 clientIdentity:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;	// IMP=0x00100000000ca1f8
- (void)dealloc;	// IMP=0x00100000000ca0f0
- (id)initWithConfiguration:(id)arg1 sourceType:(long long)arg2;	// IMP=0x00100000000c9c0a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

