//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface HSPCDetectedViewController
{
    _Bool _firstDetectedCard;	// 8 = 0x8
}

+ (id)viewControllerForCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x00400000000122df
@property(readonly, nonatomic, getter=isFirstDetectedCard) _Bool firstDetectedCard; // @synthesize firstDetectedCard=_firstDetectedCard;
- (id)commitConfiguration;	// IMP=0x0010000000012b6e
@property(readonly, nonatomic) NSString *prominentButtonTitleKey;
- (id)iconDescriptor;	// IMP=0x0010000000012a08
- (id)handleInstallationGuideURL;	// IMP=0x001000000001295a
- (id)initWithCenterContentView:(id)arg1;	// IMP=0x001000000001292b
- (id)initWithCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x001000000001249c

@end

