//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface HSPCNameAccessoryViewController
{
}

- (id)suggestedAccessoryName;	// IMP=0x004000000002c479
- (id)commitConfiguration;	// IMP=0x001000000002c2c4
- (void)viewDidLoad;	// IMP=0x001000000002c243
- (id)initWithCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x001000000002c02a

@end

